; YXHK versioned Simplified Chinese translations.
mautic.integration.Amazon.endpoint="S3终点"
mautic.integration.Amazon.region="S3区"
mautic.integration.form.feature.cloud_storage="连接到云存储"
mautic.integration.form.provider.settings="供应商设置"
mautic.integration.keyfield.OpenCloud.containerName="窗口存储路径"
mautic.integration.keyfield.amazons3.bucket="Bucket 路径"
