; YXHK versioned Simplified Chinese translations.
mautic.campaign.error.contact_not_in_campaign="接触%contact% 不在活动中%campaign%."
mautic.campaign.error.decision_cannot_be_scheduled="无法计划决策类型事件。事件：%event%，运动：%campaign%，联系人：%contact%."
mautic.campaign.error.edit_events.request_invalid="此项目的参数中缺少contactId和/或eventId。"
mautic.campaign.error.event_already_executed="事件%event% 在竞选中%campaign% 已在以下位置执行%dateTriggered% 用于接触%contact%."
mautic.campaign.error.event_must_be_scheduled="事件%event% 在竞选中%campaign% 必须与联系人一起计划或标记为完成%contact% 尚未有日志条目。"
mautic.campaign.error.export.file_not_found="无法创建导出文件：%path%"
mautic.campaign.error.export.no_campaigns_selected="未找到要导出的活动。"
mautic.campaign.error.export.no_data="未找到活动导出的数据：%objectId%"
mautic.campaign.error.import.file.missing="文件'%file%'在文件系统中找不到。请重试。"
mautic.campaign.error.notfound="没有ID为的活动%id% 已找到！"
mautic.campaign.notice.batch_deleted="%count% 活动已被删除！"
mautic.campaign.notice.import.canceled="活动导入已成功取消。"
mautic.campaign.notice.import.finished="'%name%' (ID: %id%）已成功导入。"
mautic.campaign.notice.import.undo="上次导入已成功撤消。"
mautic.campaign.notice.import.undo_no_data="未找到可撤消导入的数据。"
