; YXHK versioned Simplified Chinese translations.
mautic.campaign.event.delete="删除"
mautic.campaign.event.delete.confirmation="您将要将联系人从此事件重定向到另一个事件。此操作无法撤消。"
mautic.campaign.event.delete.error="删除事件时出错。"
mautic.campaign.event.delete.generic_error="处理您的请求时出错。"
mautic.campaign.event.delete.last_event="您不能删除活动中的最后一个事件。请先创建新的操作或条件事件并保存活动，然后删除此事件。"
mautic.campaign.event.delete.redirect_contacts="将为该事件安排的现有联系人重定向到另一个事件："
mautic.campaign.event.delete.redirect_event="重定向事件"
mautic.campaign.event.delete.select_redirect="您必须先选择重定向事件，然后才能继续。这可确保联系人在整个市场活动流程中继续。"
mautic.campaign.event.delete.unable_delete_last="无法删除市场活动中的最后一个事件"
mautic.campaign.event.first_execution_date="开始"
mautic.campaign.event.id="ID"
mautic.campaign.event.last_execution_date="上次运行"
mautic.campaign.event.max_rotations="最大旋转"
mautic.campaign.event.negative_path_count="条件未满足"
mautic.campaign.event.not_executed="此活动尚未运行"
mautic.campaign.event.pending_executions="排队"
mautic.campaign.event.positive_path_count="条件满足"
mautic.campaign.event.total_executions="次运行"
mautic.campaign.event.unique_executions="唯一运行"
