; YXHK versioned Simplified Chinese translations.
mautic.campaign.add_new_source="添加一个联络人来源 ..."
mautic.campaign.allow_restart="允许联系人重启该活动"
mautic.campaign.allow_restart.tooltip="在允许的情况下，如果一个联系人因为某些原因被移出活动，之后又被添加回来，他将从流程开始重新进行活动流程。"
mautic.campaign.api.import.incorrect_upload_file_format="不支持的文件类型。仅支持ZIP存档。"
mautic.campaign.api.import.incorrect_zip_file="没有JSON 找到个内容，并且必须上载一个ZIP文件。"
mautic.campaign.api.import.upload_failed="文件上载失败或超过服务器大小限制。"
mautic.campaign.api.import.uploaded_file_no_exist="磁盘上不存在插入的文件路径。"
mautic.campaign.auto_organize="整理"
mautic.campaign.builder="营销活动构建器"
mautic.campaign.campaign="推广活动"
mautic.campaign.campaign.addremovelead="添加或删除联络人"
mautic.campaign.campaign.description="<strong>推广活动描述：</strong> %description%"
mautic.campaign.campaign.id="推广活动 ID "
mautic.campaign.campaign.import="导入"
mautic.campaign.campaign.import.cancel="取消"
mautic.campaign.campaign.import.cancelconfirm="好"
mautic.campaign.campaign.import.cancelmessage="您确定要取消汇入吗？"
mautic.campaign.campaign.import.count="计数"
mautic.campaign.campaign.import.create_entity="创建新实体"
mautic.campaign.campaign.import.donotleave="请不要离开这个页面，直到完成。"
mautic.campaign.campaign.import.email_notice="电子邮件地址未包含在与“%emailName%'以保护敏感数据。请添加相关地址以使活动正常运行。转到'%emailName%'以更新此必需信息。"
mautic.campaign.campaign.import.entity="实体"
mautic.campaign.campaign.import.error="失败了!"
mautic.campaign.campaign.import.finished="导入成功：默认情况下已关闭导入的广告系列。"
mautic.campaign.campaign.import.follow_campaign_action="将遵循父活动操作"
mautic.campaign.campaign.import.follow_form="将遵循父窗体"
mautic.campaign.campaign.import.inprogress="导入进行中。"
mautic.campaign.campaign.import.instructions="上传包含要导入的联系人的ZIP文件。最多%size%MB可以上传。"
mautic.campaign.campaign.import.name="名"
mautic.campaign.campaign.import.newmessage="您的导入包含%create_count% 将创建的新记录。"
mautic.campaign.campaign.import.proceed="进行"
mautic.campaign.campaign.import.stats="%created% 已创建， %merged% 已合并, %ignored% 已忽略"
mautic.campaign.campaign.import.status.created="创建"
mautic.campaign.campaign.import.status.updated="更新"
mautic.campaign.campaign.import.success="成功！"
mautic.campaign.campaign.import.title="导入活动"
mautic.campaign.campaign.import.undo="撤销"
mautic.campaign.campaign.import.undoconfirm="您确定要撤消导入吗？"
mautic.campaign.campaign.import.update_entity="更新实体"
mautic.campaign.campaign.import.updatemessage="您的导入包含%update_count% 将被更新的现有记录。此操作无法撤消。"
mautic.campaign.campaign.import.upload.button="上传"
mautic.campaign.campaign.jump_to_event="跳转到事件"
mautic.campaign.campaign.jump_to_event.target_not_exist="要跳转的目标已经不存在了"
mautic.campaign.campaign.launch.builder="打开推广活动生成器"
mautic.campaign.campaign.leads="添加联络人"
mautic.campaign.campaign.reimport="导入新"
mautic.campaign.campaign.searchcommand.isexpired="is:expired"
mautic.campaign.campaign.searchcommand.isexpired.description="过滤已过期的活动"
mautic.campaign.campaign.searchcommand.ispending="is:pending"
mautic.campaign.campaign.searchcommand.ispending.description="计划在未来推出的活动的筛选器"
mautic.campaign.campaign_export_file.name="MauticCampaignExport-%date%.zip文件"
mautic.campaign.campaigns="推广活动"
mautic.campaign.changelog.event_removed="删除的事件"
mautic.campaign.changelog.event_removed_details="事件“%event_name%\" (ID: %event_id%）已删除。"
mautic.campaign.changelog.event_updated="活动添加/更新"
mautic.campaign.changelog.event_updated_details="的事件ID: %event_id% 已添加或更新。"
mautic.campaign.changelog.settings_updated="已更新广告系列设置"
mautic.campaign.changelog.source.updated="已更新活动来源"
mautic.campaign.command.messages.sent="信息已发送： %events%"
mautic.campaign.command.process.messages="处理信息队列"
mautic.campaign.connection.trigger.date.label="等待直至  %full%"
mautic.campaign.connection.trigger.date.label_inaction="根据 %full%"
mautic.campaign.connection.trigger.interval.label="等待 %number% %unit%"
mautic.campaign.connection.trigger.interval.label_inaction="限于 %number% %unit%"
mautic.campaign.contentblock.copy="根据联系人行为、数据或时间序列触发电子邮件、更新分数、更改细分等。"
mautic.campaign.contentblock.heading="打造个性化的客户旅程"
mautic.campaign.contentblock.subheading="设计自动化工作流程，通过定制体验指导联系人。"
mautic.campaign.dashboard.widgets="市场活动控件"
mautic.campaign.deleted="删除"
mautic.campaign.email.send.to.user="发送邮件给用户"
mautic.campaign.email_stats="电子邮件统计"
mautic.campaign.email_stats.hour="每小时电子邮件指标"
mautic.campaign.email_stats.weekday="每周电子邮件指标"
mautic.campaign.event.action.descr="在触发时自动执行任务（例如发送电子邮件）。"
mautic.campaign.event.action.header="操作"
mautic.campaign.event.actions.header="操作"
mautic.campaign.event.addremovelead="修改推广活动"
mautic.campaign.event.addremovelead_descr="在某个事件被触发后，将联络人添加到特定的市场活动，或从该市场活动中删除"
mautic.campaign.event.back_to_panel="返回事件选择面板"
mautic.campaign.event.campaign_unpublished="该活动仍未发布。"
mautic.campaign.event.cancel="取消本次活动（以后无法重新安排）。"
mautic.campaign.event.cancelled="该事件已经取消。重新安排并恢复其执行。"
mautic.campaign.event.cancelled.time="本事件原定于 %date% 执行，但被取消。"
mautic.campaign.event.clone.btn.tooltip="克隆"
mautic.campaign.event.clone.from="发件人"
mautic.campaign.event.clone.header="在此处插入克隆的事件"
mautic.campaign.event.clone.insert="插入"
mautic.campaign.event.clone.name="名"
mautic.campaign.event.clone.new.campaign="新运动"
mautic.campaign.event.clone.request.missing="克隆不再可用"
mautic.campaign.event.condition.descr="按已知的配置文件字段值或提交的表单数据进行筛选。"
mautic.campaign.event.condition.details="'检查是否'%field%“是%operator% \"%comparisonValue%\" (%value%评价目的：%path%.'"
mautic.campaign.event.condition.header="条件"
mautic.campaign.event.conditions.header="条件"
mautic.campaign.event.create="活动创建"
mautic.campaign.event.decision.descr="基于联系人行为的分支流程（例如打开电子邮件）。"
mautic.campaign.event.decision.header="判断"
mautic.campaign.event.decisions.header="判断"
mautic.campaign.event.delete="删除事件"
mautic.campaign.event.delete.do_not_redirect="不重定向"
mautic.campaign.event.delete.redirect_description="将为该事件安排的现有联系人重定向到另一个事件："
mautic.campaign.event.delete.redirect_event="重定向事件"
mautic.campaign.event.edit.btn.tooltip="编辑"
mautic.campaign.event.failed="为 %contact% 执行推广活动事件失败。"
mautic.campaign.event.failed.campaign.unpublished="由于多次事件失败，%campaign% 活动已取消发布。失败事件的名称为%event%."
mautic.campaign.event.failed.timeline="类型错误"
mautic.campaign.event.has_last_attempt_error="本事件在上次执行过程中遇到错误。"
mautic.campaign.event.id="ID"
mautic.campaign.event.inline.triggerimmediately="立即"
mautic.campaign.event.inline.triggerinterval="+ %interval% %unit%"
mautic.campaign.event.intervalunit.choice.d="天数(天数)"
mautic.campaign.event.intervalunit.choice.h="小时(小时数)"
mautic.campaign.event.intervalunit.choice.i="分钟(分钟数)"
mautic.campaign.event.intervalunit.choice.m="月(月数)"
mautic.campaign.event.intervalunit.choice.y="年(年数)"
mautic.campaign.event.intervalunit.d="{0} 天|{1} 天|[2,Inf] 天"
mautic.campaign.event.intervalunit.h="{0} 小时|{1} 小时|[2,Inf] 小时"
mautic.campaign.event.intervalunit.i="{0} 分钟|{1} 分钟|[2,Inf] 分钟"
mautic.campaign.event.intervalunit.m="{0} 月|{1} 月|[2,Inf] 月"
mautic.campaign.event.intervalunit.y="{0} 年|{1} 年|[2,Inf] 年"
mautic.campaign.event.jump_to_event="跳转到事件"
mautic.campaign.event.jump_to_event_descr="跳转到活动流程中选择的事件"
mautic.campaign.event.last_error="上次执行错误"
mautic.campaign.event.leadchange="市场活动联络人变更"
mautic.campaign.event.leadchange_descr="当某个联络人被添加到或从市场活动中删除时，触发操作"
mautic.campaign.event.message.descr="通过联系人首选的渠道发送信息。"
mautic.campaign.event.message.header="信息"
mautic.campaign.event.messages.header="信息"
mautic.campaign.event.path.tooltip="“联系人跟随着%path% 路径'"
mautic.campaign.event.redirected="（重定向自%original%)"
mautic.campaign.event.remove.btn.tooltip="删除"
mautic.campaign.event.reschedule="重新调度该事件。"
mautic.campaign.event.save="保存"
mautic.campaign.event.systemchanges.header="系统变更"
mautic.campaign.event.timed.choice.anniversary="是纪念日"
mautic.campaign.event.timed.choice.custom="定制"
mautic.campaign.event.timed.choice.today="是今天"
mautic.campaign.event.timed.choice.tomorrow="是明天"
mautic.campaign.event.timed.choice.yesterday="是昨天"
mautic.campaign.event.triggered="'%event%' 事件已触发"
mautic.campaign.event.triggered.description="由推广活动 '%campaign%' 中的 %lead% 触发"
mautic.campaign.event.upcoming="'%event%' 事件触发"
mautic.campaign.event.upcoming.description="将由推广活动 '%campaign%' 触发"
mautic.campaign.event.update="活动更新"
mautic.campaign.events="推广活动事件"
mautic.campaign.filter.placeholder="联络人来源过滤器"
mautic.campaign.form.addevent="使用右侧的列表来添加触发器和操作到推广流程。"
mautic.campaign.form.addtocampaigns="将联络人添加到"
mautic.campaign.form.confirmation.cancel_text="否"
mautic.campaign.form.confirmation.confirm_text="是"
mautic.campaign.form.confirmation.message="您确定要取消发布此市场活动并立即停止处理联系人和市场活动事件（包括计划事件）吗？"
mautic.campaign.form.confirmation.message.publish="所有计划的事件都将根据“重新发布行为”设置执行。当前设置为：%republishBehavior%."
mautic.campaign.form.confirmbatchdelete="是否删除选定的活动-这将永久删除其事件、计划操作和活动执行历史记录。"
mautic.campaign.form.confirmdelete="删除活动，%name%？这将永久删除其事件、计划操作和活动执行历史记录。"
mautic.campaign.form.jump_to_event="事件将跳转到"
mautic.campaign.form.lead_source="联络人来源"
mautic.campaign.form.modalheader="推广活动事件详情"
mautic.campaign.form.removefromcampaigns="从 ... 中删除联络人"
mautic.campaign.form.thiscampaign="本推广活动"
mautic.campaign.form.thiscampaign_restart="这个活动（重启活动）"
mautic.campaign.form.trigger_leadchanged="当联络人 ... 时，执行该操作"
mautic.campaign.form.type="执行该事件 ..."
mautic.campaign.form.type.date="在特定的日期/时间"
mautic.campaign.form.type.date_inaction="根据特定的日期/时间"
mautic.campaign.form.type.help="此事件将对新添加到活动中的联系人执行，即使计划日期已过。对于计划发送的电子邮件，如果你不希望联系人在过期日期之后收到该邮件，建议你取消发布该邮件。所有日期均以联系人的时区为准。"
mautic.campaign.form.type.immediate="立即"
mautic.campaign.form.type.interval="在相对的时间段内"
mautic.campaign.form.type.interval_inaction="在相对的时间段内"
mautic.campaign.form.type.interval_schedule_at="发送自"
mautic.campaign.form.type.interval_schedule_between_hours="或间隔多少小时"
mautic.campaign.form.type.interval_trigger_restricted_dow="仅在一周中选定的几天安排："
mautic.campaign.form.type.optimized="最佳接触"
mautic.campaign.form.type.trigger_window_day="在24小时内，以获得最佳时机"
mautic.campaign.form.type.trigger_window_week="7天内最好的一天"
mautic.campaign.form.type_inaction="若联络人不进行某个操作，则执行该事件 ..."
mautic.campaign.if="筛选条件"
mautic.campaign.last.publish.date="最后发布日期"
mautic.campaign.last.publish.date.tooltip="在选择了“重新发布时重新启动”选项以从其重新启动所有计划事件的情况下重新发布市场活动时，将考虑此日期。它是市场活动上次发布的日期，如果已发布，则是“发布截止日期”。"
mautic.campaign.lead.addtocompany="将联系人添加至公司"
mautic.campaign.lead.changeowner="修改联络人的所有者"
mautic.campaign.leadsource.form="表单"
mautic.campaign.leadsource.forms="表单"
mautic.campaign.leadsource.forms.tooltip="来自表单提交的联络人将被自动添加到这一市场活动。"
mautic.campaign.leadsource.header="联络人来源"
mautic.campaign.leadsource.header.singular="联络人来源"
mautic.campaign.leadsource.list="分组"
mautic.campaign.leadsource.lists="联络人分组"
mautic.campaign.leadsource.lists.tooltip="选定组中包含的联络人会自动添加到本市场活动中。"
mautic.campaign.locate="定位"
mautic.campaign.member.removed="联系人离开活动的百分比：%date%"
mautic.campaign.menu.edit="编辑推广活动"
mautic.campaign.menu.index="推广活动"
mautic.campaign.menu.new="新建推广活动"
mautic.campaign.message.send="发送的信息"
mautic.campaign.modify.warning="警告：本市场活动已经发布。修改事件或删除联络人群组可能影响正在执行的市场活动。"
mautic.campaign.noresults.tip="市场活动会导致与联络人之间基于设定条件的系列化互动。例如，当联络人打开某个邮件时，您可以发送一个跟踪邮件。或当联络人点击某个着陆页时，增加 10 个积分点。 "
mautic.campaign.permissions.campaigns="推广活动 - 用户可访问"
mautic.campaign.permissions.header="推广活动授权"
mautic.campaign.permissions.imports="导入 - 用户有权访问"
mautic.campaign.point.trigger="推广活动触发器"
mautic.campaign.point.trigger.changecampaigns="修改联络人所在的市场活动"
mautic.campaign.preview.header="预览"
mautic.campaign.rebuild.leads_affected="%leads% 联络人(组)受影响"
mautic.campaign.rebuild.no_lists="没有要重建的列表"
mautic.campaign.rebuild.not_found="推广活动 #%id% 不存在"
mautic.campaign.rebuild.rebuilding="为市场活动 %id% 重建联络人列表"
mautic.campaign.rebuild.to_be_added="总数为 %leads% 的联络人(组)被批量添加到 %batch%"
mautic.campaign.rebuild.to_be_removed="总数为 %leads% 的联络人(组)被从 %batch% 批量删除"
mautic.campaign.scheduled="推广活动事件规划设置成功"
mautic.campaign.share.archive_fetch_failed="无法从读取活动存档Mautic."
mautic.campaign.share.back_to_campaign="回到Campaign"
mautic.campaign.share.banner_image="横幅图片"
mautic.campaign.share.banner_image.help="用于卡片和详细信息页面横幅。带有横幅图像的包往往会获得更多的可见性。（PNG，JPEG或WebP，最大2MB）"
mautic.campaign.share.compatibility_section="兼容性"
mautic.campaign.share.description="描述"
mautic.campaign.share.description.help="描述有关此活动的所有重要内容。接受Markdown。最少100个字符。"
mautic.campaign.share.download="下载ZIP"
mautic.campaign.share.gallery.help="最多上传5张截图或图片。为每张图片提供ALT文本以方便访问。"
mautic.campaign.share.gallery_add_more="添加更多"
mautic.campaign.share.gallery_alt="ALT说明"
mautic.campaign.share.gallery_alt.placeholder="可访问性的图像描述"
mautic.campaign.share.gallery_image="图片"
mautic.campaign.share.gallery_title="画廊"
mautic.campaign.share.header="分享活动：%name%"
mautic.campaign.share.headline="标题"
mautic.campaign.share.headline.help="用几句话描述此活动的作用（显示在卡片和搜索结果上）。"
mautic.campaign.share.images_section="图像"
mautic.campaign.share.keywords="关键词"
mautic.campaign.share.keywords.help="逗号分隔的关键字（如电子邮件，滴，再参与）。这些工作就像标签的可重复性。"
mautic.campaign.share.keywords.placeholder="以逗号分隔的关键字。例如，email、drop、re-engagement"
mautic.campaign.share.languages="语言"
mautic.campaign.share.languages.help="选择此活动可用的所有语言。"
mautic.campaign.share.open_marketplace="开放的市场"
mautic.campaign.share.opening_marketplace="正在打开市场..."
mautic.campaign.share.opening_marketplace.desc="将打开一个新窗口以确认在市场上发布。如果被阻止，请允许弹出窗口。"
mautic.campaign.share.panel_title="活动元数据"
mautic.campaign.share.popup_blocked="Marketplace窗口已被阻止。请允许此网站弹出窗口，然后重试。"
mautic.campaign.share.popup_closed="在发布完成之前，Marketplace窗口已关闭。"
mautic.campaign.share.price="价格"
mautic.campaign.share.price.coming_soon="付费软件包将在未来的更新中推出-现在每个软件包都是免费的。"
mautic.campaign.share.price.help="为空或设置为0表示免费软件包。"
mautic.campaign.share.price.notice="请注意：20%的价格将用于Mautic 支持正在进行开发的项目。"
mautic.campaign.share.pricing_section="定价"
mautic.campaign.share.publish="发布到市场"
mautic.campaign.share.publish_failed="发布失败。"
mautic.campaign.share.publish_success="活动已成功发布。"
mautic.campaign.share.publishing="正在发布到市场..."
mautic.campaign.share.redirecting="重定向到市场"
mautic.campaign.share.sending_archive="正在将活动档案发送到Marketplace."
mautic.campaign.share.title="名"
mautic.campaign.share.vendor_name="供应商名称"
mautic.campaign.share.vendor_name.invalid="供应商名称必须是字母数字和连字符（例如acme，my-org）。名称“mautic”是为官方软件包保留的。"
mautic.campaign.share.vendor_name.placeholder="例如，Acme"
mautic.campaign.share.version="包版本"
mautic.campaign.share.version.invalid="版本必须遵循语义版本控制（例如1.0.0、2.1.0-beta.1、1.2.3+build.01）。"
mautic.campaign.share.waiting_for_marketplace="正在等待商城确认..."
mautic.campaign.share.works_with="适用于"
mautic.campaign.share.works_with.help="选择所有Mautic 与此活动兼容版本"
mautic.campaign.share.works_with.min="至少选择一个兼容的Mautic 版本."
mautic.campaign.share_to_marketplace="分享到市场"
mautic.campaign.stat.contacts="联系人总数"
mautic.campaign.stat.contacts.tooltip="当前在此活动中的联系人总数"
mautic.campaign.stats="推广活动数据"
mautic.campaign.summarizing="以 %batch% 小时为一批，建立过去活动事件的汇总统计。将从最新事件向最旧事件回填数据。"
mautic.campaign.timeline.user_name="用户名"
mautic.campaign.trigger.decision_count_analyzed="%decisions% 的决定将会用于分析大约%leads%的联系人在%batch%批处理中不活跃的因素"
mautic.campaign.trigger.event_count="%events% 的事件被 %batch% 的联系人批处理了"
mautic.campaign.trigger.events_executed="{0} 总共执行了0个事件|{1} 总共执行了1个事件|[2，Inf]%count% 已执行的事件总数"
mautic.campaign.trigger.events_rescheduled="{0} 重新安排了总共0个事件|{1} 共1起事件被重新安排|[2，Inf]%count% 已重新计划的事件总数"
mautic.campaign.trigger.events_scheduled="{0} 共安排了0个事件|{1} 共安排了1起事件|[2，Inf]%count% 已排定的事件总数"
mautic.campaign.trigger.lead_count_processed="总数为 %leads% 的联络人(组) 在 %batch% 中得以批量处理"
mautic.campaign.trigger.negative="为了不活跃的联系人而触发的事件"
mautic.campaign.trigger.scheduled="触发调度事件"
mautic.campaign.trigger.starting="为了新添加的联系人而触发的事件"
mautic.campaign.trigger.triggering="推广活动 %id% 的触发事件"
mautic.campaign.triggered="触发的推广活动操作"
mautic.campaign.triggered.events="触发的事件"
mautic.campaign.unsaved="未保存的活动"
mautic.campaign.user.devent.description="<strong>事件描述：</strong> %description%"
mautic.campaign.user.event.triggered="已触发 <strong>%event%</strong> 事件"
mautic.campaign.when="检查是否"
mautic.campaignconfig.campaign_by_range="所有视图均使用日期范围"
mautic.campaignconfig.campaign_by_range.tooltip="操作、条件、决定和联系人选项卡将基于查看广告系列时提供的日期范围。"
mautic.campaignconfig.campaign_email_stats_enabled="启用活动电子邮件统计信息"
mautic.campaignconfig.campaign_email_stats_enabled.tooltip="在“活动”视图中启用电子邮件统计信息，例如每个工作日和每个小时的指标。"
mautic.campaignconfig.campaign_republish_behavior="活动重新发布行为"
mautic.campaignconfig.campaign_republish_behavior.count_all_time="无论发布状态如何，都对延迟进行计数"
mautic.campaignconfig.campaign_republish_behavior.count_only_while_published="仅在发布时计算延迟"
mautic.campaignconfig.campaign_republish_behavior.restart_on_publish="重新发布时重新启动"
mautic.campaignconfig.campaign_republish_behavior.use_global="使用全局设置"
mautic.campaignconfig.campaign_republish_behavior_tooltip="配置当活动在取消发布一段时间后重新发布时，工作流中间具有相对延迟的计划事件的行为方式。"
mautic.campaignconfig.campaign_time_wait_on_event_false="在重新尝试失败操作前的等待时间"
mautic.campaignconfig.campaign_time_wait_on_event_false_help="设置等待时间允许系统在短暂暂停后再次尝试操作，这有助于解决临时问题。"
mautic.campaignconfig.campaign_time_wait_on_event_false_tooltip="某个操作失败后，等待以下的时间然后再重新尝试"
mautic.campaignconfig.use_summary="使用汇总统计"
mautic.campaignconfig.use_summary.tooltip="通过使用汇总数据提高查看每天有数千个事件的活动时的性能。可能需要您通过SSH运行命令来回填数据一次。"
mautic.config.peak_interaction_timer.best_default_days="'默认最佳天数'"
mautic.config.peak_interaction_timer.best_default_days.tooltip="'选择在特定联系人数据不可用时被认为最适合进行交互的默认日期。'"
mautic.config.peak_interaction_timer.best_default_hour_end="'默认最佳结束时间'"
mautic.config.peak_interaction_timer.best_default_hour_end.tooltip="'设置特定联系人数据不可用时最佳交互窗口的默认结束时间。'"
mautic.config.peak_interaction_timer.best_default_hour_start="'默认最佳开始时间'"
mautic.config.peak_interaction_timer.best_default_hour_start.tooltip="'设置特定联系人数据不可用时最佳交互窗口的默认开始时间。'"
mautic.config.peak_interaction_timer.cache.month="'1个月'"
mautic.config.peak_interaction_timer.cache.off="'无缓存'"
mautic.config.peak_interaction_timer.cache_timeout="“交互数据缓存\""
mautic.config.peak_interaction_timer.cache_timeout.tooltip="'选择交互数据应缓存多长时间。选择“无缓存”可禁用缓存，选择“1个月”可将数据缓存一个月。'"
mautic.config.peak_interaction_timer.cache_timeout_min_message="“该高速缓存超时必须大于或等于0。”"
mautic.config.peak_interaction_timer.fetch.from_30_days="“过去30天”"
mautic.config.peak_interaction_timer.fetch.from_60_days="“过去60天”"
mautic.config.peak_interaction_timer.fetch.from_90_days="“过去90天”"
mautic.config.peak_interaction_timer.fetch_interactions_from="'获取交互自'"
mautic.config.peak_interaction_timer.fetch_interactions_from.tooltip="'选择获取交互数据的时间范围。这决定了系统将在多早以前查找交互。'"
mautic.config.peak_interaction_timer.fetch_limit="'交互获取限制'"
mautic.config.peak_interaction_timer.fetch_limit.tooltip="'设置要检索的每种类型的最大交互次数（例如，页面点击、电子邮件读取），以优化计时。'"
mautic.config.peak_interaction_timer.fetch_limit_min_message="'读取限制必须大于10。'"
mautic.config.peak_interaction_timer.title="'最适合联系人事件调度程序'"
mautic.config.tab.campaignconfig="推广活动设置"
mautic.core.config.header.campaignconfig.description="自定义营销活动行为、重试逻辑和交互优化，以提高参与度。"
mautic.core.config.header.peak_interaction_timer.description="设置默认时间范围以优化联系人交互和日程安排。"
mautic.project.campaign="推广活动"
mautic.protip.campaigns.crosssell="使用基于购买历史记录的个性化交叉销售活动来增加客户终身价值"
mautic.protip.campaigns.onboarding="创建自动化的入职流程，指导新用户使用关键产品功能并提高激活率"
mautic.protip.campaigns.reengagement="针对不再活跃的潜在客户实施重新参与活动"
mautic.protip.campaigns.survey="部署有针对性的调查活动，以收集可操作的见解并提高客户满意度"
mautic.report.campaign.completed.actions="已完成的操作"
mautic.report.campaign.event.channel="事件渠道"
mautic.report.campaign.event.channel_id="事件渠道 ID"
mautic.report.campaign.event.description="事件描述"
mautic.report.campaign.event.event_type="事件分类"
mautic.report.campaign.event.name="事件名称"
mautic.report.campaign.event.rotation="旋转"
mautic.report.campaign.event.trigger_date="事件触发日期"
mautic.report.campaign.event.trigger_mode="事件触发模式"
mautic.report.campaign.event.type="事件内容"
mautic.report.campaign.log.channel="事件日志渠道"
mautic.report.campaign.log.channel_id="事件日志渠道 ID"
mautic.report.campaign.log.date_triggered="事件日志日期触发"
mautic.report.campaign.log.is_scheduled="事件日志已调度"
mautic.report.campaign.log.non_action_path_taken="事件日志没有选择操作路径？"
mautic.report.campaign.log.system_triggered="系统触发的事件日志？"
mautic.report.campaign.log.trigger_date="事件日志触发日期"
mautic.report.campaign.no.percent="失败率"
mautic.report.campaign.pending.actions="将进行的操作"
mautic.report.campaign.yes.percent="成功率"
mautic.report.group.campaign_lead_event_log="推广活动"
mautic.report.source.campaign_lead_event_log="推广活动事件"
mautic.stage.campaign.event.change_descr="选择要为联络人设定的阶段。"
mautic.widget.events.in.time="事件及时触发"
mautic.widget.leads.added.in.time="销售线索及时添加"
