; YXHK versioned Simplified Chinese translations.
mautic.campaign.form.events.notempty="至少需要一个活动。请使用“启动市场活动构建器”按钮添加一个活动。"
mautic.campaign.form.events.orphan="一个或多个孤立事件，必须链接到节点才能继续。请连接所有孤立事件以维护有效的市场活动流。"
mautic.campaign.form.sources.notempty="至少需要一个联系人来源。请使用“启动市场活动构建器”按钮添加一个。"
mautic.campaign.import.analyze.error="%data%"
mautic.campaign.import.incorrectfile="上载的文件不是有效的市场活动导入文件。请上载格式正确的市场活动导入文件。"
mautic.campaign.import.nofile="请选择有效的活动导入文件。"
mautic.campaign.infiniteloop.immediate="活动无法在没有延迟的情况下自行重新启动。请添加至少30分钟的延迟。"
mautic.campaign.infiniteloop.interval="你的耽搁%count% 分钟。必须至少30分钟。"
mautic.campaign.share.works_with.min="至少选择一个兼容的Mautic 版本."
mautic.config.peak_interaction_timer.best_default_hour.validation.range="“结束时间必须在开始时间之后。”"
