; YXHK versioned Simplified Chinese translations.
mautic.campaign.event.clone.success="您的活动已被克隆。请在此活动或其他活动中选择一个节点以附加它。"
mautic.core.builder.code_mode_warning="切换到代码模式后，将只能以 HTML 代码的方式编辑内容。重新切换主题会导致内容丢失。"
mautic.core.builder.section_delete_warning="您确定要删除整个区段及其中的内容？"
mautic.core.builder.storage.dismiss.button="驳回"
mautic.core.builder.storage.restore.button="还原备份"
mautic.core.builder.storage.restore.message="您已将此模板的副本保存在<b>%date%</b>"
mautic.core.builder.theme_change_warning="切换主题会导致现有内容的丢失。"
mautic.core.copied="复制到剪贴板"
mautic.core.dynamicContent="动态内容"
mautic.core.dynamicContent.alt_content="内容"
mautic.core.dynamicContent.default_content="缺省内容"
mautic.core.dynamicContent.new="动态内容 %number%"
mautic.core.dynamicContent.tab="偏差 %number%"
mautic.core.dynamicContent.token_name="名"
mautic.core.error.copyfailed="无法复制到剪贴板。"
mautic.core.form.cancel="取消"
mautic.core.form.confirm="确认"
mautic.core.lookup.keep_typing="请输入 ..."
mautic.core.lookup.loading_data="正在加载数据..."
mautic.core.lookup.looking_for="查找"
mautic.core.lookup.search_options="搜索选项 ..."
mautic.core.notice.copiedtoclipboard="已复制到剪贴板！"
mautic.core.request.error="无法处理您的请求，请重试"
mautic.core.tabs.more="更多"
mautic.user.config.title.experience_and_learning.reset_confirmation="所有已解除的资源再次可见"
yxhk.ui.087adcfa71866911="浅蓝色"
yxhk.ui.0e35f6e9742e074d="基础组件"
yxhk.ui.19dd83f117525b93="黄色"
yxhk.ui.27b0da11a987cdd9="绿松石"
yxhk.ui.306ef19c8ac3d276="在新标签页中打开"
yxhk.ui.3495e757855a5c67="白色"
yxhk.ui.3b41ba9c7cb8c5d6="暂无数据"
yxhk.ui.74273989b0966e23="重做"
yxhk.ui.78e7771b8b46e11d="橙子"
yxhk.ui.7d465fb9b9314846="紫色"
yxhk.ui.7d9eb7acb13e2462="关闭"
yxhk.ui.8209d96ad8c307af="浅灰色"
yxhk.ui.9bae918add9affa5="布局区块"
yxhk.ui.a8283ade31856f71="撤销"
yxhk.ui.b561c35b4933fda4="浅绿色"
yxhk.ui.ba19e9c3d5f49882="红色"
yxhk.ui.c3b03dd28595bab2="段落"
yxhk.ui.c6cfe6e4f129a346="黑色"
yxhk.ui.d486dfbd5fb57834="绿色"
yxhk.ui.d4ac58091b024645="灰色"
yxhk.ui.eab20dd91b194f92="暗灰色"
yxhk.ui.ec7d56a01607001e="蓝色"
yxhk.ui.ef23e98791d6461e="海蓝宝石"
