; YXHK versioned Simplified Chinese translations.
mautic.core.ab_test.winner_criteria.not_blank="请选择胜出准则"
mautic.core.config.form.image.path.invalid="图像路径无效。"
mautic.core.config.form.image.path.invalid.folder.not.exists="图片路径无效。该文件夹不存在。"
mautic.core.config.form.image.path.invalid.not.media="图片路径无效。必须以 “media/” 开头。"
mautic.core.config.form.trusted_hosts.invalid.domain="信任的主机字段包含无效的网域。"
mautic.core.config.form.trusted_hosts.invalid.regexp="信任的主机字段包含无效的正则表达式。"
mautic.core.email.required="必须填写有效的邮件地址。"
mautic.core.heading.required="标题是必需的。"
mautic.core.invalid_file_encoding="文件未正确编码为UTF-8。"
mautic.core.invalid_file_type="无效的文件类型 {{ type }}。请使用与以下 mime 类型匹配的 {{ types }} 文件。"
mautic.core.message.required="必须输入信息内容。"
mautic.core.name.required="姓名为必填项。"
mautic.core.not.allowed.file.extension="%extension% 不是可允许的文件扩展名"
mautic.core.regex.invalid="regex 语法无效。"
mautic.core.remote_url_not_allowed="中的远程域URL 由于安全原因，不允许。要允许指定的域，请将其添加到位于\"配置\"->\"系统设置\"->\"其他设置\"->\"允许的远程域\"的列表中。"
mautic.core.segment.circular_dependency_exists="无法完成更新，因为当前筛选器与另一个段的筛选器冲突。确保您的段筛选器没有创建不可能或相互矛盾的条件（例如，段A必须是段B的成员，而段B必须是段A的成员）。"
mautic.core.subject.required="主题为必填项。"
mautic.core.theme.default.cannot.overwrite="%name% 是缺省的主题，因此不能被覆盖。"
mautic.core.theme.missing.files="您尝试安装的主题缺少以下所需文件，因此无法安装：%files%"
mautic.core.theme.upload.empty="请选择需要上传的 zip 文件"
mautic.core.title.required="标题为必填项。"
mautic.core.type.required="请选择类型"
mautic.core.valid_url_required="必须填写有效的 URL"
mautic.core.value.required="必须填写一个值。"
mautic.core.variant_weights_invalid="不同变体的权重之和不能超过 100%"
mautic.form.date_time_range.invalid_range="请将停止发送日期设置为开始发送日期之后。"
mautic.form.lists.count="至少需要一个列表值。"
mautic.form.lists.notblank="列表值不能为空"
