; YXHK versioned Simplified Chinese translations.
mautic.email.error.clone_with_relations_parent_only="带有翻译和变体的克隆仅适用于父电子邮件。"
mautic.email.error.list_type.sent="列表邮件发送后即无法修改。您可以考虑克隆该邮件。"
mautic.email.error.notfound="未找到序号为 %id% 的邮件！"
mautic.email.error.send.unpublished="电子邮件%name% 不可用，可用日期已过期或电子邮件类别不可用。在可用之前，您无法发送此电子邮件。"
mautic.email.notice.activated="<a href='%url%' data-toggle='ajax' data-menu-link='mautic_email_index'><strong>%name%</strong></a> 已经成为当前激活的主邮件！"
mautic.email.notice.batch_deleted="%count% 封邮件已删除！"
mautic.email.notice.cloned_with_relations="的电子邮件组<strong>%name%</strong> 已被克隆（%count% 电子邮件）。"
mautic.email.notice.schedule.cancel="电子邮件已取消预定。"
mautic.email.notice.schedule.sent="电子邮件已安排在选定日期发送。"
mautic.email.notice.test_sent.success="一封测试邮件已发送至您的邮箱。"
mautic.email.notice.test_sent_multiple.success="测试邮件已发送。"
