; YXHK versioned Simplified Chinese translations.
mautic.email.address.does.not.match.link="此电子邮件地址与用于生成此链接的电子邮件地址不匹配。"
mautic.email.api_key_required="API 密钥是必需的。"
mautic.email.chooseemail.notblank="选择要发送的电子邮件。"
mautic.email.dsn.invalid_dsn="无效的DSN。请确保输入了所有必需的字段。"
mautic.email.dsn.unsupported_scheme="不支援的配置。"
mautic.email.email_or_token.not_valid="提供的值'%value%'既不是电子邮件地址，也不是基于电子邮件字段类型构建的令牌。%details%"
mautic.email.links.invalid="该电子邮件包含无效的URL: %url%"
mautic.email.list.noaccess="未选择列表，或者您无权访问已选择的列表。"
mautic.email.multiple_emails.not_valid="提供的电子邮件无效：%email%"
mautic.email.name.length="电子邮件名称最大长度为190个字符。"
mautic.email.preheader_text.length="前标题文本最大长度为130个字符。"
mautic.email.subject.dynamic_content.text_only="动态内容插槽'%slotName%'不是' text '型别。"
mautic.email.subject.length="电子邮件主题最大长度为190个字符。"
mautic.email.subject.notblank="主题是必需的。"
mautic.email.variant.weight.notblank="输入接收此电子邮件的收件人的百分比。"
