; YXHK versioned Simplified Chinese translations.
marketplace.average.rating="评级"
marketplace.beta.warning="<strong>小心点！</strong> 这是Mautic 市场。有些事情可能还没有像预期的那样工作。<a target='_blank' href='https://docs.mautic.org/en/marketplace'>[Read更多信息]</a>"
marketplace.clear.cache="刷新插件列表"
marketplace.clear.cache.tooltip="我们保存了一些数据以加快市场加载速度。单击此处可更新此保存的数据。"
marketplace.composer.required="<strong>小心点！</strong> 安装或更新插件所需的技术设置。<a target='_blank' href='https://mau.tc/switch-to-composer'>将这些说明发送给开发人员。</a>"
marketplace.downloads="下载"
marketplace.favers="明星"
marketplace.latest.version.missing="找不到此软件包的任何版本。请稍后再试。"
marketplace.noresults.tip="您的版本没有可用的套件Mautic.请尝试升级到较新版本."
marketplace.other.packages="其他包装%name%"
marketplace.package.all.versions="所有版本"
marketplace.package.cache.clear.failed="无法刷新插件列表。请让开发人员检查服务器权限，然后重试。"
marketplace.package.cli.install="通过CLI安装"
marketplace.package.cli.install.descr="建议通过命令行界面安装插件。要安装此插件，请执行以下命令：<code>bin/console mautic：marketplace：install%vendor%/%package%</code>"
marketplace.package.create.date="已创建包"
marketplace.package.daily.downloads="每日下载"
marketplace.package.dependents="依赖包"
marketplace.package.details.close="回到市场"
marketplace.package.github.forks="叉"
marketplace.package.github.info="GitHub信息"
marketplace.package.github.open.issues="未决问题"
marketplace.package.github.stars="明星"
marketplace.package.github.watchers="观察人士"
marketplace.package.homepage="主页"
marketplace.package.install="安装"
marketplace.package.install.already.installed="此软件包已安装在系统上。"
marketplace.package.install.failed="安装程序包失败，请检查Mautic的日志以了解更多详细信息。"
marketplace.package.install.html.failed="安装时出错<strong>%packagename%</strong>。错误如下："
marketplace.package.install.html.in.progress="<strong>%packagename%</strong> 正在安装。这可能需要一些时间..."
marketplace.package.install.html.success="成功安装<strong>%packagename%</strong>!"
marketplace.package.install.html.success.continue="进入插件页面激活插件"
marketplace.package.install.html.success.view_campaigns="查看您的广告系列"
marketplace.package.issue.tracker="问题跟踪器"
marketplace.package.keywords="关键词"
marketplace.package.last_updated="最后更新"
marketplace.package.latest.stable.version="最新稳定版本"
marketplace.package.license="许可证"
marketplace.package.maintainers="维护者"
marketplace.package.monthly.downloads="每月下载量"
marketplace.package.packagist.info="Packagist信息"
marketplace.package.remove="去除"
marketplace.package.remove.failed="删除包失败，请检查Mautic的日志以了解更多详细信息。"
marketplace.package.remove.html.failed="删除时出错<strong>%packagename%</strong>。错误如下："
marketplace.package.remove.html.in.progress="<strong>%packagename%</strong> 正在删除。这可能需要一些时间..."
marketplace.package.remove.html.success="成功删除<strong>%packagename%</strong>!"
marketplace.package.remove.html.success.continue="回到市场概述"
marketplace.package.remove.not.installed="所选程序包当前未安装，因此无法删除。请使用其他程序包名称重试。"
marketplace.package.repository="存储库"
marketplace.package.request.details.missing="未提供程序包供应商或名称。请重试。"
marketplace.package.request.marketplace_disabled="市场被禁用。"
marketplace.package.request.no_permissions="您没有执行此操作的权限。"
marketplace.package.required.packages="需的包"
marketplace.package.suggesters="其他软件包建议"
marketplace.package.total.downloads="总下载量"
marketplace.package.type="类型"
marketplace.package.type.plugin="插件"
marketplace.package.type.resource="竞选"
marketplace.package.type.theme="主题"
marketplace.package.version="版本"
marketplace.package.version.release.date="发布日期"
marketplace.package.wiki="文件"
marketplace.reviews="评论"
marketplace.title="市场<sup>BETA</sup>"
marketplace.vendor="供应商"
mautic.marketplace.marketplace="市场"
mautic.marketplace.permissions.header="市场营销"
mautic.marketplace.permissions.packages="软件包-用户有权访问"
mautic.marketplace.rate.package="价格&评论"
