; YXHK versioned Simplified Chinese translations.
mautic.asset.abtest.criteria="资源数据"
mautic.asset.abtest.criteria.downloads="下载率"
mautic.asset.abtest.downloads="%count% 下载"
mautic.asset.abtest.label.downloads="下载数"
mautic.asset.abtest.label.hits="不同资源的下载数"
mautic.asset.abtest.label.sentemils="发送的邮件数"
mautic.asset.actions="资源操作"
mautic.asset.asset="资源"
mautic.asset.asset.deleted="删除的资产"
mautic.asset.asset.downloads.total="总下载量"
mautic.asset.asset.downloads.total.all_time="自此资产创建以来随时间推移的所有下载"
mautic.asset.asset.downloads.unique="唯一下载"
mautic.asset.asset.downloads.unique.all_time="与总下载量不同的是，此选项仅对每个联系人计数一次"
mautic.asset.asset.error.file.mimetype="不允许该文件类型。"
mautic.asset.asset.error.missing.remote.path="当选择远程存储时，必须指定远程的 URL 。"
mautic.asset.asset.form.confirmbatchdelete="删除存储在中的选定资产？文件Mautic 也将被永久删除。"
mautic.asset.asset.form.confirmdelete="删除资产，%name%？如果文件存储在Mautic，它也将被永久删除。"
mautic.asset.asset.form.disallow.crawlers="屏蔽索引该文件的搜索引擎"
mautic.asset.asset.form.disallow.crawlers.descr="如果您不想索引PDF，DOCX等文件，此选项将会为您屏蔽使用X-Robots-Tag HTTP header的搜索器。"
mautic.asset.asset.form.file.upload="上传文件 (允许的最大文件大小 = %max%)"
mautic.asset.asset.form.language.help="选择资源语种"
mautic.asset.asset.form.remotePath="远程 URL "
mautic.asset.asset.form.storageLocation="存储位置"
mautic.asset.asset.form.storageLocation.local="本地"
mautic.asset.asset.form.storageLocation.remote="远程"
mautic.asset.asset.help.alias="字母和数字（允许连字符）用于URL 此资产的生成。如果留空，将自动生成基于标题的唯一别名。一旦设置，将无法编辑别名。"
mautic.asset.asset.help.searchcommands="<strong>搜索命令</strong><br />id：ID 1，ID 2（逗号分隔的ID，没有空格）<br />是：我的<br />出版：Published<br />是：未发表<br />是：过期<br />是：待定<br />联系人：*<br />是：未分类<br />类别：{category alias}<br />项目：“项目名称”"
mautic.asset.asset.menu.edit="编辑资源"
mautic.asset.asset.menu.new="新建资源"
mautic.asset.asset.preview="预览"
mautic.asset.asset.searchcommand.isexpired="is:expired"
mautic.asset.asset.searchcommand.isexpired.description="筛选已过期的资产"
mautic.asset.asset.searchcommand.ispending="is:pending"
mautic.asset.asset.searchcommand.ispending.description="筛选计划在未来可用的资产"
mautic.asset.asset.searchcommand.lang="lang"
mautic.asset.asset.searchcommand.lang.description="按特定语言代码过滤资源"
mautic.asset.asset.size="文件大小"
mautic.asset.asset.submitaction.downloadfile="下载一个资源"
mautic.asset.asset.submitaction.downloadfile.msg="<br />您的下载将在五秒内开始。若未开始，请<a href='%url%'>点击这里</a>.<script>setTimeout(function(){window.location='%url%';}, 5000);</script>"
mautic.asset.asset.submitaction.downloadfile_descr="提交表单后下载所选资源。"
mautic.asset.asset.thead.download.count="下载计数"
mautic.asset.asset.url="下载 URL"
mautic.asset.assets="资源"
mautic.asset.campaign.event.assets="仅限资源"
mautic.asset.campaign.event.assets.descr="选择本触发器所适用的资源。若未选择任何项，该事件触发将适用于所有资源。"
mautic.asset.campaign.event.download="下载资源"
mautic.asset.campaign.event.download_descr="下载某个资源后触发操作。"
mautic.asset.click_to_view_full_size="查看原始大小"
mautic.asset.click_to_zoom="点击图片以放大"
mautic.asset.config.form.allowed.extensions="可接受的文件扩展名"
mautic.asset.config.form.allowed.extensions.tooltip="逗号分隔的文件扩展名列表。只有指定文件扩展名类型的文件才能上传。"
mautic.asset.config.form.max.size="最大文件大小 (MB)"
mautic.asset.config.form.max.size.tooltip="请设定资源上传时的最大文件大小，以 MB (Megabytes) 为单位。缺省值为 6MB。"
mautic.asset.config.form.upload.dir="资源目录路径"
mautic.asset.config.form.upload.dir.tooltip="设置资产应上传到的绝对路径。%kernel.project_dir%/app可用作public web根目录中app目录的占位符。建议使用public web根目录之外的目录，以防止资产被公众访问。"
mautic.asset.dashboard.widgets="资源控件"
mautic.asset.downloadcount="下载计数"
mautic.asset.drop.file.here="拖放文件至此，或点击这里以查找和选择文件。"
mautic.asset.error.file.failed="文件上传失败。"
mautic.asset.event.download="资源已下载"
mautic.asset.filename.local="本地文件名"
mautic.asset.filename.original="原始文件名"
mautic.asset.filename.remote="远程文件名"
mautic.asset.form.submit.assets="资源"
mautic.asset.form.submit.assets_descr="请选择要下载的资源。"
mautic.asset.form.submit.latest.category="请在分类中使用最新的资源"
mautic.asset.form.submit.latest.category_descr="如果资源选项“使用分类中最近的文件”被打开，那么此选项将会为您下载选中分类的最新资源。"
mautic.asset.graph.line.downloads="下载"
mautic.asset.graph.pie.statuses="下载 HTTP 状态"
mautic.asset.no_audio_support="您的浏览器不支持语音功能。"
mautic.asset.no_preview="无预览可用"
mautic.asset.no_video_support="您的浏览器不支持视频功能。"
mautic.asset.noresults.tip="资源指白皮书、PDF 文件、图像、文档、电子书或任何您希望发布给客户的电子文档。想在用户提交表单后提供某个下载资源？这很简单！在创建表单时添加“下载一个资源”操作。"
mautic.asset.onboarding.copy="使用它们来传递价值、产生销售线索，并根据受众选择下载的内容了解他们的兴趣。"
mautic.asset.onboarding.heading="分享和监控您的数字资源"
mautic.asset.onboarding.subheading="资产是您提供给联系人的可下载文件，如PDF、电子书、指南或视频。"
mautic.asset.open_preview="打开预览"
mautic.asset.permissions.assets="资源 - 用户可访问"
mautic.asset.permissions.header="资源授权"
mautic.asset.point.action.assets="仅限所选资源"
mautic.asset.point.action.assets.descr="选择本操作适用的资源。若未选择任何项，则适用于所有资源。"
mautic.asset.point.action.download="下载一个资源"
mautic.asset.point.action.download_descr="下载资源后更新联络人的积分。"
mautic.asset.preview.ariaLabel="预览%title%"
mautic.asset.preview.pdf_iframe_title="PDF预览%title%"
mautic.asset.remote.file.browse="浏览远程文件"
mautic.asset.remote.no_results="未发现远程文件。"
mautic.asset.remote.select_service="请选择左侧的服务。若未列出任何服务，请配置去存储插件。"
mautic.asset.repetitive="重复的"
mautic.asset.report.download.code="请求码"
mautic.asset.report.download.date_download="下载日期"
mautic.asset.report.download_count="下载计数"
mautic.asset.report.downloads.table="资源下载"
mautic.asset.report.unique_download_count="独立下载计数"
mautic.asset.stage.action.download="下载资源"
mautic.asset.table.most.downloaded="下载最多的资源"
mautic.asset.table.top.referrers="推荐最多者"
mautic.asset.tag.disallow.label="屏蔽索引该文件的搜索引擎"
mautic.asset.tag.language="语言：%lang%"
mautic.asset.tag.storage.local="本地存储"
mautic.asset.tag.storage.remote="远程存储"
mautic.asset.type.audio="音频"
mautic.asset.type.code="代码"
mautic.asset.type.excel="Excel"
mautic.asset.type.fallback="文件"
mautic.asset.type.image="图片"
mautic.asset.type.pdf="PDF"
mautic.asset.type.ppt="呈现"
mautic.asset.type.text="文本"
mautic.asset.type.video="视频"
mautic.asset.type.word="词"
mautic.asset.type.zip="Zip"
mautic.asset.unique="单次"
mautic.campaign.asset.download="资源已下载"
mautic.config.AssetBundle.upload_dir="上传目录"
mautic.config.tab.assetconfig="资源设置"
mautic.core.config.header.assetconfig.description="管理上传资源的文件存储、大小限制和允许的文件类型。"
mautic.project.asset="资源"
mautic.protip.assets.gating="在允许下载之前，通过一个表单来收集潜在客户信息，以保护有价值资产。"
mautic.protip.assets.naming="使用一致的命名规范来保持资源井然有序"
mautic.protip.assets.repurpose="在不同渠道和活动中重新利用高性能资产"
mautic.protip.assets.track="跟踪仪表板小部件中的资产性能指标，以识别性能最佳的内容"
mautic.report.group.assets="资源"
mautic.report.source.asset.downloads="资源下载"
mautic.report.source.assets="资源"
mautic.widget.asset.downloads.in.time="及时下载"
mautic.widget.created.assets="创建资源"
mautic.widget.popular.assets="最受欢迎的资源"
mautic.widget.unique.vs.repetitive.downloads="单次或重复下载"
