; YXHK versioned Simplified Chinese translations.
mautic.campaign.sms.reply="发送短信"
mautic.campaign.sms.reply.tooltip="联系人已发送或回复短信"
mautic.campaign.sms.send_text_sms="发送文本消息"
mautic.campaign.sms.send_text_sms.tooltip="向联系人发送文本/SMS。"
mautic.config.tab.smsconfig="短信设置"
mautic.core.config.header.smsconfig.description="为短信活动配置短信传输设置和跟踪选项。"
mautic.lead.list.filter.dnc_bounced_sms="已退回- SMS"
mautic.lead.list.filter.dnc_unsubscribed_sms="已取消订阅-短信"
mautic.lead.timeline.sms.sms.reply="收到联系人的短信"
mautic.protip.sms.compliance="通过包含退出说明来遵守法规"
mautic.protip.sms.concise="保持信息简洁和行动导向，以尊重短信的个人性质"
mautic.protip.sms.timesensitive="使用短信发送时间敏感的信息，如约会提醒或限时优惠"
mautic.sms.campaign.failed.missing_entity="指定的SMS实体不存在。"
mautic.sms.campaign.failed.missing_number="缺少联系人的电话号码。"
mautic.sms.campaign.failed.not_contactable="联系人无法通过SMS渠道联系。"
mautic.sms.campaign.failed.unpublished="已取消发布指定的SMS。"
mautic.sms.campaign.send_sms="发送推送短信"
mautic.sms.campaign.send_sms.tooltip="向用户发送推送短信。"
mautic.sms.choose.smses="选择要发送给用户的SMS。"
mautic.sms.choose.smss="选择要发送的文本消息。"
mautic.sms.config.choose_transport="选择传输"
mautic.sms.config.form.sms.disable_trackable_urls="禁用点击跟踪"
mautic.sms.config.form.sms.disable_trackable_urls.tooltip="此选项将禁用文本消息中URL的点击跟踪。"
mautic.sms.config.form.sms.enabled="是否启用文本消息？"
mautic.sms.config.form.sms.enabled.tooltip="在您的广告系列中启用文本消息支持？"
mautic.sms.config.form.sms.messaging_service_sid="消息服务SID"
mautic.sms.config.form.sms.messaging_service_sid.tooltip="提供商提供的消息服务SID，您可以使用它发送和接收文本消息。"
mautic.sms.config.form.sms.password="授权令牌"
mautic.sms.config.form.sms.password.tooltip="Twilio 授权令牌"
mautic.sms.config.form.sms.username="帐户SID"
mautic.sms.config.form.sms.username.tooltip="Twilio 帐户SID"
mautic.sms.config.no_transport="未启用传输"
mautic.sms.config.select_default_transport="选择要使用的默认传输"
mautic.sms.config.smsconfig="请先安装消息传输。"
mautic.sms.contentblock.copy="理想的时间敏感的警报，快速确认，和简洁的促销，短信营销提供高打开率。"
mautic.sms.contentblock.heading="通过即时消息联系联系人"
mautic.sms.contentblock.subheading="通过SMS向联系人的移动的号码发送直接、高影响力的通信。"
mautic.sms.create.in.campaign.builder="似乎没有！尝试更改筛选器（如果适用）或在Campaign Builder中创建新筛选器。"
mautic.sms.disabled="文本消息当前已禁用"
mautic.sms.enable.in.configuration="启用和配置文本消息Mautic 配置."
mautic.sms.form.action.sendsms.admin="发送短信给用户"
mautic.sms.form.action.sendsms.admin.descr="发送选定的短信给选定的用户（S）提交表格。"
mautic.sms.form.action.sendsms.lead="发送短信联系"
mautic.sms.form.action.sendsms.lead.descr="发送选定的短信联系表单提交后。"
mautic.sms.form.body="身体"
mautic.sms.form.confirmbatchdelete="是否删除选定的文本消息？"
mautic.sms.form.confirmdelete="删除短信，%name%?"
mautic.sms.form.confirmsend="排队，%name%，用于发送？"
mautic.sms.form.heading="标题"
mautic.sms.form.internal.description="描述"
mautic.sms.form.internal.name="内部名称"
mautic.sms.form.is_mms="是彩信"
mautic.sms.form.list="联系人列表"
mautic.sms.form.media="媒体"
mautic.sms.form.message="短信"
mautic.sms.form.mms="MMS"
mautic.sms.form.mms.media.infobox="发送媒体目前仅适用于美国和加拿大的电话号码。<br />支持的媒体类型包括.gif、.png和.jpg/. jpg。<br />一条彩信中最多可包含10幅图像.<br />邮件媒体的总大小限制为5 MB。<br />Campaign Studio不验证外部链接。用户必须确保外部链接上的媒体URL 包括. gif、. png或. jpg/. jpeg扩展名，并且图像总大小在5 MB以下。"
mautic.sms.form.nbcharacter.counter="字符数："
mautic.sms.form.nbcharacter.infobox="一条短信是由160个字符组成的。大多数时候，如果你超过这个字符数，你的短信路由器会向你收取2条或更多的短信。"
mautic.sms.form.url="链路"
mautic.sms.form.url.tooltip="当用户单击SMS时发送到的目的地。"
mautic.sms.header.edit="编辑短信-%name%"
mautic.sms.header.new="新文本消息"
mautic.sms.headings="文本消息标题"
mautic.sms.headings.tooltip="您的短信标题"
mautic.sms.icon_tooltip.has_media="有媒体"
mautic.sms.icon_tooltip.list_sms="是分段（广播）短信"
mautic.sms.link="链路"
mautic.sms.link.placeholder="网址：//"
mautic.sms.link.tooltip="当用户点击短信时，你想把它们发送到哪里？"
mautic.sms.list.frequency.number="不要发送短信超过"
mautic.sms.no.smses.note="请创建新的文本消息以供选择。"
mautic.sms.permissions.header="手机短信"
mautic.sms.permissions.smses="文本消息-用户有权访问"
mautic.sms.placeholder="留言内容在此..."
mautic.sms.preview="预览"
mautic.sms.preview.demo.message="明白了！谢谢你通知我。"
mautic.sms.preview.input.placeholder="消息"
mautic.sms.reply_pattern="回复应匹配的模式"
mautic.sms.reply_pattern.tooltip="键入答复必须匹配的模式，以便确认此决定。保留为空将匹配任何邮件。可以使用星号 * 进行通配符字符串匹配，或使用？表示单个字符。若要匹配星号或问号本身，请将其括在类似[？]的条形中。"
mautic.sms.send.edit.sms="编辑短信"
mautic.sms.send.new.sms="新文本消息"
mautic.sms.send.preview.sms="预览文字消息"
mautic.sms.send.selectsmses="选择文本消息"
mautic.sms.send.selectsmss="选择消息"
mautic.sms.show.failed="失败"
mautic.sms.show.total.sent="总发送"
mautic.sms.sms="短信"
mautic.sms.smses="短信"
mautic.sms.smses.header="短信"
mautic.sms.smses.header.preview="预览文字消息"
mautic.sms.stat.leadcount="%count% 未决"
mautic.sms.stat.readcount="%count% 读"
mautic.sms.stat.sentcount="%count% 发送"
mautic.sms.stat.sentcount.label="发送"
mautic.sms.stats="短信统计"
mautic.sms.stats.report.table="短信发送"
mautic.sms.text="短信内容"
mautic.sms.text.tooltip="您的短信内容"
mautic.sms.timeline.content.heading="消息内容"
mautic.sms.timeline.event.custom_sms="自定义文本消息"
mautic.sms.timeline.event.failed="发送短信失败"
mautic.sms.timeline.event.list="已向此联系人发送短信，因为他们属于\"%list%'段。"
mautic.sms.timeline.reply="短信收到"
mautic.sms.timeline.status="地位"
mautic.sms.timeline.status.delivered="发送的文本消息"
mautic.sms.timeline.status.failed="短信失败"
mautic.sms.timeline.status.scheduled="短信预定"
mautic.sms.timeline.status.sent="发来的短信"
mautic.sms.timeline.type="类型"
mautic.sms.token.dropdown.hint="提示：在文本消息区域中，输入{显示一个令牌。"
mautic.sms.transport.twilio.not_configured="Twilio 未配置。"
mautic.sms.twilio.transport="Twilio"
mautic.sms.type.header="您要创建哪种类型的SMS？"
mautic.sms.type.list="分段文本消息"
mautic.sms.type.list.description="可以手动向选定的联系人细分市场发送细分市场短信。短信一旦发送，就无法编辑。但是，当新联系人添加到关联的细分市场时，可以将其发送给新联系人。"
mautic.sms.type.list.differences.1st="用于营销信息、警报、更新等。"
mautic.sms.type.list.differences.2nd="允许手动发送到选定的网段"
mautic.sms.type.list.differences.3rd="专为营销/广播用途而设计"
mautic.sms.type.list.differences.4th="用于定向群发短信"
mautic.sms.type.list.differences.5th="发送后不可编辑"
mautic.sms.type.list.header="分段文本消息"
mautic.sms.type.list.tag="独立发送"
mautic.sms.type.template="触发短信"
mautic.sms.type.template.description="触发的短信息由活动、表单、点事件等自动发送。这些内容可以编辑，但不能发送到联系人列表。"
mautic.sms.type.template.differences.1st="用于活动、表单、点事件等。"
mautic.sms.type.template.differences.2nd="允许多次发送（基于触发器）"
mautic.sms.type.template.differences.3rd="适合事务/通知使用"
mautic.sms.type.template.differences.4th="基于用户的特定操作或事件"
mautic.sms.type.template.differences.5th="模板可编辑"
mautic.sms.type.template.header="触发短信"
mautic.sms.type.template.tag="需要触发器"
mautic.sms.type_media_url="在此键入媒体URL。"
mautic.sms.webhook.event.send="文本发送事件"
