; YXHK versioned Simplified Chinese translations.
mautic.sms.choosesms.notblank="请选择一条短信"
mautic.sms.form.max.media.error="最大值{{ limit }}媒体可附加1条彩信"
mautic.sms.form.max.size.media.error="所有附加的媒体文件的大小不能超过5MB，请删除一些媒体文件，并确保总大小在5MB以下。"
