; YXHK versioned Simplified Chinese translations.
mautic.tagmanager.tag.already.exists="<a href='%url%' data-toggle='ajax' data-menu-link='%menu_link%'><strong>%name%</strong></a> 已存在！"
mautic.tagmanager.tag.error.cannotbedeleted="只有不存在联系人的标签能被删除。"
mautic.tagmanager.tag.error.notfound="ID为%id%的标签没有被找到"
mautic.tagmanager.tag.notice.batch_deleted="成功删除了%count%个标签！"
mautic.tagmanager.tag.notice.merge_success="标记'%secondary%'已成功合并到'%primary%'"
