; YXHK versioned Simplified Chinese translations.
mautic.protip.tags.creation="您可以在编辑联系人时创建新标记。"
mautic.protip.tags.multivalue="对多值联系人属性使用标记而不是自定义字段"
mautic.protip.tags.segmentation="标签可用于快速分段，而自定义字段更适合长期数据存储。"
mautic.tagManager.permissions.header="标记管理员权限"
mautic.tagManager.permissions.tagManager="标签管理"
mautic.tagmanager.batch.tags="更改标记"
mautic.tagmanager.contentblock.copy="使用关键字或便利贴等标签来标记兴趣（\"product-A-interest\"）、跟踪操作（\"attended-webinar-X\"）、记录偏好（\"prefers-video\"）或管理临时状态。"
mautic.tagmanager.contentblock.heading="按您的方式整理联系人"
mautic.tagmanager.contentblock.subheading="标记提供了一种灵活的方式来标记您的联系人超出标准字段或段，提供了一种通用的方法来进行微分段。"
mautic.tagmanager.form.confirmdelete="是否删除此标记？"
mautic.tagmanager.lead.searchcommand.list="tag"
mautic.tagmanager.menu.edit="编辑标签：%name%"
mautic.tagmanager.menu.new="创建新标记"
mautic.tagmanager.tag.error.notfound="没有ID为的标记%id% 已找到！"
mautic.tagmanager.tag.form.confirmdelete="是否删除此标记？"
mautic.tagmanager.tag.header.index="标签"
mautic.tagmanager.tag.header.merge="正在合并当前标记"
mautic.tagmanager.tag.no_usages="此标记未被其他组件使用。"
mautic.tagmanager.tag.summary="总结"
mautic.tagmanager.tag.usages="标签用法"
mautic.tagmanager.to.merge.into="选择要合并到的标记"
tagmanager.menu.index="标签"
