; YXHK versioned Simplified Chinese translations.
mautic.config.tab.messengerconfig="队列设置"
mautic.core.config.header.messenger.email.description="配置电子邮件、短信和推送通知的消息队列设置。"
mautic.core.config.header.messenger.failed.description="为超过重试次数的失败邮件设置存储。"
mautic.core.config.header.messenger.hit.description="管理页面浏览量和电子邮件跟踪数据的排队设置。"
mautic.core.config.header.messenger.retry.description="定义在队列系统中如何处理和重试失败的消息。"
mautic.messenger.config.dsn.send_test_message="发送测试消息"
mautic.messenger.config.dsn.test_message_failed="由于以下错误，无法发送测试消息：“”%message%\"'."
mautic.messenger.config.dsn.test_message_processed="DSN“”的测试邮件%type%“”已成功处理。"
mautic.messenger.config.dsn_email="电子邮件队列（SMS和推送消息）"
mautic.messenger.config.dsn_failed="故障队列"
mautic.messenger.config.dsn_help_failed="如果消息的所有重试都失败，则默认情况下将丢弃该消息。为了避免这种情况发生，您可以选择配置失败队列。有关详细信息，请参阅<a href=\"%link%\">%link%</a>."
mautic.messenger.config.dsn_help_general="默认情况下不启用队列管理（方案设置为“同步”）。如果您想开始使用队列，请按照<a href=\"%link%\">%link%</a>."
mautic.messenger.config.dsn_help_retry_strategy="当消息的处理失败时，消息将被发送回队列进行再次尝试。您可以在下面的部分中调整此行为。请参阅<a href=\"%link%\">%link%</a> 的双曲余弦值。"
mautic.messenger.config.dsn_hit="命中队列（页面和电子邮件）"
mautic.messenger.config.retry_strategy="重试策略"
mautic.messenger.config.retry_strategy.delay="延迟"
mautic.messenger.config.retry_strategy.max_delay="最大延迟"
mautic.messenger.config.retry_strategy.max_retries="最大重试"
mautic.messenger.config.retry_strategy.multiplier="乘法器"
