; YXHK versioned Simplified Chinese translations.
mautic.messenger.dsn.invalid_dsn="无效的DSN。请确保输入了所有必填字段。通常，字段“scheme”和“host”是必填字段。"
mautic.messenger.dsn.unsupported_scheme="不支持的方案。请确保输入的方案与支持的方案之一匹配。您可能需要先安装支持该方案的程序包。有关详细信息，请参阅https://symfony.com/doc/5.4/messenger.html#transport-configuration"
