; YXHK versioned Simplified Chinese translations.
mautic.campaign.dwc.decision="请求动态内容"
mautic.campaign.dwc.push_content="推送动态内容"
mautic.core.icon_tooltip.is_filter_based="基于过滤器的动态页面内容"
mautic.dwc.delete_new="丢弃新的动态内容"
mautic.dwc.form.confirmbatchdelete="确认批量删除"
mautic.dwc.form.is.campaign="活动动态内容"
mautic.dwc.form.is.campaign.tooltip="是活动动态内容"
mautic.dwc.form.is.standalone="独立动态内容"
mautic.dwc.form.is_campaign_based="是否基于推广活动？"
mautic.dwc.form.is_campaign_based.tooltip="请选择基于市场活动条件或过滤器，对页面内容进行展示的位置"
mautic.dynamic.content.triggered="动态内容触发"
mautic.dynamic.content.type.html="HTML"
mautic.dynamic.content.type.text="文本"
mautic.dynamicContent.campaign.decision_dwc="请求动态内容"
mautic.dynamicContent.campaign.decision_dwc.tooltip="这是动态内容请求的最高级别"
mautic.dynamicContent.campaign.event.dynamicContenthit="访问一个着陆页"
mautic.dynamicContent.campaign.event.dynamicContenthit_descr="页面/url 点击后触发操作。"
mautic.dynamicContent.campaign.event.form.dynamicContents="仅限页面"
mautic.dynamicContent.campaign.event.form.dynamicContents.descr="选择本触发器适用的着陆页。若未选择任何项，则适用于所有着陆页。"
mautic.dynamicContent.campaign.event.form.url="URL"
mautic.dynamicContent.campaign.event.form.url.descr="请插入已植入跟踪图像的页面URL。可使用通配符 (*)。例如：*product/123* 可匹配 http://web.com/product/1234.htm. 多个 URL 间用逗号分隔。"
mautic.dynamicContent.campaign.send_dwc="推送动态内容"
mautic.dynamicContent.campaign.send_dwc.tooltip="在动态内容被请求时要触发的动作。"
mautic.dynamicContent.choose.dynamicContents="选择要显示的缺省动态内容。"
mautic.dynamicContent.config.form.cat.in.url="在页面 URL 中显示类别？"
mautic.dynamicContent.config.form.cat.in.url.tooltip="启用后，类别标志会被包括在 URL中。"
mautic.dynamicContent.config.form.google.analytics="分析脚本  (如： Google Analytics)"
mautic.dynamicContent.config.form.google.analytics.tooltip="插入分析脚本，让其自动包含在着陆页的源代码中。"
mautic.dynamicContent.dynamicContent="动态Web内容"
mautic.dynamicContent.dynamicContents="动态Web内容"
mautic.dynamicContent.error.notfound="动态内容项 %id% 未找到。"
mautic.dynamicContent.event.hit="页面点击"
mautic.dynamicContent.event.publish.down="设置%dwc% 为不可用"
mautic.dynamicContent.event.publish.down.description="动态内容'%dwc%'将无法使用。"
mautic.dynamicContent.event.publish.up="设置%dwc% 为不可用"
mautic.dynamicContent.event.publish.up.description="佩奇%dwc%'将可供使用。"
mautic.dynamicContent.form.confirmbatchdelete="删除所选的项目？警告 - 这将同时删除与该项目相关的所有翻译。"
mautic.dynamicContent.form.confirmdelete="删除动态内容项目， %name%? 警告 - 这将同时删除相关的翻译!"
mautic.dynamicContent.form.content="内容"
mautic.dynamicContent.form.content.help="在该变量或缺省项目被请求时，要返回的内容。"
mautic.dynamicContent.form.internal.name="内部名称"
mautic.dynamicContent.form.language.help="通过设定一个父页面，将内容翻译成不同语言，并将其链接到一起。语言选项将在相关的着陆页中可用，以便用户选择他们希望的语言。"
mautic.dynamicContent.header.edit="编辑动态内容 - %name%"
mautic.dynamicContent.header.is_filter_based="是为区块建立的，基于过滤器的动态页面内容： %slot%"
mautic.dynamicContent.header.new="新建动态内容"
mautic.dynamicContent.label.slot_name="区块名称"
mautic.dynamicContent.menu.edit="编辑页面"
mautic.dynamicContent.menu.view="查看页面"
mautic.dynamicContent.notice.batch_deleted="%count% 动态内容项被删除。"
mautic.dynamicContent.publish.down="设置为不可用"
mautic.dynamicContent.publish.up="设置为可用"
mautic.dynamicContent.report.revision="修改"
mautic.dynamicContent.send.edit.dynamicContent="编辑动态内容"
mautic.dynamicContent.send.new.dynamicContent="新建动态内容"
mautic.dynamicContent.send.selectDynamicContents="选择动态内容"
mautic.dynamicContent.send.selectDynamicContents.default="选择缺省内容"
mautic.dynamicContent.send.slot_name="请求的区块名称"
mautic.dynamicContent.send.slot_name.tooltip="联络人正在请求的区块名。"
mautic.dynamicContent.show.total.views="总阅读量"
mautic.dynamicContent.show.unique.views="独立阅读量"
mautic.dynamicContent.slot.campaign="是基于推广活动"
mautic.dynamicContent.timeline.content="内容"
mautic.dynamicContent.timeline.title="阅读动态内容"
mautic.dynamicContent.token.slot="动态页面内容区块"
mautic.dynamicContent.type.label="类型"
mautic.dynamicContent.views="阅读量"
mautic.dynamiccontent.generator.copy_dynamic_content_slot="复制动态内容槽"
mautic.dynamiccontent.generator.default_content_tooltip="添加您自己的默认内容，以确保在过滤器不匹配时显示该内容-例如，新的匿名访问者或与您指定的条件不匹配的联系人。"
mautic.dynamiccontent.generator.deployment_instructions="将插件代码复制并粘贴到您的CMS编辑器中，或者添加HTML 代码片段直接复制到您网站代码中。"
mautic.dynamiccontent.generator.deployment_options="选择如何集成动态内容"
mautic.dynamiccontent.generator.html="HTML"
mautic.dynamiccontent.generator.html_description="适用于任何网站使用我们的跟踪脚本。"
mautic.dynamiccontent.generator.html_tag_info="使用div表示块级别的内容，这些内容应该从新行开始，或者使用span表示在文本中流动的内联内容。这两个标签都支持相同的动态内容功能。"
mautic.dynamiccontent.generator.html_tag_title="选择正确的HTML 标签"
mautic.dynamiccontent.generator.input_placeholder="在此起草您的默认内容"
mautic.dynamiccontent.generator.joomla_syntax_info="Joomla使用花括号{mautic}得双曲余切值.WordPress 使用方括号[mautic]。请根据您的CMS插件选择适当的语法。"
mautic.dynamiccontent.generator.more_information.html="信息HTML标签"
mautic.dynamiccontent.generator.more_information.plugins="有关代码包装的信息"
mautic.dynamiccontent.generator.plugins="插件"
mautic.dynamiccontent.generator.plugins_description="与流行的CMS社区插件兼容。"
mautic.dynamiccontent.generator.preview_content_discard_notice="关闭此窗口时，在输入字段中输入的任何文本都将丢失。"
mautic.dynamiccontent.generator.switch_code_wrapper="开关代码包装器"
mautic.dynamiccontent.generator.switch_html_tag="开关HTML 标签"
mautic.dynamiccontent.generator.troubleshooting.cache="缓存相关问题"
mautic.dynamiccontent.generator.troubleshooting.cache_text="如果使用Cloudflare等服务，请尝试在测试期间禁用缓存，清除浏览器缓存并清除CDN缓存。"
mautic.dynamiccontent.generator.troubleshooting.content_not_displaying="内容未显示"
mautic.dynamiccontent.generator.troubleshooting.content_not_displaying_text="尝试使用匿名会话或隐身窗口进行测试。Mautic 会忽略管理员活动。"
mautic.dynamiccontent.generator.troubleshooting.default_content="包括默认内容"
mautic.dynamiccontent.generator.troubleshooting.default_content_text="确保访问者总是看到有意义的东西。这对于匿名访问者或联系人不符合您指定的标准时至关重要。"
mautic.dynamiccontent.generator.troubleshooting.javascript="JavaScript限制"
mautic.dynamiccontent.generator.troubleshooting.javascript_text="Mautic 为了安全性而清除DWC，请在内容中使用具有技术属性的元素，这些元素可以被外部脚本作为目标。"
mautic.dynamiccontent.generator.troubleshooting.title=" 问题排查"
mautic.dynamiccontent.generator.when_to_change_brackets="不同的CMS插件使用不同的语法"
mautic.dynamiccontent.permissions.dynamiccontents="动态内容 - 用户有以下权限"
mautic.dynamiccontent.permissions.header="动态内容授权"
mautic.placeholder_tokens.dynamic_content.example="【动态内容一】| 例如，用户定义变量名"
mautic.placeholder_tokens.dynamic_content_tokens="动态内容"
