; YXHK versioned Simplified Chinese translations.
mautic.dynamicContent.filter.options.empty="至少需要一个筛选器。"
mautic.dynamicContent.name.notblank="请输入姓名。"
mautic.dynamicContent.no_nesting="DWC标记不能在另一个DWC中使用。请从内容中删除任何DWC标记以继续。"
mautic.dynamicContent.slot_name.notblank="请输入插槽名称。"
mautic.dynamicContent.slot_name_type="具有相同插槽名称的所有动态内容必须为相同类型。"
