; YXHK versioned Simplified Chinese translations.
mautic.integration.app.authorize="授权App"
mautic.integration.app.reauthorize="重新授权App"
mautic.integration.enabled="是否已启用？"
mautic.integration.feature.push_activity="将Mautic的活动推入此集成"
mautic.integration.feature.push_activity.included_events="推送活动时要包含的事件"
mautic.integration.feature.push_activity.included_events.tooltip="选择将作为活动发送到集成的Mautic事件。"
mautic.integration.feature.sync="在Mautic和此集成中同步物体"
mautic.integration.features="应该启用此集成的哪些功能？"
mautic.integration.integration="集成"
mautic.integration.last_sync_date="上次同步日期"
mautic.integration.message="信息"
mautic.integration.not_configured="集成被配置了"
mautic.integration.oauth1a.consumer.key="使用者密钥"
mautic.integration.oauth1a.consumer.secret="消费者秘密"
mautic.integration.oauth1a.token="令牌"
mautic.integration.oauth1a.token.secret="令牌密钥"
mautic.integration.object="对象"
mautic.integration.object_id="物体ID"
mautic.integration.sync.channel_dnc="不要联系 - %channel%"
mautic.integration.sync.contact_timeline="联系时间线URL"
mautic.integration.sync.event="%integration%：%message%"
mautic.integration.sync.timeline_notices="集成同步通知"
mautic.integration.sync.update_blanks="非空值是否应该用另一个系统的空格覆盖？"
mautic.integration.sync.user_notification.contact="以下联系人无法同步。查看他们的时间表了解更多细节。%contacts%"
mautic.integration.sync.user_notification.count_message="%count% 个物体同步失败。考虑验证集成的配置。"
mautic.integration.sync.user_notification.header="当同步物体%object%到集成 %integration%时遇到了问题"
mautic.integration.sync.user_notification.sync_error="%name% 同步失败，失败原因：&quot;%message%&quot；"
mautic.integration.sync_direction_bidirectional="同步两种方式"
mautic.integration.sync_direction_integration="只同步到此集成"
mautic.integration.sync_direction_mautic="只同步到Mautic"
mautic.integration.sync_field_mapping="%object%字段映射"
mautic.integration.sync_filter_fields="过滤集成字段..."
mautic.integration.sync_mautic_field="选择一个Mautic字段"
mautic.integration.sync_objects="选择要同步到Mautic的物体"
