; YXHK versioned Simplified Chinese translations.
mautic.campaign.campaign.sendwebhook="发送 Webhook"
mautic.config.tab.webhookconfig="Webhook 设置"
mautic.core.config.header.webhookconfig.description="为webhook配置事件处理和交付选项。"
mautic.webhook.card.copy="事件驱动的webhooks允许您更新第三方应用程序的联系人和活动，因为他们发生，使用API 可以监听网钩的机器人。"
mautic.webhook.card.heading="将数据从您的帐户发送到其他系统或数据库"
mautic.webhook.card.image.alt="一个象征网络钩子的概念图像，其特征是相互连接的蓝色和紫色晶体结构，表示在应用程序之间自动发送的数据包。"
mautic.webhook.card.interesting="你可能会发现"
mautic.webhook.config.allowed_private_addresses="允许的私有地址（每行一个）"
mautic.webhook.config.allowed_private_addresses.tooltip="指定允许Webhook使用的私有IP或域列表。这允许Webhook安全地与内部服务交互。"
mautic.webhook.config.cron_process="仅查询事件 - 通过 CLI Command 处理"
mautic.webhook.config.email.details="发送电子邮件详细信息"
mautic.webhook.config.email.details.tooltip="如果启用，电子邮件相关的webhooks发送详细数据。"
mautic.webhook.config.event.orderby="队列事件的次序"
mautic.webhook.config.event.orderby.chronological="时序"
mautic.webhook.config.event.orderby.reverse.chronological="时序倒置"
mautic.webhook.config.event.orderby.tooltip="如果使用队列，一个webhook请求可以包含多个事件。默认值在设置中定义。"
mautic.webhook.config.form.queue.mode="队列模式"
mautic.webhook.config.form.queue.mode.tooltip="请选择如何处理 webhook 事件。立即处理会执行 webhook 事件。队列模式会添加事件到队列中，以便在以后通过 cron 命令来执行。"
mautic.webhook.config.immediate_process="立即处理"
mautic.webhook.contentblock.copy="创建联系人、提交表单、打开电子邮件或触发其他事件时，Mautic 立即将相关数据推送到URL 实现无缝的、事件驱动的集成。"
mautic.webhook.contentblock.heading="触发外部操作Mautic 事件"
mautic.webhook.contentblock.subheading="当特定事件发生时，Webhook会将实时数据发送到其他应用程序，作为外部系统的即时通知。"
mautic.webhook.error.notfound="Webhook 未找到"
mautic.webhook.error.private_address="的URL 您提供的webhook位于私有IP 地址范围，默认情况下不允许。请提供URL 指向可公开访问的服务器，或者如果需要使用专用IP."
mautic.webhook.event.sendwebhook="发送 Webhook"
mautic.webhook.event.sendwebhook.data="数据"
mautic.webhook.event.sendwebhook.headers="文件头"
mautic.webhook.event.sendwebhook.method="方法"
mautic.webhook.event.sendwebhook.timeout="超时"
mautic.webhook.event.sendwebhook.url="URL"
mautic.webhook.event.sendwebhook_desc="发送一个 webhook ( 仅限有经验的用户 )"
mautic.webhook.failing="Webhook%webhook% 正在失败"
mautic.webhook.failing.details="%webhook% 失败的原因是%reason%"
mautic.webhook.form.confirmbatchdelete="删除所选的 Webhooks？"
mautic.webhook.form.confirmdelete="删除 Webhook，%name%？"
mautic.webhook.form.description="Webhook 描述"
mautic.webhook.form.secret="隐秘性"
mautic.webhook.form.webhook.events="Webhook 事件"
mautic.webhook.form.webhook_url="Webhook 请求地址（POST）"
mautic.webhook.killed="由于响应出错，Webhook已自动停用%limit% 次。"
mautic.webhook.label.no.events="未选择事件"
mautic.webhook.label.no.url="未指定 URL "
mautic.webhook.label.success="成功！"
mautic.webhook.label.warning="发现错误！"
mautic.webhook.no.logs="无 Webhooks 日志"
mautic.webhook.no.logs_desc="该 webhook 尚未执行，因此没有任何可用的日志"
mautic.webhook.note="备注"
mautic.webhook.permissions.header="Webhook 授权"
mautic.webhook.permissions.webhooks="Webhook - 用户有权访问"
mautic.webhook.runtime="请求运行时"
mautic.webhook.secret.tooltip="如果未提供任何值，则会自动产生此字段。请使用此秘密杂凑来验证目的服务器上webhook负载的真实性。"
mautic.webhook.send.test.payload="发送测试载荷"
mautic.webhook.status="响应"
mautic.webhook.stopped="Webhook 已停止"
mautic.webhook.stopped.details="%webhook% 由于 %reason% 的原因被终止"
mautic.webhook.stopped.reason="一段时间内的响应不成功"
mautic.webhook.stopped.reason.410="响应的 HTTP 代码是 410，意味着接受方不希望收到更多的请求。"
mautic.webhook.webhook.header.edit="编辑 Webhook"
mautic.webhook.webhook.header.new="创建新的 Webhook"
mautic.webhook.webhook.logs.desc="以下是本接口的日志。每当事件触发该接口时，我们会记录 HTTP 响应的 header。成功的响应会返回 200 header。其它响应将被视为错误。"
mautic.webhook.webhook.logs.empty.response="收到空响应正文"
mautic.webhook.webhook.logs.title="Webhook 响应日志"
mautic.webhook.webhook.menu.index="Webhook 回调"
mautic.webhook.webhook_url="Webhook 地址"
mautic.webhook.webhooks="Webhook 回调"
