; YXHK versioned Simplified Chinese translations.
mautic.project.already.exists="<a href='%url%' data-toggle='ajax' data-menu-link='%menu_link%'><strong>%name%</strong></a> 已存在！"
mautic.project.error.cannotbedeleted="只能删除没有任何联系人的项目。"
mautic.project.error.invalid_entity_type="无效的实体类型'%type%'"
mautic.project.error.notfound="没有ID为%id% 已找到！"
mautic.project.notice.batch_deleted="成功删除%count% 项目!"
mautic.project.notice.entities_added="%count% 个项目已添加到项目'%project%'"
mautic.project.notice.item_removed="'%name%'已从项目中移除'%project%'"
mautic.project.notice.no_entities_added="未向项目中添加新项"
