; YXHK versioned Simplified Chinese translations.
mautic.campaign.focus.show="聚集项"
mautic.focums.html_mode.tooltip="请选择模式。在不同模式间切换时，会丢失原有的内容。"
mautic.focus="聚焦项"
mautic.focus.builder="焦点生成器"
mautic.focus.campaign.event.show_focus="显示聚集项目"
mautic.focus.campaign.event.show_focus_descr="激活聚集项目"
mautic.focus.click="焦点点击"
mautic.focus.details.unique_views="独到的见解"
mautic.focus.details.unique_views.tooltip="已查看焦点项目的独立访问者数。"
mautic.focus.details.views="阅读量"
mautic.focus.details.views.tooltip="焦点项目已显示的次数。"
mautic.focus.edit="编辑 %name%"
mautic.focus.event.click="焦点点击"
mautic.focus.event.view="聚焦视图"
mautic.focus.fetch_snapshot="获取"
mautic.focus.focus_item="聚集项"
mautic.focus.focus_items="聚焦项"
mautic.focus.focusitem.selectitem="选择聚集项目"
mautic.focus.focusitem.selectitem_descr="选择聚集项"
mautic.focus.form.activate_for_links="点击链接时激活"
mautic.focus.form.animate="动画 ?"
mautic.focus.form.bar.allow_hide="允许隐藏？"
mautic.focus.form.bar.push_page="将页面下移？"
mautic.focus.form.bar.push_page.tooltip="若设置为否，则工具条会覆盖页面内容。"
mautic.focus.form.bar.size="大小"
mautic.focus.form.bar.size.large="大; 50px 高，字体为 17pt "
mautic.focus.form.bar.size.regular="正常; 30px 高，字体 14pt "
mautic.focus.form.bar.sticky="启用可移动功能？"
mautic.focus.form.bar.sticky.tooltip="若选择是，则工具条在滚动时会一直显示。"
mautic.focus.form.basic="基本"
mautic.focus.form.button_color="按钮颜色"
mautic.focus.form.button_text_color="按钮文字颜色"
mautic.focus.form.choose_form="选择要插入的表单"
mautic.focus.form.confirmbatchdelete="删除所选的聚焦项？"
mautic.focus.form.confirmdelete="删除名称为%name%的焦点项目？"
mautic.focus.form.custom.css="自定义CSS"
mautic.focus.form.custom.css.help="输入您的自定义样式，<&#8239;style&#8239;>标签"
mautic.focus.form.editor="编辑器"
mautic.focus.form.engage_after_conversion="沟通后停止联络？"
mautic.focus.form.engage_after_conversion.tooltip="若设置为是，则在访问者提交表单或点击链接时，聚集将不再显示，直到用户清除其 cookies。 "
mautic.focus.form.font="字体"
mautic.focus.form.frequency="多久联络一次？"
mautic.focus.form.frequency.daily="每天一次"
mautic.focus.form.frequency.daily.description="每天显示焦点一次"
mautic.focus.form.frequency.everypage="每页"
mautic.focus.form.frequency.everypage.description="在每一页上显示焦点"
mautic.focus.form.frequency.help="当选择“每次会话一次”时，焦点项目将为每个活动浏览器会话显示一次，当访问者离开您的网站时，焦点项目将结束。"
mautic.focus.form.frequency.hourly="每小时一次"
mautic.focus.form.frequency.hourly.description="每小时显示一次焦点"
mautic.focus.form.frequency.once="每进程一次"
mautic.focus.form.frequency.once.description="每个会话显示一次焦点"
mautic.focus.form.frequency.q15m="每 15 分钟"
mautic.focus.form.frequency.q15min.description="每15分钟显示一次焦点"
mautic.focus.form.frequency.q2m="每 2 分钟"
mautic.focus.form.frequency.q2min.description="每2分钟显示一次焦点"
mautic.focus.form.headline="标题"
mautic.focus.form.html="HTML"
mautic.focus.form.html_mode="内容模式"
mautic.focus.form.html_mode.tooltip="HTML 模式下可为聚集项添加您定制的 HTML 代码。"
mautic.focus.form.link_new_window="在新窗口中打开链接？"
mautic.focus.form.link_text="链接文字"
mautic.focus.form.link_url="链接 URL"
mautic.focus.form.placement="占位"
mautic.focus.form.placement.bottom="页脚"
mautic.focus.form.placement.bottom_left="页脚左侧"
mautic.focus.form.placement.bottom_right="页脚右侧"
mautic.focus.form.placement.help="启用粘滞以将栏固定在视口的底部，或禁用粘滞以将其放置在页面的末尾。"
mautic.focus.form.placement.middle="中部"
mautic.focus.form.placement.top="页眉"
mautic.focus.form.placement.top_left="页眉左侧"
mautic.focus.form.placement.top_right="页眉右侧"
mautic.focus.form.primary_color="主要色彩"
mautic.focus.form.stop_after_close="关闭焦点后停止参与？"
mautic.focus.form.stop_after_close.tooltip="如果设置为“是”，并且访问者直接关闭焦点，则在访问者清除其Cookie之前，焦点将不会再次显示。"
mautic.focus.form.style="要使用的风格?"
mautic.focus.form.tagline="口号"
mautic.focus.form.text_color="文字色彩"
mautic.focus.form.timeout="接合前超时"
mautic.focus.form.timeout.description="接合前超时（秒）"
mautic.focus.form.timeout.seconds="秒"
mautic.focus.form.type="聚焦应该是什么？"
mautic.focus.form.type.form="收集数据"
mautic.focus.form.type.form_description="使用 Mautic 表单来收集访问者数据。"
mautic.focus.form.type.link="强调一个链接"
mautic.focus.form.type.link_description="让访问者点击某个 URL。"
mautic.focus.form.type.notice="显示通知"
mautic.focus.form.type.notice_description="显示通知给访问者"
mautic.focus.form.type.tooltip="选择要使用的聚焦类型"
mautic.focus.form.website="网站"
mautic.focus.form.website.tooltip="请输入网站地址，Mautic 会截屏并显示一个样本。"
mautic.focus.form.when="何时参与沟通？"
mautic.focus.form.when.5seconds="5 稍延迟"
mautic.focus.form.when.5seconds.description="5秒延迟后显示焦点"
mautic.focus.form.when.immediately="抵达后"
mautic.focus.form.when.immediately.description="到达后立即显示焦点"
mautic.focus.form.when.leave="访客准备离开"
mautic.focus.form.when.leave.description="当访客打算离开时显示焦点"
mautic.focus.form.when.minute="1 秒延迟"
mautic.focus.form.when.minute.description="延迟1分钟后显示焦点。"
mautic.focus.form.when.scroll_bottom="滚动至页脚后"
mautic.focus.form.when.scroll_bottom.description="滚动到底部后显示焦点。"
mautic.focus.form.when.scroll_middle="滚动到中部后"
mautic.focus.form.when.scroll_middle.description="在用户滚动到页面中间后显示焦点。"
mautic.focus.form.when.scroll_slight="略向下滚动后"
mautic.focus.form.when.scroll_slight.description="在用户稍微向下滚动页面后显示焦点。"
mautic.focus.form_token.instructions="插入 <strong>{focus_form}</strong> 到上述内容，以生成所选择的表单。"
mautic.focus.graph.clicks="点击"
mautic.focus.graph.stats="聚焦数据"
mautic.focus.graph.submissions="提交"
mautic.focus.graph.views="阅读量"
mautic.focus.header="聚集项"
mautic.focus.help.searchcommands="<strong>搜索命令</strong><br />id：ID 1，ID 2（逗号分隔的ID，没有空格）<br />出版：Published<br />是：未发表<br />是：我的<br />是：未分类<br />类别：{category alias}<br />项目：“项目名称”"
mautic.focus.install.description="将这行代码复制到您的网站中，最好是在结束正文标记之前。或者，通过活动操作显示此焦点项目，以响应具有Mautic 跟踪脚本。"
mautic.focus.install.header="聚焦安装"
mautic.focus.install.tracking.warning="此独立的焦点项目脚本记录视图和交互，与Mautic 网站跟踪。如果需要同意，请单独管理此脚本。"
mautic.focus.interaction="相互作用"
mautic.focus.new="新的聚焦"
mautic.focus.no.focusitem.note="没有可供选择的聚集项，请创建。"
mautic.focus.noresults.tip="利用聚焦表单，聚集点击或聚焦通知获得网站访客的注意。"
mautic.focus.onboarding.eyebrow="功能"
mautic.focus.onboarding.heading="吸引网站访问者"
mautic.focus.onboarding.purpose.copy="收集订阅者信息、突出显示重要链接或显示重要通知，帮助您生成联系人并指导他们的旅程。"
mautic.focus.onboarding.purpose.heading="核心目标"
mautic.focus.onboarding.style.bar.copy="在页面顶部或底部显示横幅，用于低干扰通知或简单的行动引导。"
mautic.focus.onboarding.style.bar.heading="工具栏"
mautic.focus.onboarding.style.eyebrow="风格"
mautic.focus.onboarding.style.fullpage.copy="覆盖整个屏幕，突出重要信息、访问提示或紧急行动引导。"
mautic.focus.onboarding.style.fullpage.heading="整页"
mautic.focus.onboarding.style.modal.copy="覆盖窗口，经常触发，铅捕获或特别优惠."
mautic.focus.onboarding.style.modal.heading="模式窗口"
mautic.focus.onboarding.style.notification.copy="小滑入框（角落）用于简短的消息或微妙的警报。"
mautic.focus.onboarding.style.notification.heading="通知"
mautic.focus.onboarding.styles.heading="款式"
mautic.focus.onboarding.subheading="这些引人注目的栏、弹出窗口（模态）、通知或全页显示在关键时刻吸引注意力。"
mautic.focus.permissions.header="聚焦授权"
mautic.focus.permissions.items="聚焦项目 - 用户可以访问"
mautic.focus.preview="预览"
mautic.focus.show.edit.item="编辑聚集项目"
mautic.focus.show.new.item="新建聚集项"
mautic.focus.show.preview.item="预览聚集项目"
mautic.focus.style="风格"
mautic.focus.style.bar="工具栏"
mautic.focus.style.bar_description="在网页顶部显示工具栏"
mautic.focus.style.modal="模式窗口"
mautic.focus.style.modal_description="在网页中间显示一个弹出窗口"
mautic.focus.style.notification="通知"
mautic.focus.style.notification_description="在页面的角落里显示一个小窗口。"
mautic.focus.style.page="整页"
mautic.focus.style.page_description="显示一个整幅页面大小的窗口。"
mautic.focus.tab.focus_colors="色彩"
mautic.focus.tab.focus_content="内容"
mautic.focus.tab.focus_style="风格"
mautic.focus.tab.focus_type="聚焦"
mautic.focus.thead.style="聚焦风格"
mautic.focus.thead.type="聚焦类型"
mautic.focus.type="类型"
mautic.focus.type.form="表单"
mautic.focus.type.link="链接"
mautic.focus.type.notice="通知"
mautic.focus.unsaved="未保存的焦点项目"
mautic.focus.view="聚焦视图"
mautic.focus.website_placeholder="在此输入一个网站，将会抓取一个截屏，以示范聚焦在您的网站上显示的效果。"
mautic.report.datasource.focus.leads="焦点电极导线"
mautic.report.focus.category="Focus类别"
mautic.report.focus.description="焦点描述"
mautic.report.focus.hits="点击"
mautic.report.focus.id="重点ID"
mautic.report.focus.name="焦点名称"
mautic.report.focus.ratio.click="点击比率"
mautic.report.focus.ratio.submission="提交比率"
mautic.report.focus.style="聚焦风格"
mautic.report.focus.uniquehits="唯一的点击率"
mautic.report.group.focus="聚焦项"
mautic.report.source.focus_leads="焦点电极导线"
