; YXHK versioned Simplified Chinese translations.
mautic.point.action.delta="变化点（+/-）"
mautic.point.action.delta.help="设置此操作要添加或扣除的点数。如果为正数，则添加到联系人的点数中。如果为负数，则扣除。"
mautic.point.action.empty.heading="通过操作解锁自动化销售线索评分"
mautic.point.action.empty.purpose="目的"
mautic.point.action.empty.score_contacts_desc="当联系人下载资产、访问您的定价页面、打开重要电子邮件或提交密钥表单时，自动分配积分。"
mautic.point.action.empty.score_contacts_heading="根据特定行为对联系人进行评分"
mautic.point.action.empty.subheading="停止猜测哪些潜在客户参与！专注于您的后续工作纯粹是在关闭交易."
mautic.point.action.empty.understand="理解"
mautic.point.action.empty.what_are_point_actions="什么是点操作？"
mautic.point.action.empty.what_are_point_actions_desc="这些是您创建的用于自动调整联系人得分的规则。您可以控制每个活动的点值（正或负），从而根据您的业务量身定制系统。"
mautic.point.action.noresults.tip="使用积分操作可根据定义的事件调整联系人的积分。例如，如果联系人打开活动电子邮件，则给予他/她10分。"
mautic.point.actions.header.index="点动作"
mautic.point.changes="点变化"
mautic.point.dashboard.widgets="点小部件"
mautic.point.event.gained="得分"
mautic.point.event.manual_change="手动改变"
mautic.point.form.addaction="使用右侧的列表添加操作。"
mautic.point.form.confirmbatchdelete="是否删除选定的点动作？"
mautic.point.form.confirmdelete="删除点动作，%name%?"
mautic.point.form.no_point_groups="没有可用的点群组。"
mautic.point.form.repeat="是可重复"
mautic.point.form.repeat.help="启用此操作可多次对销售线索进行评分;禁用此操作可一次性评分。"
mautic.point.form.repeat.no="仅一次性评分"
mautic.point.form.repeat.yes="允许多个分数"
mautic.point.form.score_not_set="未设置分数"
mautic.point.form.type="联系人采取的行动"
mautic.point.group.form.confirmbatchdelete="是否删除选定的点编组？这些编组中的联系得分也将被永久删除。"
mautic.point.group.form.confirmdelete="删除点编组，%name%？该组中的联系人分数也将被永久删除。"
mautic.point.group.form.group="点编组"
mautic.point.group.form.group_descr="选择要应用此选项的点编组。如果未选择编组，则此选项将应用于主要联系人点。"
mautic.point.group.form.nogroup="没有一"
mautic.point.group.header.index="点编组"
mautic.point.group.menu.edit="编辑组"
mautic.point.group.menu.index="管理组"
mautic.point.group.menu.new="新组"
mautic.point.group.onboarding.copy="跟踪与特定产品线，内容主题或漏斗阶段的参与度的单独分数。这可以让您更全面地了解联系人感兴趣的内容，而不仅仅是他们的整体参与度。"
mautic.point.group.onboarding.heading="通过精细的潜在客户评分获得更深入的洞察力"
mautic.point.group.onboarding.subheading="超越单一的参与度评分。群组允许您根据不同类型的互动或兴趣对积分进行分类。"
mautic.point.group.report.table="组得分"
mautic.point.insight.action="洞察力行动"
mautic.point.insight.action.set_custom_field="将自定义字段设置为获胜点编组"
mautic.point.insight.action.set_custom_field_to_winning_point_group="Insight Action：将自定义字段设置为获胜点组"
mautic.point.insight.action.set_custom_field_to_winning_point_group.tooltip="愿意写这ID 将具有最高值的点群组的名称和名称写入所选自定义字段（例如，“1（YourPointGroupName）”）。如果所有群组均为0，则不执行任何操作。即使存在多个具有相同值的群组，也仅写入一个赢家。"
mautic.point.insight.compare_point_groups="比较点编组"
mautic.point.insight.customfield="自定义字段"
mautic.point.insight.empty.heading="深入了解联系人的主要兴趣"
mautic.point.insight.empty.subheading="根据联系人的行为轻松识别他们的主要兴趣。使用这些洞察来根据他们的兴趣定制您的营销。"
mautic.point.insight.form.confirmbatchdelete="是否删除所选见解？"
mautic.point.insight.form.confirmdelete="删除点洞察力，%name%?"
mautic.point.insight.header.edit="编辑洞察"
mautic.point.insight.header.new="新增积分分析"
mautic.point.insight.noresults.tip="通过比较联系人在不同点组中的价值，Point Insights可让您轻松识别联系人的主要兴趣，如产品组或品牌。"
mautic.point.insight.onboarding.group.heading="如何使用Point Insights"
mautic.point.insight.onboarding.step1="创建点编组以分类联系人的兴趣。"
mautic.point.insight.onboarding.step2="创建新的点洞察。"
mautic.point.insight.onboarding.step3="选择要比较的点编组。"
mautic.point.insight.onboarding.step4="选择将在其中存储结果的联系人字段。"
mautic.point.insight.onboarding.step5="开始使用点洞察作为过滤器。"
mautic.point.insight.pointgroups.compare="要比较的点编组"
mautic.point.insight.purpose.copy="使用确定的主要兴趣作为细分市场、广告系列或动态内容的过滤器。"
mautic.point.insight.purpose.eyebrow="目的"
mautic.point.insight.purpose.heading="基于主要兴趣的定制"
mautic.point.insight.type="洞察力"
mautic.point.insight.understand.copy="根据接触在其中具有最多点的点编组自动更改接触字段值。"
mautic.point.insight.understand.eyebrow="理解"
mautic.point.insight.understand.heading="什么是点洞察？"
mautic.point.insights.menu="点洞察"
mautic.point.menu.edit="编辑点操作"
mautic.point.menu.index="管理操作"
mautic.point.menu.new="新点操作"
mautic.point.permissions.groups="组-用户有权访问"
mautic.point.permissions.header="波因特"
mautic.point.permissions.insights="洞察-用户有权访问"
mautic.point.permissions.points="点操作-用户有权访问"
mautic.point.permissions.triggers="触发器-用户有权访问"
mautic.point.point="点"
mautic.point.report.group_id="组ID"
mautic.point.report.group_name="组名称"
mautic.point.report.group_score="组得分"
mautic.point.thead.action="行动"
mautic.point.thead.delta="积分+/-"
mautic.point.thead.group="组"
mautic.point.trigger.addevent="从“添加事件”列表中选择事件。"
mautic.point.trigger.empty.heading="在互动达到高峰时触发自动化"
mautic.point.trigger.empty.subheading="当联系人的参与度达到关键阈值（以点数衡量）时自动响应。"
mautic.point.trigger.event.add="添加事件"
mautic.point.trigger.form.color="接触色"
mautic.point.trigger.form.color_descr="至少具有上述点数的触点将被指定为此颜色。"
mautic.point.trigger.form.confirmbatchdelete="删除所选触发器-这将永久删除其事件配置和触发器历史记录。"
mautic.point.trigger.form.confirmdelete="删除触发器，%name%？这将永久删除其事件配置和触发历史记录。"
mautic.point.trigger.form.existingleads="是否在保存时触发现有的适用联系人（如果已发布）？"
mautic.point.trigger.form.modalheader="触发器操作详细信息"
mautic.point.trigger.form.points="最小点数"
mautic.point.trigger.form.points_descr="触发相关操作所需的最小点数。"
mautic.point.trigger.header.edit="编辑触发器"
mautic.point.trigger.header.index="点触发器"
mautic.point.trigger.header.new="新触发"
mautic.point.trigger.menu.edit="编辑触发器事件"
mautic.point.trigger.menu.index="管理触发器"
mautic.point.trigger.noresults.tip="创建一个触发器，一旦达到一定的积分水平，就可以对联系人采取一些行动。您可以调整联系人的活动，推到CRM发送电子邮件等。定义一种颜色，以便在查看联系人列表时一目了然地看到联系人的位置!"
mautic.point.trigger.onboarding.copy="触发器执行预定义的操作，如更改段、添加标记或推送到CRM - 联系人达到特定分数的时刻。"
mautic.point.trigger.onboarding.cta="创建新触发器"
mautic.point.trigger.onboarding.eyebrow="理解"
mautic.point.trigger.onboarding.group.heading="设置分数触发事件"
mautic.point.trigger.onboarding.heading="点触发器如何工作？"
mautic.point.trigger.onboarding.notification.content="只要达到分数阈值，它们就会激活，从而确保根据参与度级别立即采取行动。"
mautic.point.trigger.onboarding.notification.title="触发器的行为与基于事件的事件不同"
mautic.point.trigger.onboarding.step1="创建一个新的触发器并设置接触必须达到的最小点数。"
mautic.point.trigger.onboarding.step2="选择一个或多个在达到点阈值时执行的事件。"
mautic.point.trigger.onboarding.step3="发布触发器。您可以选择是否立即将其应用于已满足条件的现有联系人。"
mautic.point.trigger.onboarding.usecase.eyebrow="用例"
mautic.point.trigger.onboarding.usecase.heading="实用性强"
mautic.point.trigger.tab.events="事件"
mautic.point.trigger.thead.points="点总数"
mautic.point.trigger.thead.pointstrigger="点触发"
mautic.points.menu.insights="积分洞察"
mautic.points.menu.root="积分"
mautic.project.point="点动作"
mautic.project.pointtrigger="点触发器"
mautic.protip.points.decay="实施潜在客户评分衰减模型以准确捕捉意图。"
mautic.protip.points.limit="使用限制来防止分数过高或过低。"
mautic.protip.points.reduce="随着时间的推移，如果联系人变得不活跃，则系统地降低分数。"
mautic.protip.triggers.behavioral="使用行为触发器根据用户操作及时发送相关电子邮件。"
mautic.widget.points.in.time="时间点"
