; YXHK versioned Simplified Chinese translations.
mautic.point.delta.notblank="必须选择一个点变化（增量）。"
mautic.point.form.actions.notempty="至少需要一个操作。"
mautic.point.insight.action.required="必须选择洞察操作。"
mautic.point.insight.type.required="必须选择洞察类型。"
mautic.point.type.notblank="至少必须选择一个分值操作。"
