; YXHK versioned Simplified Chinese translations.
mautic.config.dsn.host="主机"
mautic.config.dsn.options="可选项"
mautic.config.dsn.password="密码"
mautic.config.dsn.path="路径"
mautic.config.dsn.port="端口"
mautic.config.dsn.save_to_test="保存更改以测试DSN。"
mautic.config.dsn.scheme="方案"
mautic.config.dsn.user="用户"
mautic.config.dsn.using_current_dsn="使用当前保存的DSN"
mautic.config.header.index="配置"
mautic.config.menu.index="配置"
mautic.config.notwritable="配置文件不可写入！变更无法保存。"
mautic.config.remove_file_contents="删除为本设置存储的内容？"
mautic.config.restricted="由系统设定"
mautic.sysinfo.dbinfo.driver="Doctrine 驱动程序"
mautic.sysinfo.dbinfo.platform="Doctrine 数据库平台（自动检测）"
mautic.sysinfo.dbinfo.property="属性"
mautic.sysinfo.dbinfo.title="数据库信息"
mautic.sysinfo.dbinfo.value="值"
mautic.sysinfo.dbinfo.version="版本号"
mautic.sysinfo.folder.path="文件夹/文件路径"
mautic.sysinfo.folders.title="下列文件夹和文件必须可写入，以便 Mautic 正常工作。"
mautic.sysinfo.header.index="系统信息"
mautic.sysinfo.is.writable="可写入"
mautic.sysinfo.log.missing="今天的 Mautic 错误日志为空。请检查服务器错误日志中的错误信息。Mautic 未能捕捉到该信息。"
mautic.sysinfo.log.title="当前错误日志"
mautic.sysinfo.menu.index="系统信息"
mautic.sysinfo.no.recommendations="目前没有任何建议适用于您。您的服务器配置正确！"
mautic.sysinfo.phpinfo.missing="信息不可用。服务器上的 PHP 函数 phpinfo() 被关闭。"
mautic.sysinfo.phpinfo.phpversion="服务器上的 PHP 函数 phpinfo() 被关闭。您的 PHP 版本为 <b>%phpversion%</b>."
mautic.sysinfo.tab.dbinfo="数据库信息"
mautic.sysinfo.tab.folders="文件夹 & 文件权限"
mautic.sysinfo.tab.log="日志"
mautic.sysinfo.tab.phpinfo="PHP 信息"
mautic.sysinfo.tab.recommendations="建议"
mautic.sysinfo.unwritable="不可写入"
mautic.sysinfo.writable="可写入"
