; YXHK versioned Simplified Chinese translations.
mautic.campaign.form.field_value="表单字段值"
mautic.campaign.form.submit="表单已提交"
mautic.config.tab.formconfig="窗体设置"
mautic.config.tab.formresultsconfig="表单结果设置"
mautic.core.config.header.formconfig.description="管理所有表单的表单提交规则和默认行为。"
mautic.core.config.header.formresultsconfig.description="配置如何处理和报告表单提交数据。"
mautic.core.field.mapped.to="字段映射到%object%"
mautic.email.form.users="发送邮件给用户"
mautic.form.abtest.criteria="表单数据"
mautic.form.abtest.criteria.submissions="提交率"
mautic.form.abtest.label.hits="独立页面点击"
mautic.form.abtest.label.sentemils="发送的邮件数"
mautic.form.abtest.label.submissions="提交计数"
mautic.form.abtest.submissions="%count% 个提交"
mautic.form.action.add="新增提交操作"
mautic.form.action.repost="发布结果到另一表单"
mautic.form.action.repost.authorization_header="授权头"
mautic.form.action.repost.authorization_header.tooltip="若表单在防火墙内，请在此设置授权头信息"
mautic.form.action.repost.descr="将提交的结果发送到另一个表单"
mautic.form.action.repost.failed_message="提交 URL: <a href='%link%'>%link%</a><br /><br />错误信息： %message%<br /><br />结果：<br />%results%"
mautic.form.action.repost.failed_subject="表单再提交失败： %form%"
mautic.form.action.repost.failure_email="提交失败通知邮件"
mautic.form.action.repost.failure_email.tooltip="若重新提交由于任何原因而失败，将给以下地址发送通知。"
mautic.form.action.repost.field_mapping="(可选) 覆盖接收表单的字段名称："
mautic.form.action.repost.post_url="提交 URL"
mautic.form.action.repost.post_url.tooltip="重新提交表单结果时使用的 URL"
mautic.form.action.repost.validation_failed="表单验证失败"
mautic.form.action.sendemail="发送表单结果"
mautic.form.action.sendemail.copytolead="发送给联络人"
mautic.form.action.sendemail.descr="发送简单的邮件或表单结果给联络人或其它指定的邮件地址。"
mautic.form.action.sendemail.dragfield="点击以插入字段"
mautic.form.action.sendemail.emailtoowner="发送给所有者"
mautic.form.action.sendemail.immediately="立即发送"
mautic.form.action.sendemail.immediately.desc="忽略电子邮件设置中的队列模式"
mautic.form.action.sendemail.message="信息"
mautic.form.action.sendemail.setreplyto="回复联系人"
mautic.form.action.sendemail.setreplyto_tooltip="将联系人的电子邮件设置为&amp;quot；回复&amp;quot；地址，以便在回复结果电子邮件时，联系人地址将是默认收件人。"
mautic.form.action.sendemail.subject="主题"
mautic.form.action.sendemail.subject.default="您的表单结果"
mautic.form.actions="表单操作"
mautic.form.builder.advanced_options="高级选项"
mautic.form.builder.formfield="提交结果"
mautic.form.builder.formfield.placeholder="插入表单字段别名 ..."
mautic.form.builder.formfield.remove_row="删除行"
mautic.form.campaign.event.field_value="表单字段值"
mautic.form.campaign.event.field_value_descr="表单字段值满足定义的条件时，触发特定的动作。"
mautic.form.campaign.event.forms="仅限表单"
mautic.form.campaign.event.forms_descr="请选择可触发推广流程中特定操作的表单(表单组)。"
mautic.form.campaign.event.submit="提交表单"
mautic.form.campaign.event.submit_descr="联络人提交表单时触发操作"
mautic.form.config.form.blocked_free_email_providers="被屏蔽的免费电子邮件提供商域名"
mautic.form.config.form.blocked_free_email_providers.tooltip="输入域，每行一个，以阻止来自这些提供商的表单提交。"
mautic.form.config.form.do_not_submit_email="不接受来自这些域名的提交"
mautic.form.config.form.do_not_submit_email.tooltip="输入您要限制提交表单的电子邮件（每行一个）。您可以使用过滤器（*domain.com）过滤特定的电子邮件地址（email@yourdomain.com）或整个域名。"
mautic.form.config.form.form_field_autofill="启用从联系人数据自动填充表单字段"
mautic.form.config.form.form_field_autofill.tooltip="默认情况下禁用，以降低暴露表单中的个人身份信息（PII）的风险。除非您的组织明确要求自动填写并接受该风险，否则请保持禁用状态。"
mautic.form.config.form.successful_submit_action="成功提交操作"
mautic.form.config.form.successful_submit_action.tooltip="在表单上选择成功提交操作的位置"
mautic.form.config.form.successful_submit_action_at_the_bottom="底部"
mautic.form.config.form.successful_submit_action_at_the_top="在顶部"
mautic.form.config.form_results_data_sources="使用表单结果作为报表数据源"
mautic.form.config.form_results_data_sources.tooltip="如果要将窗体结果表用作报表数据源，请启用此选项。"
mautic.form.confirm_batch_rebuild="为所选的表单(表单组)重建缓冲的 HTML"
mautic.form.dashboard.widgets="表单控件"
mautic.form.details.detail="详情"
mautic.form.details.field_order="字段排序： %order%"
mautic.form.details.field_type="字段类型： %type%"
mautic.form.event.submission="%form% 提交"
mautic.form.event.submitted="表单已提交"
mautic.form.field="表单字段"
mautic.form.field.add="新增字段"
mautic.form.field.checkboxgrp.max_message="最大选择错误消息"
mautic.form.field.checkboxgrp.max_message.placeholder="您不能选择超过[X]个选项。"
mautic.form.field.checkboxgrp.max_message.tooltip="可选。使用适应最大设置的默认值。"
mautic.form.field.checkboxgrp.maximum="最大选择数"
mautic.form.field.checkboxgrp.min_message="最小选择错误消息"
mautic.form.field.checkboxgrp.min_message.placeholder="您必须至少选择[X]个选项。"
mautic.form.field.checkboxgrp.min_message.tooltip="可选。使用适应最小值集的默认值。"
mautic.form.field.checkboxgrp.minimum="最小选择数"
mautic.form.field.file.allowed_extensions="可接受的文件扩展名"
mautic.form.field.file.allowed_size="最大文件大小 (MB)"
mautic.form.field.file.public="可供公众访问的下载链接"
mautic.form.field.file.set_as_profile_image="设置为联系人配置文件图像"
mautic.form.field.file.tooltip.allowed_extensions="逗号分隔值（例如“gif，jpg”）"
mautic.form.field.file.tooltip.allowed_size="最大上传文件大小的 PHP 配置是： %uploadSize%MB"
mautic.form.field.form.alias="字段的 HTML 名称"
mautic.form.field.form.alias.tooltip="HTML 元素的名称。表单保存后，该选项将不可修改。若留空，则后根据字段标签自动生成。"
mautic.form.field.form.always_display="始终显示"
mautic.form.field.form.always_display.tooltip="如果设置了一次显示的最大字段数，则强制在表单中显示此字段。"
mautic.form.field.form.auto_fill="自动填充数据"
mautic.form.field.form.condition="条件"
mautic.form.field.form.condition.any_value="任何值"
mautic.form.field.form.condition.enabled="启用"
mautic.form.field.form.condition.field.value=""
mautic.form.field.form.condition.select.value="值"
mautic.form.field.form.condition.select_one_of="选择其中一"
mautic.form.field.form.condition.select_other_thatn="选择除"
mautic.form.field.form.condition.show.on="仅当选择来自"
mautic.form.field.form.condition.show.only="仅在选定值上显示"
mautic.form.field.form.condition.show.only.tooltip="带有选项组的选择框将仅显示与父字段值匹配的选项组。如果不存在选项组，则条件字段本身将被隐藏。用例：仅显示具有某些州的国家/地区的州。"
mautic.form.field.form.container_attr="字段容器样式"
mautic.form.field.form.dependency.label="此字段是否依赖于从另一个字段输入的值？"
mautic.form.field.form.dependent.field.mapping="依赖字段映射"
mautic.form.field.form.emptyvalue="空值"
mautic.form.field.form.field_width="字段宽度"
mautic.form.field.form.field_width.fifty="50%"
mautic.form.field.form.field_width.one_hundred="100%"
mautic.form.field.form.field_width.seventy_five="75%"
mautic.form.field.form.field_width.sixty_six="66%"
mautic.form.field.form.field_width.thirty_three="33%"
mautic.form.field.form.field_width.twenty_five="25%"
mautic.form.field.form.form_attr="表单造型"
mautic.form.field.form.form_attr.tooltip="添加自定义HTML 表单标签的样式属性，例如name = my-form。某些软件可能需要自订样式属性。&quot;&quot;"
mautic.form.field.form.freehtml_attributes="HTML 文本样式"
mautic.form.field.form.freetext_attributes="描述文本样式"
mautic.form.field.form.header="报头"
mautic.form.field.form.header_attributes="页眉样式"
mautic.form.field.form.helpmessage="帮助信息"
mautic.form.field.form.hide_when_value_exists="值存在时隐藏"
mautic.form.field.form.inputattr="输入样式"
mautic.form.field.form.label="标签"
mautic.form.field.form.labelattr="标签样式"
mautic.form.field.form.mapped.field="匹配字段"
mautic.form.field.form.mapped.object="匹配对象"
mautic.form.field.form.multiple="允许多值？"
mautic.form.field.form.number_precision="精度"
mautic.form.field.form.number_precision.tooltip="四舍五入前允许的位数。"
mautic.form.field.form.property_buttontype="按钮类型"
mautic.form.field.form.property_captcha="Captcha 答案"
mautic.form.field.form.property_captchaerror="定制错误信息"
mautic.form.field.form.property_list_sync_choices="使用指定联系人/公司字段的列表选项。"
mautic.form.field.form.property_lookup_field="查阅字段"
mautic.form.field.form.property_pagebreak_nextpage_label="下一页按钮标签"
mautic.form.field.form.property_pagebreak_prevpage_label="上一页按钮标签"
mautic.form.field.form.property_pagebreak_prevpage_placeholder="留空则不显示"
mautic.form.field.form.property_placeholder="输入占位符"
mautic.form.field.form.rating_base_color="基础星星颜色"
mautic.form.field.form.rating_star_color="所选星星颜色"
mautic.form.field.form.rating_star_count="星数"
mautic.form.field.form.rating_symbol="评级符号"
mautic.form.field.form.rating_symbol.asterisk="星号"
mautic.form.field.form.rating_symbol.asterisk_label="星号"
mautic.form.field.form.rating_symbol.circle_filled="圈"
mautic.form.field.form.rating_symbol.circle_filled_label="●圆"
mautic.form.field.form.rating_symbol.diamond_filled="钻石"
mautic.form.field.form.rating_symbol.diamond_filled_label="◆钻石"
mautic.form.field.form.rating_symbol.heart="心脏"
mautic.form.field.form.rating_symbol.heart_label="心脏病"
mautic.form.field.form.rating_symbol.sparkle="闪耀"
mautic.form.field.form.rating_symbol.sparkle_label="电子邮件"
mautic.form.field.form.rating_symbol.square="平方"
mautic.form.field.form.rating_symbol.square_label="🞵广场"
mautic.form.field.form.rating_symbol.star_filled="星星"
mautic.form.field.form.rating_symbol.star_filled_alt="星星（已填充）"
mautic.form.field.form.rating_symbol.star_filled_alt_label="星星星星（已填充）"
mautic.form.field.form.rating_symbol.star_filled_label="★星星"
mautic.form.field.form.read_only="只读"
mautic.form.field.form.saveresult="保存结果？"
mautic.form.field.form.show.after.submissions="显示后%number% 划界案"
mautic.form.field.form.show.after.x.submissions="在 X 次提交后显示"
mautic.form.field.form.show.when.value.exists="若存在值则显示"
mautic.form.field.form.showheader="显示 header？"
mautic.form.field.form.showlabel="显示标签？"
mautic.form.field.form.slider_max="最大值"
mautic.form.field.form.slider_min="最小值"
mautic.form.field.form.slider_step="步骤"
mautic.form.field.form.validationmsg="验证信息"
mautic.form.field.form.value="值"
mautic.form.field.group.labelattr="单选/复选框标签样式"
mautic.form.field.help.attr="添加自定义HTML 设置属性的样式，即class = myclass&quot;&quot;"
mautic.form.field.help.auto_fill="允许Mautic 以使用跟踪的联系人配置文件的值自动填充此值。如果多个联系人共享相同的IP 地址，可能会预填充不正确的详细信息。仅适用于嵌入到Mautic 登录页。"
mautic.form.field.help.captcha="利用标签来显示任何人都可以回答的简单问题，在此输入正确的答案。例如, ' 10 加 8 等于几?' 在此输入 18。也可以保持空白，隐藏标签，将其作为 captcha 蜜罐。"
mautic.form.field.help.captcha_placeholder="留空则将其用作蜜罐。"
mautic.form.field.help.container_attr="添加自定义HTML 包装整个字段的div的样式属性，例如class = myclass&quot;&quot;"
mautic.form.field.help.emptyvalue="在列表中输入标签作为空值。选择空值来关闭。"
mautic.form.field.help.field_width="选择此字段在表单中显示时的宽度。"
mautic.form.field.help.group.labelattr="添加自定义HTML 包装每个单选按钮/复选框的标签的样式属性，即class = myclass。请注意，如果留空或未包含类，则每个标签/输入周围将放置一个包装div&quot;&quot;"
mautic.form.field.help.helpmessage="标签下面要显示的文本"
mautic.form.field.help.mapped.field="选择一个字段以将其与此表单字段关联。如果该字段是唯一标识符（如联系人的电子邮件），并且存在具有相同值的联系人，则将更新匹配的联系人。如果找不到匹配的联系人，则将创建新联系人。"
mautic.form.field.help.mapped.object="选择一个对象以获取其下面的字段列表。"
mautic.form.field.help.pagebreak="插入分页符，只有本页的字段会被显示"
mautic.form.field.help.rating_base_color="未选中的星星的颜色"
mautic.form.field.help.rating_star_color="所选星星的颜色"
mautic.form.field.help.rating_star_count="联系人可选择的星级总数"
mautic.form.field.help.rating_symbol="用于评级的符号"
mautic.form.field.help.read_only="启用后，自动填充的字段将被锁定以进行编辑，以保持数据的一致性。"
mautic.form.field.help.saveresult="若设置为否，则该值将不会保存到数据库。"
mautic.form.field.help.show.after.x.submissions="仅在活动的联络人提交该表单 X 次后显示该字段， X 为本选项中的提交次数。"
mautic.form.field.help.show.when.value.exists="若活动的联络人已经填写过该值，则显示。"
mautic.form.field.hide.if.submission.count="{1} 在 1 次提交后显示 |[2,Inf] 在 %count% 次提交后显示"
mautic.form.field.hide.if.value="若存在值则不显示"
mautic.form.field.points.operation="%operator% 点数%points% 从%group%"
mautic.form.field.section.attributes="造型"
mautic.form.field.section.general="通用"
mautic.form.field.section.mappedfield="映射字段"
mautic.form.field.section.progressive.profiling="行为"
mautic.form.field.section.properties="属性"
mautic.form.field.section.validation="数据验证"
mautic.form.field.type="字段类型"
mautic.form.field.type.blockfreeemail="阻止免费电子邮件提供商"
mautic.form.field.type.blockfreeemail.tooltip="阻止常见消费者电子邮件提供程序列表中的电子邮件地址。可以在系统配置中的“表单设置”下自定义此列表。"
mautic.form.field.type.button="按钮"
mautic.form.field.type.captcha="验证码"
mautic.form.field.type.checkboxgrp="多选按钮组"
mautic.form.field.type.companyLookup="公司简介"
mautic.form.field.type.country="国家"
mautic.form.field.type.date="日期"
mautic.form.field.type.datetime="日期和时间"
mautic.form.field.type.donotsubmit="域名提交过滤器"
mautic.form.field.type.email="邮件地址"
mautic.form.field.type.email.blocked_free_providers="被屏蔽的免费电子邮件提供商"
mautic.form.field.type.file="文件"
mautic.form.field.type.freehtml="HTML 区域"
mautic.form.field.type.freetext="描述区域"
mautic.form.field.type.hidden="隐藏对象"
mautic.form.field.type.lookup="查找"
mautic.form.field.type.number="数字"
mautic.form.field.type.pagebreak="分页符"
mautic.form.field.type.password="密码"
mautic.form.field.type.radiogrp="单选按钮"
mautic.form.field.type.rating="评级"
mautic.form.field.type.select="选取"
mautic.form.field.type.slider="滑块"
mautic.form.field.type.tel="电话"
mautic.form.field.type.tel.international="验证为国际格式"
mautic.form.field.type.text="文本：简短回答"
mautic.form.field.type.textarea="案文：段落"
mautic.form.field.type.url="URL"
mautic.form.form="表单"
mautic.form.form.addaction="请从“添加新的提交操作” 列表中选择一个操作。"
mautic.form.form.addfield="请从“添加新字段” 列表中选择一个字段。"
mautic.form.form.change_points_by="更改点数%value%"
mautic.form.form.component.fields="添加新字段"
mautic.form.form.component.fields.conditional="根据选定值添加字段"
mautic.form.form.component.submitactions="增加新的提交操作"
mautic.form.form.confirmbatchdelete="删除所选的表单？这将同时删除与该表单相关的所有结果。"
mautic.form.form.confirmdelete="删除表单，%name%? 这将同时删除该表单相关的所有结果！"
mautic.form.form.header.copy="表单实现"
mautic.form.form.header.edit="编辑表单 - %name%"
mautic.form.form.header.embedded="嵌入式"
mautic.form.form.header.external_cms="外部CMS"
mautic.form.form.header.landingpages="登陆页面"
mautic.form.form.header.new="新建表单"
mautic.form.form.header.preview="预览表单"
mautic.form.form.header.selfhosted="自托管"
mautic.form.form.help.automaticcopy="使用此选项时，可以在平台内编辑整个表单，并且这些更改将自动反映在插入表单的任何页面上。"
mautic.form.form.help.automaticcopy.iframe="通过 iframe"
mautic.form.form.help.automaticcopy.iframe.note="注：调整表单的高度和宽度，以适应页面布局。"
mautic.form.form.help.automaticcopy.js="通过 Javascript (推荐)"
mautic.form.form.help.landingpages="轻松地将表单放置在Mautic 登录页面。"
mautic.form.form.help.selfhosted="使用自托管HTML，在平台上所做的更改不会在您的网站上更新，除非您手动编辑HTML 代码，确保不依赖于外部服务器并增强隐私保护。"
mautic.form.form.help.selfhosted.body="复制粘贴表单的内容到文件的正文部分。"
mautic.form.form.help.selfhosted.script="复制粘贴内容到文件的头部或正文部分。若插入多个表单，每页只需要插入一次该内容。"
mautic.form.form.iframe.title="嵌入式表单"
mautic.form.form.kioskmode="Kiosk 模式"
mautic.form.form.kioskmode.no="跟踪访问者数据"
mautic.form.form.kioskmode.tooltip="若设定该选项，表单提交后将不会生成新的联络人跟踪代码，或分配 IP 地址来创建/更新联络人。"
mautic.form.form.kioskmode.yes="保护访客隐私"
mautic.form.form.locale.tooltip="设置窗体的主要语言。默认为配置的语言。"
mautic.form.form.modalheader="表单组件详情"
mautic.form.form.no_index="禁用搜索索引"
mautic.form.form.pagetoken.notpublished="表单尚未发布。公众无法访问。"
mautic.form.form.postaction="成功提交操作"
mautic.form.form.postaction.hideform="隐藏表单（+显示消息）"
mautic.form.form.postaction.message="显示信息"
mautic.form.form.postaction.redirect="重定向 URL"
mautic.form.form.postaction.return="停留在表单页"
mautic.form.form.postactionproperty="重定向 URL/信息"
mautic.form.form.postactionproperty.tooltip="可使用的代币：用途：<br>- <code>{pagelink=ID}</code> 用于登录页URL (for重定向操作）<br>- <code>{contactfield=ALIAS}</code> 用于销售线索值<br>- <code>{formfield=ALIAS}</code> 以用于表单输入。"
mautic.form.form.preview="预览"
mautic.form.form.progressive_profiling_limit.max_fields="一次显示的最大字段数"
mautic.form.form.progressive_profiling_limit.max_fields.tooltip="此字段的数字启用渐进式分析功能，并允许一次仅呈现一定数量的字段。"
mautic.form.form.progressive_profiling_limit_unlimited="无限"
mautic.form.form.renderstyle="使用主题样式？"
mautic.form.form.renderstyle.tooltip="禁用/启用渲染CSS 自template"
mautic.form.form.reply_to_contact="回复联系人"
mautic.form.form.resultcount="结果数"
mautic.form.form.results="结果"
mautic.form.form.results.name="结果 ID %id%"
mautic.form.form.searchcommand.hasresults="has:results"
mautic.form.form.searchcommand.hasresults.description="已收到提交的表单的筛选器"
mautic.form.form.searchcommand.isexpired="is:expired"
mautic.form.form.searchcommand.isexpired.description="筛选已过有效期的表单"
mautic.form.form.searchcommand.ispending="is:pending"
mautic.form.form.searchcommand.ispending.description="已安排但尚未活动的表单的筛选器"
mautic.form.form.send_to_contact="发送至联系人"
mautic.form.form.send_to_owner="发送给所有者"
mautic.form.form.template.help="若该表单需要通过弹出页或页面框架集成到第 3 方网站，请选择一个模板来格式化包含表单的页面。"
mautic.form.form.viewresults="{0} 无结果 |{1} 查看一个结果 |]1,Inf[ 查看 %count% 结果"
mautic.form.forms="表单"
mautic.form.graph.line.submissions="提交"
mautic.form.lead="销售线索"
mautic.form.list.block.heading="捕获潜在客户并收集数据"
mautic.form.list.block.subheading="创建从简单的联系人表单到复杂的多字段调查问卷的所有内容。"
mautic.form.list.capabilities.heading="突出显示的功能"
mautic.form.list.copy="使用它们可以将匿名访问者转换为已知的潜在客户，逐步建立详细的联系人档案，并触发自动化的营销活动。"
mautic.form.list.eyebrow="目的"
mautic.form.list.feature1.copy="根据已知的联系人数据或以前提交的内容显示或隐藏字段，以避免询问重复的问题。"
mautic.form.list.feature1.heading="渐进式性能分析"
mautic.form.list.feature2.copy="修改段/标签/点、发送电子邮件、触发资产下载、重定向URL、显示消息等。"
mautic.form.list.feature2.heading="操作（提交时）"
mautic.form.list.heading="为您的销售线索挖掘提供动力"
mautic.form.list.use1="标准联系表格、新闻通讯注册、演示请求"
mautic.form.list.use2="提供有价值的资产（电子书、指南）以换取表格提交"
mautic.form.list.use3="收集网络研讨会、研讨会或会议的注册信息"
mautic.form.list.use4="允许联系人更新其首选项或信息"
mautic.form.list.use5="创建简单的调查或反馈表单"
mautic.form.list.uses.heading="你可以用它们做什么"
mautic.form.noresults.tip="请使用我们的第 3 方 CMS 插件来方便集成表单到您的网站！"
mautic.form.permissions.forms="表单 - 用户有权访问"
mautic.form.permissions.header="表单授权"
mautic.form.point.action="表单操作"
mautic.form.point.action.forms="仅限所选表单"
mautic.form.point.action.forms.descr="选择本操作适用的表单。若未选择任何项，则适用于所有表单。"
mautic.form.point.action.submit="提交表单"
mautic.form.point.action.submit_descr="联络人提交表单时更新积分"
mautic.form.rebuild="重建缓存"
mautic.form.report.form_id="表单 ID"
mautic.form.report.form_results.label="表单结果%field%"
mautic.form.report.page_id="页面 ID"
mautic.form.report.page_name="页面名称"
mautic.form.report.submission.id="提交ID"
mautic.form.report.submission.table="表单提交"
mautic.form.report.submit.date_submitted="提交日期"
mautic.form.result.add_to_segment="更改提交者的细分"
mautic.form.result.export.csv="导出为 CSV"
mautic.form.result.export.html="导出为 HTML"
mautic.form.result.export.pdf="导出为 PDF"
mautic.form.result.export.xlsx="导出为 Excel"
mautic.form.result.header.index=" %name% 的结果集"
mautic.form.result.thead.date="提交日期"
mautic.form.result.thead.referrer="转发者"
mautic.form.results.form.confirmdelete="删除结果"
mautic.form.stage.action="表单操作"
mautic.form.stage.action.submit="提交表单"
mautic.form.stats.submission_counts="提交（唯一/全部）"
mautic.form.stats.submission_counts.total="提交总数"
mautic.form.stats.submission_counts.total.desc="本表格收到的提交总数"
mautic.form.stats.submission_counts.unique="相关联络活动"
mautic.form.stats.submission_counts.unique.desc="提交此表单的联系人数量"
mautic.form.submission.count="提交计数"
mautic.form.submission.errors="错误:"
mautic.form.submission.limit="最大提交量"
mautic.form.submission.limit_message="已达到限制消息"
mautic.form.submission.limit_reached="此表单已不再接受提交。"
mautic.form.submission.limit_reached.notification="形式“%form%“已达到提交限制。"
mautic.form.submission.limit_settings="提交限制"
mautic.form.submission.limit_status="%current% 的%limit% 划界案"
mautic.form.submission.pleasewait="请等待 ..."
mautic.form.submission.thankyou="谢谢您！"
mautic.form.tab.actions="操作"
mautic.form.tab.fields="字段"
mautic.form.table.most.submitted="提交量最多的表单"
mautic.form.table.top.referrers="转发量最多的转发者"
mautic.form.tag.kioskmode.label="保护访问者的隐私。没有设置或IP 在创建联系人时注册地址"
mautic.form.webhook.event.form.submit="表单提交事件"
mautic.form_results.form.confirmbatchdelete="删除所选结果？"
mautic.forms.command.dropped_tables_count="下降%table_count% 已删除其表单的表单结果表"
mautic.forms.command.orphan_submission_records_deleted="从表格结果表中删除的记录总数=%record_count%"
mautic.placeholder_tokens.form.field_value="字段值"
mautic.placeholder_tokens.form.page="着陆页"
mautic.placeholder_tokens.form.redirect_url="表单的重定向URL可以通过使用令牌（例如/thank-you？email={formfield=email})"
mautic.placeholder_tokens.form_tokens="重定向URL 具体"
mautic.project.form="表单"
mautic.protip.forms.language="在表格标题和CTA中使用清晰、面向行动的语言（例如，“获取免费指南”与“提交”）。"
mautic.protip.forms.minimize="最大限度地减少字段数量以提高表单提交率。"
mautic.protip.forms.multistep="对于较长的表格，使用多步骤的过程，使他们感觉不那么压倒性。"
mautic.protip.forms.redirect="表单的重定向URL可以通过使用/thank-you？email=这样的标记来包含变量{formfield=email}"
mautic.report.group.form.results="表单结果"
mautic.report.group.forms="表单"
mautic.report.source.form.submissions="表单提交"
mautic.report.source.forms="表单"
mautic.widget.created.forms="创建表单"
mautic.widget.submissions.in.time="及时提交"
mautic.widget.top.submission.referrers="表单提交的首要来源"
mautic.widget.top.submitters="首要提交者"
