; YXHK versioned Simplified Chinese translations.
mautic.report.filter.date_comparison_timezone_tooltip="所选条件使用查看报告的用户的时区来比较日期。"
mautic.report.filter.string_comparison_utc_tooltip="选定条件将字符串值作为文本进行比较，始终使用UTC时区。"
