; YXHK versioned Simplified Chinese translations.
mautic.config.tab.form.csv_always_enclose="总是在CSV导出中引用数据"
mautic.config.tab.form.csv_always_enclose.tooltip="如果用于打开CSV的应用程序要求用双引号引用值，请启用此选项。例如：&amp;#34；名字&amp;#34&amp;#34;&amp;#34;,&amp;#34;姓氏&amp;#34；"
mautic.config.tab.reportconfig="报告设置"
mautic.core.calculated.fields="计算列"
mautic.core.config.header.reportconfig.description="为报告配置导出格式和数据处理。"
mautic.format.invalid="格式%format% 不支持。支持的格式为：%validFormats%."
mautic.protip.reports.dnc="跟踪DNC评论以重新插入因临时问题而退回的联系人"
mautic.report.campaign.channel.category_id="渠道项: 分类 ID"
mautic.report.campaign.channel.created_by="渠道项: 创建人"
mautic.report.campaign.channel.created_by_user="渠道项: 创建人姓名"
mautic.report.campaign.channel.date_added="渠道项: 添加日期"
mautic.report.campaign.channel.description="渠道项: 描述"
mautic.report.campaign.channel.name="渠道项: 名称"
mautic.report.dashboard.widgets="报表控件"
mautic.report.dashboard.widgets.full_report="查看完整的报表"
mautic.report.dashboard.widgets.no_report_found="<strong>哦，啪！</strong> 报表已删除或找不到数据。"
mautic.report.date.last_30_days="过去30天"
mautic.report.date.last_7_days="最近7天"
mautic.report.date.last_90_days="过去90天"
mautic.report.date.today="今天"
mautic.report.date.yesterday="昨天"
mautic.report.download.missing="报告%id% 不具有CSV 尚未生成。但它已配置了预设报告。"
mautic.report.download.missing.but.scheduled="报告%id% 不具有CSV 尚未生成。但在您尝试下载它时已请求了它。一旦生成，您将立即收到电子邮件通知。"
mautic.report.export.and.send="导出和发送"
mautic.report.field.category_id="类别 ID"
mautic.report.field.category_name="类别名"
mautic.report.field.date_added="创建日期"
mautic.report.field.date_modified="上次修改日期"
mautic.report.field.is_published="已发布"
mautic.report.field.lead.address1="联络人地址 1"
mautic.report.field.lead.address2="联络人地址 2 "
mautic.report.field.lead.city="联络人城市"
mautic.report.field.lead.company="联络人公司名称"
mautic.report.field.lead.country="联络人国家"
mautic.report.field.lead.email="联络人电子邮件"
mautic.report.field.lead.firstname="联络人名字"
mautic.report.field.lead.id="联络人 ID "
mautic.report.field.lead.label="联系人 %field%"
mautic.report.field.lead.lastname="联络人姓"
mautic.report.field.lead.mobile="联络人手机号"
mautic.report.field.lead.phone="联络人电话"
mautic.report.field.lead.position="联络人职位"
mautic.report.field.lead.state="联络人州"
mautic.report.field.lead.title="联络人头衔"
mautic.report.field.lead.zipcode="联系人邮政编码"
mautic.report.field.modified_by_user="上次修改者"
mautic.report.field.publish_down="设置为不可用"
mautic.report.field.publish_up="设置为可用"
mautic.report.field.source="初始来源"
mautic.report.field.source_id="初始来源 ID"
mautic.report.field.utm_campaign="UTM  推广活动"
mautic.report.field.utm_content="UTM 内容"
mautic.report.field.utm_medium="UTM  媒介"
mautic.report.field.utm_source="UTM 源"
mautic.report.field.utm_term="UTM 术语"
mautic.report.form.groupby="分组依据"
mautic.report.function="功能"
mautic.report.graph.bar="柱状图"
mautic.report.graph.line="线图"
mautic.report.graph.pie="饼图"
mautic.report.graph.table="表格"
mautic.report.is.scheduled="此报告计划通过电子邮件发送"
mautic.report.notfound="报告与ID %id% 没有找到"
mautic.report.permissions.header="报表授权"
mautic.report.permissions.reports="报表 - 用户有权访问"
mautic.report.report.form.choose_graphs="选择图表"
mautic.report.report.form.columnselector="列"
mautic.report.report.form.confirmbatchdelete="是否删除所选报告？这些报告的任何计划电子邮件都将停止。"
mautic.report.report.form.confirmdelete="删除报告，%name%？此报告的任何预定电子邮件都将停止。"
mautic.report.report.form.display.dynamic.filters.settings="动态过滤器设置"
mautic.report.report.form.display.graphs.above.table="在报表页上显示表数据上方的图形"
mautic.report.report.form.display.hide.date.ranges="隐藏日期范围"
mautic.report.report.form.display.show.dynamic.filters="默认开通"
mautic.report.report.form.displayBeforeTables="在表之前显示图形"
mautic.report.report.form.graphs="报表中包括的图表/表格"
mautic.report.report.form.issystem="对所有登录用户可见"
mautic.report.report.form.issystem.tooltip="将此设置为“否”将使其对您和具有查看其他用户报告权限的角色可见。"
mautic.report.report.form.owner="所有者"
mautic.report.report.form.source="数据源"
mautic.report.report.form.source.help="请为该报告选择数据源。修改该设置将清除您现有的列和过滤器设置。"
mautic.report.report.glue.choice.and="和"
mautic.report.report.glue.choice.or="或"
mautic.report.report.groupby.totals="共计"
mautic.report.report.header.edit="编辑报表 - %name%"
mautic.report.report.header.new="新建报表"
mautic.report.report.header.view="查看报表 - %name%"
mautic.report.report.label.addfilter="添加过滤器"
mautic.report.report.label.addtableorder="增加排序"
mautic.report.report.label.aggregators.avg="平均值"
mautic.report.report.label.aggregators.count="计数"
mautic.report.report.label.aggregators.max="最大值"
mautic.report.report.label.aggregators.min="最小值"
mautic.report.report.label.aggregators.sum="总和"
mautic.report.report.label.availablecolumns="可用列"
mautic.report.report.label.clonefilter="克隆过滤器"
mautic.report.report.label.filtercolumn="列"
mautic.report.report.label.filtercondition="条件"
mautic.report.report.label.filterdynamic="动态？"
mautic.report.report.label.filterdynamic_tooltip="若设置为是，则可在本报表的列表中采用过滤器来实现动态的过滤。"
mautic.report.report.label.filtervalue="值"
mautic.report.report.label.function="添加功能"
mautic.report.report.label.removefilter="拆下滤清器"
mautic.report.report.label.selectedcolumns="所选列"
mautic.report.report.label.tableorder_dir.asc="升序"
mautic.report.report.label.tableorder_dir.desc="降序"
mautic.report.report.menu.index="管理报表"
mautic.report.report.noresults="本报表无返回数据"
mautic.report.report.tooltip.selected.columns="本框中的列顺序将决定报表中的列顺序。请使用按钮来调整列顺序。"
mautic.report.reports="报表"
mautic.report.schedule.command.finished="调度程序已完成"
mautic.report.schedule.command.invalid_parameter="参数报告必须是数字"
mautic.report.schedule.day="On"
mautic.report.schedule.day.friday="星期五"
mautic.report.schedule.day.monday="星期一"
mautic.report.schedule.day.saturday="星期六"
mautic.report.schedule.day.sunday="星期日"
mautic.report.schedule.day.thursday="星期四"
mautic.report.schedule.day.tuesday="星期二"
mautic.report.schedule.day.wednesday="星期三"
mautic.report.schedule.day.week_days="工作日"
mautic.report.schedule.email.message="报告<a href=\"%link%\">%report_name%</a> 产生%date% 已附加。"
mautic.report.schedule.email.message_file_linked="点击此处下载报告：<a href=\"%link%\">%report_name%</a>."
mautic.report.schedule.email.message_file_not_attached="文件太大，无法通过电子邮件发送，请单击链接查看此报告：<a href=\"%link%\">%report_name%</a>."
mautic.report.schedule.email.subject="报告%report_name% - %date%."
mautic.report.schedule.every="每"
mautic.report.schedule.isScheduled="电子邮件报告"
mautic.report.schedule.month_frequency="上"
mautic.report.schedule.month_frequency.first="第一个"
mautic.report.schedule.month_frequency.last="上一个"
mautic.report.schedule.preview_data="将发送的日期报告示例："
mautic.report.schedule.toAddress.label="至"
mautic.report.schedule.toAddress.tooltip="用逗号分隔多个邮箱地址"
mautic.report.schedule.unit.day="日"
mautic.report.schedule.unit.month="月"
mautic.report.schedule.unit.now="现在"
mautic.report.schedule.unit.week="周"
mautic.report.tab.data="数据"
mautic.report.tab.graphs="图表"
mautic.report.tab.schedule="日程"
mautic.report.table.noresults="无结果。请修改您的过滤器。"
mautic.widget.report="报表图表"
