; YXHK versioned Simplified Chinese translations.
mautic.api.client.callback.notblank="回调 URI 为必填项。"
mautic.api.client.redirecturis.notblank="重定向 URI 为必填项。"
mautic.api.client.redirecturl.invalid="%url% 为无效的 URI。"
mautic.api.dependent.entity.delete.error="实体ID %id% 当前正由其他实体使用。请在尝试删除之前解决所有依赖关系。"
