; YXHK versioned Simplified Chinese translations.
mautic.campaign.notification.has.active="是否活跃通知"
mautic.campaign.notification.send_mobile_notification="发送移动通知"
mautic.campaign.notification.send_notification="发送通知"
mautic.channel.mobile_notification="移动推送通知"
mautic.config.tab.campaign_notification_config="活动通知设置"
mautic.config.tab.notification_config="通知设置"
mautic.config.tab.notificationconfig="网页提醒设置"
mautic.config.tab.webhook_notification_config="Webhook 通知设置"
mautic.core.config.header.campaign_notification_config.description="指定接收有关市场活动的通知和更新的人员。"
mautic.core.config.header.webhook_notification_config.description="定义与webhook相关的通知和警报的收件人。"
mautic.integration.form.feature.landing_page_enabled="在着陆页上启用"
mautic.integration.form.feature.mobile="移动应用程序的通知"
mautic.integration.form.feature.tracking_page_enabled="在已跟踪到的网页上启用"
mautic.integration.form.feature.welcome_notification_enabled="欢迎通知"
mautic.integration.form.features.landing_page_enabled.tooltip="在Mautic登录界面启用单信号"
mautic.integration.form.features.tracking_page_enabled.tooltip="在嵌入Mautic安装包中mtc.js的网页上启用单信号"
mautic.integration.form.platforms="支持移动推送的平台"
mautic.integration.form.platforms.android="安卓"
mautic.integration.form.platforms.error="如果启用了移动通知功能，则必须至少选择一个平台"
mautic.integration.form.platforms.ios="iOS"
mautic.integration.form.platforms.tooltip="选择OneSignal配置将支持的平台。仅选择您有应用程序并集成了OneSignal SDK的平台。"
mautic.mobile_notification.graph.line.stats="已发送移动通知"
mautic.mobile_notification.graph.line.stats.read="已阅读"
mautic.mobile_notification.graph.line.stats.sent="已发送"
mautic.mobile_notification.graph.pie.ignored.read.failed="忽略/读取/失败的移动通知"
mautic.mobile_notification.graph.pie.ignored.read.failed.ignored="已忽略"
mautic.mobile_notification.graph.pie.ignored.read.failed.read="已阅读"
mautic.mobile_notification.report.hits_count="点击数量"
mautic.mobile_notification.report.hits_ratio="点击比例"
mautic.mobile_notification.report.read_count="阅读数量"
mautic.mobile_notification.report.read_ratio="阅读比例"
mautic.mobile_notification.report.sent_count="发送数量"
mautic.mobile_notification.report.unique_hits_count="唯一的点击率"
mautic.mobile_notification.report.unique_ratio="唯一比率"
mautic.mobile_notification.stats.report.table="已发送移动通知"
mautic.mobile_notifications.report.stat.date_read="阅读日期"
mautic.mobile_notifications.report.stat.date_sent="发送日期"
mautic.notification.actions="通知操作"
mautic.notification.actions.mobile_tooltip="如果用户已启用移动通知，则在填写表单时向用户发送选定的移动通知。"
mautic.notification.actions.send_mobile_notification="发送移动通知"
mautic.notification.campaign.event.notification.has.active="是否活跃通知"
mautic.notification.campaign.event.notification.has.active.desc="检查联系人是否有活动通知。"
mautic.notification.campaign.failed.missing_entity="指定的 Web 通知实体不存在。"
mautic.notification.campaign.failed.not_contactable="销售线索在 Web 通知渠道上无法联络到。"
mautic.notification.campaign.failed.not_subscribed="联络人未注册到 Web 通知渠道。"
mautic.notification.campaign.failed.unpublished="指定的Web通知未发布。"
mautic.notification.campaign.send_mobile_notification="发送移动通知"
mautic.notification.campaign.send_mobile_notification.tooltip="如果联系人在您的应用程序中的移动设备上启用了通知，则向其发送移动通知。"
mautic.notification.campaign.send_notification="发送网页提醒"
mautic.notification.campaign.send_notification.tooltip="向联系人发送网页提醒"
mautic.notification.choose.notifications="请选择提醒发送用户"
mautic.notification.config.form.notification.app_id="OneSignal应用程序ID"
mautic.notification.config.form.notification.gcm_sender_id="共享推送信息密钥"
mautic.notification.config.form.notification.icon="网页提醒图标"
mautic.notification.config.form.notification.icon.tooltip="图标会显示在您的网页提醒的左侧。"
mautic.notification.config.form.notification.notification_safari_web_id="网页提醒提供者Safari Web ID"
mautic.notification.config.form.notification.notification_safari_web_id.tooltip="One Signal App 的 One Signal Safari Web ID "
mautic.notification.config.form.notification.rest_api_key="OneSignal Rest API密钥"
mautic.notification.config.form.notification.safari_web_id="safari网络ID"
mautic.notification.config.form.notification.trackinggpage.enabled.tooltip="在跟踪页上启用Web通知？"
mautic.notification.contentblock.copy="这些推送通知非常适合用于公告、警报和重新参与工作，可立即吸引注意力。"
mautic.notification.contentblock.heading="通过及时的Web推送恢复联系人"
mautic.notification.contentblock.subheading="及时将可点击的消息直接发送到联系人的桌面或移动的浏览器-即使他们不在您的网站上。"
mautic.notification.form.action.sendnotification.admin="向用户发送网页提醒"
mautic.notification.form.action.sendnotification.admin.descr="提交完成后，发送指定的网页提醒给指定的用户(用户组)。"
mautic.notification.form.action.sendnotification.lead="向联络人发送网页提醒"
mautic.notification.form.action.sendnotification.lead.descr="表单提交完成后，发送指定的Web通知给联络人。"
mautic.notification.form.body="正文"
mautic.notification.form.button="操作按钮文本"
mautic.notification.form.button.tooltip="为通知增加操作按钮 ( 限 Chrome )"
mautic.notification.form.config.notification_email_addresses="接收通知的电子邮件地址"
mautic.notification.form.config.notification_email_addresses.tooltip="添加用来接收通知的邮件地址列表，用逗号分隔"
mautic.notification.form.config.send_notification_to_author="向作者发送通知"
mautic.notification.form.config.send_notification_to_author.tooltip="向作者或其他用户的电子邮件地址发送通知。"
mautic.notification.form.confirmbatchdelete="删除所选的网页提醒？"
mautic.notification.form.confirmdelete="删除网页提醒，%name%?"
mautic.notification.form.confirmsend="队列，%name%，等待发送？"
mautic.notification.form.heading="标题"
mautic.notification.form.internal.description="描述"
mautic.notification.form.internal.name="名"
mautic.notification.form.list="联络人列表"
mautic.notification.form.message="信息"
mautic.notification.form.mobile.android_accent_color="强调色"
mautic.notification.form.mobile.android_accent_color.tooltip="设置显示在通知文本左侧的小图标周围的圆形颜色。使用ARGB十六进制值。占位符文本显示为红色。仅适用于针对运行在Android 5.0+设备上的Android API level 21+的应用程序。"
mautic.notification.form.mobile.android_big_picture="大图"
mautic.notification.form.mobile.android_big_picture.tooltip="需要Android 4.1+在通知文本下方的可扩展视图中显示。"
mautic.notification.form.mobile.android_group_key="组密钥"
mautic.notification.form.mobile.android_group_key.tooltip="具有相同组密钥的通知将作为单个摘要通知与未打开的通知数堆叠在一起。"
mautic.notification.form.mobile.android_large_icon="大图标"
mautic.notification.form.mobile.android_large_icon.tooltip="需要Android 3.0+。图标显示在通知文本的左侧。"
mautic.notification.form.mobile.android_led_color="LED颜色"
mautic.notification.form.mobile.android_led_color.tooltip="设置设备的LED通知灯（如果设备有）。使用ARGB十六进制值。显示的占位符文本为蓝色。"
mautic.notification.form.mobile.android_lockscreen_visibility="锁屏可见性"
mautic.notification.form.mobile.android_lockscreen_visibility.placeholder="公开"
mautic.notification.form.mobile.android_lockscreen_visibility.private="隐私"
mautic.notification.form.mobile.android_lockscreen_visibility.secret="隐秘性"
mautic.notification.form.mobile.android_lockscreen_visibility.tooltip="仅适用于针对运行在Android 5.0+设备上的Android API level 21+的应用程序。"
mautic.notification.form.mobile.android_small_icon="小图标"
mautic.notification.form.mobile.android_small_icon.tooltip="图标显示在状态栏中。也显示在通知文本的左侧，除非设置了大图标。"
mautic.notification.form.mobile.android_sound="声音"
mautic.notification.form.mobile.android_sound.tooltip="当设备收到通知时，声音资源将播放。"
mautic.notification.form.mobile.heading="称谓"
mautic.notification.form.mobile.ios_badgecount="徽章数量"
mautic.notification.form.mobile.ios_badgecount.tooltip="这将根据您以前的选择设置或增加徽章数量。"
mautic.notification.form.mobile.ios_badges="徽章"
mautic.notification.form.mobile.ios_badges.increment="增长为"
mautic.notification.form.mobile.ios_badges.placeholder="不要设置或修改"
mautic.notification.form.mobile.ios_badges.set="设置为"
mautic.notification.form.mobile.ios_badges.tooltip="主屏幕上应用程序图标上的小数字，表示收到的应用程序通知数。打开应用程序时清除。"
mautic.notification.form.mobile.ios_contentavailable="存在的内容"
mautic.notification.form.mobile.ios_contentavailable.tooltip="仅适用于本机iOS应用程序。收到通知时唤醒应用程序，以便您可以在后台工作。有关更多详细信息，请参阅苹果的“内容可用”文档。"
mautic.notification.form.mobile.ios_media="媒体"
mautic.notification.form.mobile.ios_media.tooltip="富媒体附件。3D触摸通知时显示的图像、声音或视频。需要OneSignal iOS 2.1.1 SDK或更新版本。"
mautic.notification.form.mobile.ios_mutablecontent="可变内容"
mautic.notification.form.mobile.ios_mutablecontent.tooltip="在iOS 10+上运行的纯本机代码。允许您在显示应用程序的通知之前对其进行修改。有关更多详细信息，请参阅苹果的“可变内容”文档。"
mautic.notification.form.mobile.ios_sound="提示音"
mautic.notification.form.mobile.ios_sound.tooltip="当设备收到通知时，将播放提示音文件。对于默认提示音，这应该留空，或者设置为应用程序包中声音文件的名称。"
mautic.notification.form.mobile.ios_subtitle="消息副标题"
mautic.notification.form.mobile.ios_subtitle.tooltip="这是iOS 10独有的功能"
mautic.notification.form.mobile.url="URL"
mautic.notification.form.mobile.url.tooltip="单击通知时打开URL。"
mautic.notification.form.subdomain_name.label="子域名"
mautic.notification.form.url="链接"
mautic.notification.form.url.tooltip="“ 在用户点击通知信息时要转发的目标链接 ”"
mautic.notification.header.edit="编辑网页提醒"
mautic.notification.header.new="新网页提醒"
mautic.notification.headings="网页提醒标题"
mautic.notification.headings.tooltip="您的网页提醒标题"
mautic.notification.link="链接"
mautic.notification.link.placeholder="网址：//"
mautic.notification.link.tooltip="当用户点击网页提醒时，您想将他们导向到何处？"
mautic.notification.mobile.contentblock.copy="这是推动功能采用、促进应用内操作以及保持用户与您的移动的应用互动的完美渠道。"
mautic.notification.mobile.contentblock.heading="在您的移动的应用程序中加深互动"
mautic.notification.mobile.contentblock.subheading="向已安装您的iOS/Android应用并选择接收推送通知的用户发送推送通知。"
mautic.notification.mobile.header.edit="编辑手机通知"
mautic.notification.mobile.header.new="新的手机通知"
mautic.notification.mobile_notification="移动通知"
mautic.notification.mobile_notification.header="移动通知"
mautic.notification.mobile_notification.header.preview="手机通知"
mautic.notification.mobile_notification.heading="称谓"
mautic.notification.mobile_notification.preview="预览通知"
mautic.notification.mobile_notifications="移动通知"
mautic.notification.notification="网页提醒"
mautic.notification.notification.header="网页提醒"
mautic.notification.notification.header.preview="网页提醒预览"
mautic.notification.notifications="网页提醒"
mautic.notification.permissions.header="推送通知权限"
mautic.notification.permissions.mobile_notifications="手机通知 - 用户有访问权限"
mautic.notification.permissions.notifications="Web通知-用户有权访问"
mautic.notification.preview="预览"
mautic.notification.preview.message="你有一条新留言"
mautic.notification.preview.more_notifications="2更多通知"
mautic.notification.preview.notification="通知"
mautic.notification.preview.source.example_com="example.com"
mautic.notification.preview.source.web_browser="Web浏览器"
mautic.notification.send.edit.notification="编辑提醒"
mautic.notification.send.new.notification="新提醒"
mautic.notification.send.preview.notification="预览提醒"
mautic.notification.send.selectnotifications="选择提醒"
mautic.notification.show.total.sent="发送总数"
mautic.notification.stat.leadcount="%count% 等待"
mautic.notification.stat.readcount="%count% 已读"
mautic.notification.stat.sentcount="%count% 已发送"
mautic.notification.stats="提醒数据"
mautic.notification.stats.report.table="提醒已发送"
mautic.notification.tab.android="安卓"
mautic.notification.tab.data="附加数据"
mautic.notification.tab.ios="iOS"
mautic.notification.tab.mobile="移动设置"
mautic.notification.text="网页提醒内容"
mautic.notification.text.tooltip="您的网页提醒内容"
mautic.notification.timeline.status="状态"
mautic.notification.timeline.status.delivered="已送达"
mautic.notification.timeline.status.failed="已失败"
mautic.notification.timeline.type="类型"
mautic.notification.type.header="您想创建何种提醒？"
mautic.notification.type.list="段"
mautic.notification.type.list.description="您可以手动将区段通知传送至选取的连络人区段。通知一旦传送后，就无法编辑。不过，当新连络人新增至相关区段时，您可以将通知传送至新连络人。"
mautic.notification.type.list.header="新段通知"
mautic.notification.type.template="触发式"
mautic.notification.type.template.description="触发的通知由市场活动、表单、点事件等自动发送。这些内容可以编辑，但不能发送到联系人细分市场。"
mautic.notification.type.template.header="新触发通知"
mautic.report.group.mobile_notifications="移动通知"
mautic.report.source.mobile_notifications="移动通知"
mautic.report.source.mobile_notifications.stats="已发送移动通知"
