; YXHK versioned Simplified Chinese translations.
mautic.config.tab.userconfig="用户/身份验证设置"
mautic.core.config.header.saml.description="使用SAML协议和身份提供者集成配置单点登录身份验证。"
mautic.role.role="作用"
mautic.user.account.accessibility="无障碍"
mautic.user.account.accessibility.appearance="外观"
mautic.user.account.accessibility.borders_disabled_description="无附加边框的默认外观"
mautic.user.account.accessibility.borders_enabled_description="可点击元素周围的强边框和焦点上的虚线轮廓样式"
mautic.user.account.accessibility.borders_outline_style="边框和轮廓样式"
mautic.user.account.accessibility.borders_outline_style_help="增强交互式元素的视觉提示，以改善导航和焦点。"
mautic.user.account.accessibility.content="内容"
mautic.user.account.accessibility.disabled="残疾"
mautic.user.account.accessibility.enabled="启用"
mautic.user.account.accessibility.link_underlines="链接下划线"
mautic.user.account.accessibility.link_underlines_help="在界面上切换链接上下划线的可见性。"
mautic.user.account.accessibility.normal="正常"
mautic.user.account.accessibility.reduce_transparency_blur="减少透明度和模糊"
mautic.user.account.accessibility.reduce_transparency_blur_help="调整透明度和模糊效果以提高可读性和视觉清晰度。"
mautic.user.account.accessibility.reduced="减少"
mautic.user.account.accessibility.smooth_color_transitions="平滑的颜色过渡"
mautic.user.account.accessibility.smooth_color_transitions_help="调整颜色变化的动画速度，以增强视觉舒适度并减少运动。"
mautic.user.account.accessibility.transitions_disabled_description="即时颜色变化，无动画"
mautic.user.account.accessibility.transitions_enabled_description="状态之间平滑、渐进的颜色过渡"
mautic.user.account.accessibility.transparency_normal_description="默认透明度和模糊效果"
mautic.user.account.accessibility.transparency_reduced_description="没有透明度和模糊"
mautic.user.account.accessibility.underlines_disabled_description="不带下划线的链接"
mautic.user.account.accessibility.underlines_enabled_description="链接上的下划线可见"
mautic.user.account.appearance="外观"
mautic.user.account.appearance.accent_colors="强调色"
mautic.user.account.appearance.accent_help="使Mautic 为不同的高光选择一种颜色。"
mautic.user.account.appearance.accent_toggletip.content="强调色仅适用于默认的浅色和深色主题，因为自定义主题可能设计为使用特定的配色方案。"
mautic.user.account.appearance.accent_toggletip.title="为什么我不能改变一些主题？"
mautic.user.account.appearance.theme_dark="黑暗"
mautic.user.account.appearance.theme_dark_description="黑暗主题，减少低光环境下的眼睛疲劳"
mautic.user.account.appearance.theme_freire="弗莱雷"
mautic.user.account.appearance.theme_freire_description="以社区为灵感的主题庆祝多样性和协作，Mautic 颜色"
mautic.user.account.appearance.theme_help="选择您喜欢的界面主题。"
mautic.user.account.appearance.theme_light="浅色（默认）"
mautic.user.account.appearance.theme_light_description="标准灯光主题，提供明亮、整洁的界面"
mautic.user.account.appearance.theme_preferences="主题首选项"
mautic.user.account.appearance.theme_preferences.popover.content="它们经过科学设计，使用平衡柔和的颜色，提高可见度和舒适度，特别是在长时间使用时，可减轻眼睛疲劳，使阅读更轻松。"
mautic.user.account.appearance.theme_preferences.popover.title="什么是日晒颜色主题？"
mautic.user.account.appearance.theme_solarized_dark="太阳光暗"
mautic.user.account.appearance.theme_solarized_dark_description="深色主题搭配精心挑选的色调，营造最佳对比度"
mautic.user.account.appearance.theme_solarized_light="太阳能灯"
mautic.user.account.appearance.theme_solarized_light_description="浅色主题搭配温暖柔和的色彩，让您轻松阅读"
mautic.user.account.header.authorizedclients="授权的应用"
mautic.user.account.header.details="账户的详细信息"
mautic.user.account.permissions.editall="所有"
mautic.user.account.permissions.editemail="电子邮件"
mautic.user.account.permissions.editname="名称"
mautic.user.account.permissions.editposition="位置"
mautic.user.account.permissions.editusername="用户名"
mautic.user.account.settings="账户"
mautic.user.auth.error.invalidlogin="登录无效。请验证凭据。"
mautic.user.auth.expired.header="登录-请登录"
mautic.user.auth.form.loginbtn="登录"
mautic.user.auth.form.loginusername="的用户名或电子邮箱"
mautic.user.auth.form.rememberme="让我保持登入"
mautic.user.auth.form.rolename="角色名称"
mautic.user.auth.header="请登录"
mautic.user.auth.logout="注销"
mautic.user.config.account.security.helper="调整您的凭据以确保您的帐户安全。"
mautic.user.config.form.saml.idp.attribute_email="电子邮件"
mautic.user.config.form.saml.idp.attribute_firstname="名字"
mautic.user.config.form.saml.idp.attribute_lastname="姓氏"
mautic.user.config.form.saml.idp.attribute_username="用户名（可选）"
mautic.user.config.form.saml.idp.default_role="已创建用户的默认角色"
mautic.user.config.form.saml.idp.default_role.tooltip="选择默认角色以分配新创建的用户。要禁用创建用户，请清除所选角色并保留为空。"
mautic.user.config.form.saml.idp.disable_creation="留空可禁用用户创建"
mautic.user.config.form.saml.idp.metadata="身份提供程序元数据文件"
mautic.user.config.form.saml.idp.metadata.tooltip="上载身份提供程序元数据XML 文件."
mautic.user.config.form.saml.idp.own_certificate="X.509证书"
mautic.user.config.form.saml.idp.own_certificate.description="使用自定义X.509证书和私钥来保护Mautic 和国内流离失所者。"
mautic.user.config.form.saml.idp.own_certificate.tooltip="上传自定义X.509证书以保护IDP与Mautic."
mautic.user.config.form.saml.idp.own_entity_id="实体ID"
mautic.user.config.form.saml.idp.own_password="私钥加密密码"
mautic.user.config.form.saml.idp.own_password.tooltip="如果私钥是用密码加密的，请在此处输入密码。"
mautic.user.config.form.saml.idp.own_private_key="私钥"
mautic.user.config.form.saml.idp.own_private_key.tooltip="上传证书的私钥，以保护IDP和Mautic."
mautic.user.config.form.saml.idp_attributes="输入配置的IDP用于以下操作的属性的名称Mautic 用户字段中。"
mautic.user.config.form.saml.idp_entity_id_label="实体ID 为国内流离失所者"
mautic.user.config.header.saml="SAML SSO设置"
mautic.user.config.personalize.interface.helper="管理用于个性化界面体验的详细信息。"
mautic.user.config.region.preferences.helper="设置与您所在地区相关的首选项。"
mautic.user.config.signature.admin.helper="使用|FROM_NAME| 以自动插入用户名。"
mautic.user.config.signature.helper="您可以使用|FROM_NAME| 变量，以自动插入发件人的姓名。"
mautic.user.config.title.account_data_security="账户数据和安全"
mautic.user.config.title.experience_and_learning="经验和学习"
mautic.user.config.title.experience_and_learning.description="定制您的旅程，充分利用您的体验。"
mautic.user.config.title.experience_and_learning.reset_dismissed="重新启动所有已关闭的提示"
mautic.user.config.title.get_to_know_you="让我们来了解你"
mautic.user.config.title.locale="区域设置"
mautic.user.config.title.personal_information="个人信息"
mautic.user.exception.user.not_found="无法通过用户名或电子邮件找到活动用户“%identifier%\"."
mautic.user.invite.collaborate.heading="与您的组织协作"
mautic.user.invite.collaborate.subheading="添加用户的电子邮件地址以发送邀请链接。"
mautic.user.invite.email.body="您已被邀请加入Mautic.单击以下链接创建您得帐户：%invite_link%"
mautic.user.invite.email.fallback="如果按钮不起作用，请在浏览器中打开此链接：%invite_link%"
mautic.user.invite.email.footer="此邀请的发送者Mautic."
mautic.user.invite.email.heading="您已被邀请加入Mautic"
mautic.user.invite.email.intro="使用下面的按钮创建您的帐户并开始与您的团队合作。"
mautic.user.invite.email.label="电子邮件地址"
mautic.user.invite.register="创建帐户"
mautic.user.invite.registration.database.error="用户邀请注册期间发生数据库错误"
mautic.user.invite.role.label="作用"
mautic.user.invite.role.placeholder="选择一个角色"
mautic.user.invite.send="发送邀请"
mautic.user.invite.subject="你被邀请加入Mautic"
mautic.user.invite.title="邀请用户"
mautic.user.lastlogin="上次登录"
mautic.user.password.reset.email.failed="密码重置电子邮件失败"
mautic.user.password.reset.token.creation.database.error="创建密码重置令牌期间发生数据库错误"
mautic.user.permissions.header="用户权限"
mautic.user.permissions.profile="配置文件-用户可以编辑"
mautic.user.permissions.roles="角色-用户有权访问"
mautic.user.permissions.users="用户-用户有权访问"
mautic.user.profile.invite="邀请您的团队"
mautic.user.role="作用"
mautic.user.role.clone.prefix="克隆%name%"
mautic.user.role.form.confirmbatchdelete="是否删除所选角色？"
mautic.user.role.form.confirmdelete="删除角色，%name%?"
mautic.user.role.form.isadmin="拥有完整的系统访问权限"
mautic.user.role.form.isadmin.tooltip="如果设置为“是”，则分配给此角色的任何用户都将拥有对所有区域的完全访问权限。如果设置为“否”，请通过“权限”选项卡配置权限。"
mautic.user.role.form.updated_by="更新了"
mautic.user.role.header.edit="角色-编辑%name%"
mautic.user.role.header.new="角色-新角色"
mautic.user.role.list.thead.usercount="用户计数"
mautic.user.role.list.viewusers_count="{0} 没有用户|{1} 查看1个用户|]1，Inf[查看%count% 用户"
mautic.user.role.permission.isadmin.header="允许完全访问"
mautic.user.role.permission.isadmin.message="角色设置为授予完全访问权限。若要调整个人权限，请在“详细信息”选项卡上禁用完全访问权限。"
mautic.user.role.permissions="权限"
mautic.user.role.usercount="此角色中的用户数"
mautic.user.roles="角色"
mautic.user.user.contact.locked="关于%entityName% - 解锁请求"
mautic.user.user.contact.message="消息"
mautic.user.user.contact.regarding="关于%entityName%"
mautic.user.user.contact.send="发送"
mautic.user.user.emailchange.email.body="嗨%name%,\\n\\n我们在此通知您，您的帐户电子邮件已更改。如果您启动了此更改，则无需执行任何其他操作。\\n\\n如果您没有更改您的电子邮件地址，请立即联系我们的技术支持团队。"
mautic.user.user.emailchange.subject="Mautic 电子邮件已更改"
mautic.user.user.filter.email="通过电子邮件"
mautic.user.user.filter.name="按名称"
mautic.user.user.filter.role="按角色"
mautic.user.user.filter.username="通过用户名"
mautic.user.user.form.confirmbatchdelete="是否删除所选用户？分配给他们的联系人和公司将变为未分配状态，API 将删除访问令牌和预设联系人导出。"
mautic.user.user.form.confirmdelete="删除的帐户%name%？分配给此用户的联系人和公司将变为未分配，并且用户的API 将删除访问令牌和预设联系人导出。"
mautic.user.user.form.created_by="是由"
mautic.user.user.form.defaultlocale="系统默认区域设置"
mautic.user.user.form.defaulttimezone="系统默认时区"
mautic.user.user.form.help.passwordrequirements="密码至少需要6位。允许使用纯数字密码，但请避免明显的重复或连续数字组合；较长且独特的密码更安全。"
mautic.user.user.form.login_by="登录"
mautic.user.user.form.passwordconfirm="确认密码"
mautic.user.user.form.passwordplaceholder="留空不作更改"
mautic.user.user.form.update_update="更新"
mautic.user.user.form.update_user_status="信息"
mautic.user.user.form.updated_by="更新"
mautic.user.user.form.user="用户"
mautic.user.user.header.contact="留言给%name%"
mautic.user.user.header.edit="用户-编辑%name%"
mautic.user.user.header.new="用户-新用户"
mautic.user.user.help.searchcommands="<strong>搜索命令</strong><br />id：ID 1，ID 2（逗号分隔的ID，没有空格）<br />是：admin<br />是：活跃<br />是：不活动<br />电邮地址：*<br />联系人：*<br />职位：*<br />职位：*<br />用户名：*"
mautic.user.user.passwordchange.email.body="嗨%name%,\\n我们在此通知您，您的帐户密码已更改。如果您启动了此更改，则不需要执行任何其他操作。\\n如果您没有更改密码，请立即联系我们的技术支持团队。"
mautic.user.user.passwordchange.subject="Mautic 更改密码"
mautic.user.user.passwordreset.back="返回登录"
mautic.user.user.passwordreset.body="嗨%name%,\\n\\n您的新密码\\n%password%\\n\\n建议您立即登录并更改。"
mautic.user.user.passwordreset.confirm.placeholder="确认密码"
mautic.user.user.passwordreset.email.body="嗨%name%,\\n\\n您请求了密码重置。请单击下面的链接重置您的密码。\\n\\n%resetlink%"
mautic.user.user.passwordreset.info="请输入您的用户名或电子邮件地址以重置您的密码。重置密码的说明将发送到您的个人资料中的电子邮件。"
mautic.user.user.passwordreset.link="忘记密码？"
mautic.user.user.passwordreset.password.placeholder="密码"
mautic.user.user.passwordreset.reset="重置密码"
mautic.user.user.passwordreset.subject="Mautic 密码重置"
mautic.user.user.passwordresetconfirm.info="请输入您的用户名或电子邮件地址以及您的新密码以完成重置过程。"
mautic.user.user.searchcommand.isadmin="is:admin"
mautic.user.user.searchcommand.isadmin.description="具有管理权限的用户的筛选器"
mautic.user.user.searchcommand.position="position"
mautic.user.user.searchcommand.position.description="按用户在组织中的职位筛选用户"
mautic.user.user.searchcommand.role="role"
mautic.user.user.searchcommand.role.description="按分配的角色筛选用户"
mautic.user.user.searchcommand.username="username"
mautic.user.user.searchcommand.username.description="按用户名搜索用户"
mautic.user.users="用户"
mautic.user_management="用户管理"
