; YXHK versioned Simplified Chinese translations.
mautic.user.entity.must.be.user="实体必须属于User（）类"
mautic.user.invite.error.email_invalid="请输入有效的电子邮件地址。"
mautic.user.invite.error.email_required="电子邮件地址是必需的。"
mautic.user.invite.error.invalid_role="为邀请选择的角色无效。"
mautic.user.invite.error.role_required="必须为被邀请的用户选择角色。"
mautic.user.saml.certificate.invalid="证书无效。它应以开始<pre>- 开始证书-</pre>."
mautic.user.saml.metadata.invalid="元数据文件已失效。"
mautic.user.saml.private_key.invalid="私钥无效。它应该开始<pre>- 开始RSA私钥-</pre> 或<pre>- 开始加密私钥-</pre>."
mautic.user.saml.private_key.password_invalid="密码无法解密私钥。"
mautic.user.saml.private_key.password_needed="提供的私钥是加密的，因此需要密码才能解密。"
mautic.user.user.email.unique="该邮件地址已经被使用。请选择其它邮件地址。"
mautic.user.user.email.valid="您输入的邮件地址无效。"
mautic.user.user.firstname.notblank="名为必填项。"
mautic.user.user.lastname.notblank="姓为必填项。"
mautic.user.user.password.minlength="密码最少为 6 个字符。"
mautic.user.user.password.mismatch="密码不匹配。"
mautic.user.user.password.notblank="密码不能为空。"
mautic.user.user.password.weak="请输入更强的密码。您的密码必须使用大小写、特殊字符和数字的组合。"
mautic.user.user.passwordreset.notblank="需要您的用户名或邮件地址来重设密码。"
mautic.user.user.position.toolong="位置不能超过191个字符。"
mautic.user.user.role.notblank="必须为该用户选择一个角色。"
mautic.user.user.username.notblank="用户名为必填项。"
mautic.user.user.username.unique="该用户名已经被使用。请选择其它用户名。"
