; YXHK versioned Simplified Chinese translations.
mautic.campaign.page.devicehit="装置击中"
mautic.campaign.page.pagehit="页面点击"
mautic.campaign.tracking.pixel.send="发送追踪事件"
mautic.config.tab.pageconfig="着陆页设置"
mautic.config.tab.pagetracking="Mautic 跟踪设置"
mautic.config.tab.pagetracking.info="选择适当的脚本，并将其插入到网页结束之前，<code>&lt;/body&gt;</code> 标签Mautic 登录页会自动跟踪。请仅在第三方网站上使用这些脚本。"
mautic.config.tab.pixels.event.in.campaign="启用第3方活动行动"
mautic.config.tab.tracking.facebook.pixel="Facebook像素"
mautic.config.tab.tracking.google.analytics="Google分析"
mautic.config.tab.trackingconfig="追踪设置"
mautic.core.config.header.pageconfig.description="配置URL 结构和跟踪选项。"
mautic.core.config.header.pagetracking.description="配置网站跟踪、分析集成和访问者识别方法。"
mautic.core.config.header.tracking.facebook.pixel.description="设立Facebook 像素跟踪，以监控整个页面的访问者交互。"
mautic.core.config.header.tracking.google.analytics.description="使Google 用于衡量网站性能和访问者行为的分析跟踪。"
mautic.email.form.preference_center="偏好中心页面"
mautic.email.form.preference_center.tooltip="如果用户通过此邮件访问所选页面，则其显示页面将呈现偏好中心"
mautic.maintenance.lead_utmtags="UTM 标签历史"
mautic.maintenance.page_hits="访客页面点击"
mautic.page.abtest.criteria="着陆页数据"
mautic.page.abtest.criteria.bounce="最低弹出率"
mautic.page.abtest.criteria.dwelltime="最大停留时间"
mautic.page.abtest.label.bounces="弹出率"
mautic.page.abtest.label.dewlltime.average="平台停留时间(时长)"
mautic.page.builder.addcontent="点击以添加内容"
mautic.page.builder.externallink="外链"
mautic.page.campaign.condition.form.enddate="结束日期"
mautic.page.campaign.condition.form.page="着陆页"
mautic.page.campaign.condition.form.page.descr="选择此触发器应用到的页面。如果未选择任何页面，则它将应用到任何页面。"
mautic.page.campaign.condition.form.startdate="开始日期"
mautic.page.campaign.condition.form.timespent="所用时间（秒）"
mautic.page.campaign.event.devicehit="设备访问"
mautic.page.campaign.event.devicehit_descr="在点击页面或者URL时触发设备"
mautic.page.campaign.event.form.pages="仅限页面"
mautic.page.campaign.event.form.pages.descr="选择本触发器适用的着陆页。若未选择任何项，则适用于所有着陆页。"
mautic.page.campaign.event.form.referer="转发者"
mautic.page.campaign.event.form.referer.descr="插入引用站点URL 放置追踪像素的页面。纯文字会符合URL，例如product/123匹配http://web.com/product/1234.htm. 仍支持传统通配符模式，如 *product/123*。多个引用站点URL之间用逗号分隔。"
mautic.page.campaign.event.form.url="URL"
mautic.page.campaign.event.form.url.descr="插入URL 放置追踪像素的页面。纯文字会符合URL，例如product/123匹配http://web.com/product/1234.htm. 仍支持旧的通配符模式，如 *product/123*。请用逗号分隔多个URL。"
mautic.page.campaign.event.pagehit="访问一个着陆页"
mautic.page.campaign.event.pagehit_descr="页面/url 点击后触发操作。"
mautic.page.config.form.anonymize_ip="匿名IP"
mautic.page.config.form.anonymize_ip.tooltip="访问者的IP 将不会存储在任何地方。"
mautic.page.config.form.anonymize_ip.warning="现有数据将被匿名化。此操作不可逆"
mautic.page.config.form.append_segment_id_tracking_url="将段ID附加到跟踪URL"
mautic.page.config.form.append_segment_id_tracking_url.tooltip="启用后，联系人细分ID将作为查询参数（segment_ids= 1，2，3）附加到重定向URL。这允许VWO等第三方工具识别细分成员身份，以进行个性化内容交付。"
mautic.page.config.form.cat.in.url="在页面 URL 中显示类别？"
mautic.page.config.form.cat.in.url.tooltip="启用后，类别标志会被包括在 URL中。"
mautic.page.config.form.do_not_track_404_anonymous="404错误提示-匿名联系人"
mautic.page.config.form.do_not_track_404_anonymous.tooltip="如果启用此选项，则不会跟踪对404响应代码错误页面的未识别访问。此选项有助于防止机器人跟踪。"
mautic.page.config.form.event.google.analytics.enabled="Google分析事件"
mautic.page.config.form.facebook.pixel.id="Facebook像素ID"
mautic.page.config.form.google.analytics="分析脚本  (如： Google Analytics)"
mautic.page.config.form.google.analytics.id="Google分析ID"
mautic.page.config.form.google.analytics.tooltip="插入分析脚本，让其自动包含在着陆页的源代码中。"
mautic.page.config.form.pixel.campaign.enabled="启用‘发送第3方像素’的活动行动"
mautic.page.config.form.track_contact_by_ip="通过IP辨别访问者"
mautic.page.config.form.track_contact_by_ip.tooltip="启用后，使用与现有联络人同样 IP 地址的未识别访问者，会被当作现有联络人进行跟踪。"
mautic.page.config.form.tracking.anonymize.ip.enabled="启用IP匿名"
mautic.page.config.form.tracking.anonymize.ip.enabled.tooltip="在一些情况下，你可能需要将Google分析的点击的IP地址进匿名化处理"
mautic.page.config.form.tracking.landingpage.enabled="在Mautic登陆页面上启用"
mautic.page.config.form.tracking.trackingpage.enabled="在你的追踪页面上启用"
mautic.page.config.no_index="禁用搜索索引"
mautic.page.config.tracking.script.consent.description="在同意之前加载基本脚本，然后配置您的同意管理器，使其仅在访问者同意后运行跟踪加载项。"
mautic.page.config.tracking.script.consent.focus_notice="单独嵌入的焦点项跟踪视图和交互，Mautic 网站跟踪。仅加载基本脚本不会禁用焦点项目跟踪。"
mautic.page.config.tracking.script.consent.tab="同意管理"
mautic.page.config.tracking.script.essential.description="将此代码段放在页面上以加载EssentialMautic 功能，而不需要访问者跟踪。"
mautic.page.config.tracking.script.essential.label="基本脚本（知情同意前）"
mautic.page.config.tracking.script.full.description="仅在获得跟踪同意后或不需要同意的情况下使用此加载程序。它首先加载基本脚本，然后加载跟踪加载项。"
mautic.page.config.tracking.script.full.tab="全程跟踪"
mautic.page.config.tracking.script.tracking.description="在访问者同意后，从您的同意管理器的回调中运行此完整片段。它会等待基本运行时并对初始页面视图进行排队。"
mautic.page.config.tracking.script.tracking.label="跟踪附加组件（知情同意后）"
mautic.page.contentblock.heading="设计和发布高转化率的着陆页"
mautic.page.contentblock.subheading="Pages提供了一个专注的环境，旨在推动特定的操作，同时与您的自动化工作流和跟踪完全集成。"
mautic.page.dashboard.widgets="页面组件"
mautic.page.event.hit="页面点击"
mautic.page.event.publish.down="设置%page% 为不可用"
mautic.page.event.publish.down.description="佩奇%page%'将无法使用。"
mautic.page.event.publish.up="设置%page% 按可得到"
mautic.page.event.publish.up.description="佩奇%page%“马上就要变成可用的了。"
mautic.page.event.videohit="视频查看事件"
mautic.page.field.hits="点击数"
mautic.page.field.unique_hits="独立点击数"
mautic.page.form.categorylist="分类表单"
mautic.page.form.channelfrequency="渠道使用频率"
mautic.page.form.confirmbatchdelete="删除所选的页面? 警告 - 这将删除所有相关的A/B测试和翻译!"
mautic.page.form.confirmdelete="删除页面， %name%? 警告 - 这将删除所有相关的A/B测试和翻译!"
mautic.page.form.customhtml="定制 HTML 内容"
mautic.page.form.customhtml.help="使用定制化 HTML 设计整个着陆页"
mautic.page.form.footerscript="页脚中的脚本"
mautic.page.form.has_variants="有变体"
mautic.page.form.headscript="头部内的脚本"
mautic.page.form.language.help="通过设定一个父页面，将内容翻译成不同语言，并将其链接到一起。语言选项将在相关的着陆页中可用，以便用户选择他们希望的语言。"
mautic.page.form.leadidentifier="潜在客户标识符"
mautic.page.form.metadescription="资源描述"
mautic.page.form.preference_center="设置为首选项中心页面"
mautic.page.form.preference_center.tooltip="如果选择此选项，则该页面将被标记为首选项中心登录页。Mautic 电子邮件，收件人将在点击<strong><code>{unsubscribe_url}</code></strong> 链接."
mautic.page.form.preferredchannel="偏好渠道"
mautic.page.form.redirecttype="重定向类型"
mautic.page.form.redirecttype.303_temporary="303临时"
mautic.page.form.redirecttype.307_temporary="307 临时重定向"
mautic.page.form.redirecttype.308_permanent="308 永久重定向"
mautic.page.form.redirecttype.help="重选择重定向类型 (301 永久, 302 临时, 无)"
mautic.page.form.redirecttype.none="无重定向"
mautic.page.form.redirecttype.permanent="301 永久"
mautic.page.form.redirecttype.temporary="302 临时"
mautic.page.form.redirecturl="URL 重定向"
mautic.page.form.redirecturl.help="显示当一个页面被取消发布时要显示的  URL。可以输入定制的 URL，可选择已经发布的个人着陆页。"
mautic.page.form.saveprefs="保存偏好"
mautic.page.form.script.help="请确保附上您的脚本内<&#8239;script&#8239;> 标签，以防止它在网页上显示为文字，而非执行。"
mautic.page.form.segmentlist="分区表单"
mautic.page.form.successmessage="成功讯息"
mautic.page.form.template.help="请选择着陆页要使用的主题，这将决定其外观和感觉。然后您可以使用页面生成器来定义其内容。警告：若两个主题使用了不同的组成模块，则在生成而面后修改其主题可能使内容无法正确显示。"
mautic.page.graph.line.hits="页面点击"
mautic.page.graph.line.time.on.site="平均站点停留秒数"
mautic.page.graph.pie.devices="设备粒度"
mautic.page.graph.pie.languages="页面语言"
mautic.page.graph.pie.new.vs.returning="首次 & 重复访客"
mautic.page.graph.pie.new.vs.returning.new="新建"
mautic.page.graph.pie.new.vs.returning.returning="重复访客"
mautic.page.graph.pie.time.on.site="网站停留时间"
mautic.page.header.edit="编辑页面 - %name%"
mautic.page.header.new="新建页面"
mautic.page.help.alias="字母和数字（允许连字符）用于URL 生成此登录页。如果留空，将自动生成基于标题的唯一别名。"
mautic.page.help.searchcommands="<strong>搜索命令</strong><br />id：ID 1，ID 2（逗号分隔的ID，没有空格）<br />出版：Published<br />是：未发表<br />是：过期<br />是：待定<br />是：我的<br />是：未分类<br />是：prefcenter<br />类别：{category alias}<br />lang：{lang code}<br />项目：“项目名称”"
mautic.page.hits="页面点击"
mautic.page.menu.edit="编辑页面"
mautic.page.menu.view="查看页面"
mautic.page.page="着陆页"
mautic.page.pages="着陆页"
mautic.page.pageviews="页面浏览量"
mautic.page.permissions.header="着陆页授权"
mautic.page.permissions.pages="着陆页 - 用户可访问"
mautic.page.permissions.preference_center="偏好中心页面-用户可以访问"
mautic.page.point.action="着陆页操作"
mautic.page.point.action.form.accumulative.time="总花费时间"
mautic.page.point.action.form.accumulative.time.descr="根据多次访问过程中，在整个站点上花费的总访问时间来修改分值。"
mautic.page.point.action.form.first.time.only="限首次访问"
mautic.page.point.action.form.first.time.only.descr="联系人可能会多次访问某个 URL。请确定是否每次都要修改其积分，或只在首次访问时修改其积分。"
mautic.page.point.action.form.page.hits.descr="根据联系人访问页面的次数，修改积分。"
mautic.page.point.action.form.page.url="页面 URL"
mautic.page.point.action.form.page.url.descr="插入URL 放置追踪像素的页面。纯文字会符合URL，例如product/123匹配http://yourweb.com/product/1234. 仍支持传统通配符模式，如 *product/123*。"
mautic.page.point.action.form.pages="仅限所选着陆页"
mautic.page.point.action.form.pages.descr="选择本操作适用的着陆页。若未选择任何项，则适用于所有着陆页。"
mautic.page.point.action.form.returns.after="... 时间后返回"
mautic.page.point.action.form.returns.after.descr="根据联系人 <em>在指定时间后</em>返回到 URL 的次数，修改其积分。 "
mautic.page.point.action.form.returns.within="返回区间"
mautic.page.point.action.form.returns.within.descr="根据联系人 <em>在指定时间内</em>返回到 URL 的次数，修改其积分。 "
mautic.page.point.action.pagehit="访问一个着陆页"
mautic.page.point.action.pagehit_descr="联系人访问某个着陆页后，修改其积分。"
mautic.page.point.action.urlhit="访问特定的 URL"
mautic.page.point.action.urlhit_descr="联系人访问某个被跟踪的 URL 后，更新其积分。 "
mautic.page.preview.show.contact="显示联系人预览"
mautic.page.preview.url="预览URL"
mautic.page.publish.down="设置为不可用"
mautic.page.publish.up="设置为可用"
mautic.page.referrer="转发者"
mautic.page.report.hits.browser_languages="点击浏览器语言"
mautic.page.report.hits.city="点击城市"
mautic.page.report.hits.code="点击代码"
mautic.page.report.hits.country="点击国家"
mautic.page.report.hits.date_hit="日点击量"
mautic.page.report.hits.date_left="剩余天数"
mautic.page.report.hits.device="设备"
mautic.page.report.hits.duration="为期时间"
mautic.page.report.hits.email_id="邮件 ID"
mautic.page.report.hits.email_subject="邮件主题"
mautic.page.report.hits.id="页面命中ID"
mautic.page.report.hits.isp="点击 ISP"
mautic.page.report.hits.organization="点击组织"
mautic.page.report.hits.redirect_hit_count="重定制点击计数"
mautic.page.report.hits.redirect_unique_hits="重定向独立点击计数"
mautic.page.report.hits.redirect_url="重定向 URL"
mautic.page.report.hits.referer="点击转发者"
mautic.page.report.hits.region="点击地区"
mautic.page.report.hits.remote_host="点击远程主机"
mautic.page.report.hits.time_spent="花费的时间"
mautic.page.report.hits.time_watched="观看的时间"
mautic.page.report.hits.url="点击 URL"
mautic.page.report.hits.url_title="点击页标题"
mautic.page.report.hits.user_agent="点击用户代理"
mautic.page.report.revision="修改"
mautic.page.report.translation_parent_id="上级翻译 ID"
mautic.page.report.translation_parent_title="无上级翻译名"
mautic.page.report.variant_hits="A/B 测试点击量"
mautic.page.report.variant_parent_id=" A/B 测试上级项目 ID"
mautic.page.report.variant_parent_title=" A/B 测试上级项目标题"
mautic.page.report.variant_start_date=" A/B 测试开始日期"
mautic.page.result.header.index=" %name% 的结果集"
mautic.page.results.view="查看页面结果"
mautic.page.results.view.description="访问已提交Mautic 此页面表单数据"
mautic.page.searchcommand.isexpired="is:expired"
mautic.page.searchcommand.isexpired.description="筛选已过期的页面"
mautic.page.searchcommand.ispending="is:pending"
mautic.page.searchcommand.ispending.description="筛选计划将来可用的页面"
mautic.page.searchcommand.isprefcenter="是：prefcenter"
mautic.page.searchcommand.isprefcenter.description="指定为首选项中心的页面的筛选器"
mautic.page.show.total.visits="总访问量"
mautic.page.show.unique.and.total.visits="总访问量和唯一访问量"
mautic.page.show.unique.visits="唯一访问量"
mautic.page.stage.action="页面操作"
mautic.page.stage.action.pagehit="访问一个着陆页"
mautic.page.stage.action.urlhit="访问 URL"
mautic.page.table.most.visited="最多访问"
mautic.page.table.most.visited.unique="最多独立访问"
mautic.page.table.referrers="最多转发"
mautic.page.thead.hits="点击量"
mautic.page.time.on.page="页面停留时间"
mautic.page.time.on.video="总观看时间"
mautic.page.time.on.video.value="观看次数：%time_watched% 持续时间： %duration% (%percentage%%)"
mautic.page.token.dwc="DWC"
mautic.page.token.lang="语言栏"
mautic.page.token.lang.descr="若页面有多个翻译版本，则插入一个语言选择栏。"
mautic.page.token.pagelink="页面链接"
mautic.page.token.share="分享按钮"
mautic.page.token.share.descr="请在社交网络设置中插入分享按钮"
mautic.page.token.thispage="此页面"
mautic.page.tokens.header="令牌"
mautic.page.tokens.help="令牌是特定对象的占位符。您可以通过拖拽方式将其添加到编辑器中！"
mautic.page.tracking.form.action="操作"
mautic.page.tracking.form.category="类别"
mautic.page.tracking.form.category.tooltip="仅限Google分析"
mautic.page.tracking.form.label="标签"
mautic.page.tracking.form.services="服务"
mautic.page.tracking.pixel.event.send="发送追踪事件"
mautic.page.tracking.pixel.event.send_desc="发送自定义追踪Google Analytics或Facebook Pixel的事件"
mautic.page.unique="唯一的"
mautic.page.url="页面 URL"
mautic.page.visit.flag.filter="访问状态"
mautic.page.webhook.event.hit="页面点击事件"
mautic.placeholder_tokens.landing_page.language_bar="语言栏"
mautic.placeholder_tokens.landing_page.meta_description="Meta描述"
mautic.placeholder_tokens.landing_page.share_buttons="分享按钮"
mautic.placeholder_tokens.landing_page.success_message="成功消息"
mautic.placeholder_tokens.landing_page.title="称谓"
mautic.placeholder_tokens.landing_page_tokens="登陆页面"
mautic.placeholder_tokens.landing_page_tokens.explanation="自定义着陆页构建器中的内容。"
mautic.placeholder_tokens.preference_center.category_list="分类表单"
mautic.placeholder_tokens.preference_center.channel_frequency="渠道使用频率"
mautic.placeholder_tokens.preference_center.lead_identifier="潜在客户标识符"
mautic.placeholder_tokens.preference_center.preferred_channel="偏好渠道"
mautic.placeholder_tokens.preference_center.save_preferences="保存首选项按钮"
mautic.placeholder_tokens.preference_center.segment_list="分区表单"
mautic.placeholder_tokens.preference_center_tokens="首选项中心登录页面"
mautic.project.page="着陆页"
mautic.protip.pages.forms="把表单放在显眼的位置，这样用户就不必滚动页面来找到它们。"
mautic.protip.pages.mobile="优化您的网站，以实现移动优先，因为现在大多数网络流量都来自移动的设备"
mautic.report.group.pages="页面"
mautic.report.group.videos="视频"
mautic.report.source.focus_stats="聚焦数据"
mautic.report.source.page.hits="页面点击"
mautic.report.source.pages="着陆页"
mautic.report.source.video.hits="视频点击"
mautic.trackable.click_conversion_rate="转化率"
mautic.trackable.click_count="点击"
mautic.trackable.click_counts="点击计数"
mautic.trackable.click_counts.header_none="未找到可跟踪的链接"
mautic.trackable.click_counts.none="本渠道目前没有被跟踪的 URL。有可能该渠道尚未被发送，或没有 URL。"
mautic.trackable.click_track_id="跟踪 ID"
mautic.trackable.click_unique_count="独立点击"
mautic.trackable.click_url="URL"
mautic.trackable.total_clicks="总点击量"
mautic.trackable.total_conversion_rate_tooltip="点击至少一个链接的联系人数量/唯一视图总数"
mautic.video.hits="视频点击"
mautic.video.url="视频 URL"
mautic.widget.created.pages="创建着陆页"
mautic.widget.dwell.times="停留时间"
mautic.widget.page.hits.in.time="页面访问次数"
mautic.widget.popular.pages="最受欢迎的着陆页"
mautic.widget.unique.vs.returning.leads="唯一访问 & 重复访问"
