; YXHK versioned Simplified Chinese translations.
grapesjsbuilder.assetManager.noAssets="没有<b>资产</b> 在此处，放置要上载文件"
grapesjsbuilder.blocks.typography.h1="H1"
grapesjsbuilder.blocks.typography.h2="H2"
grapesjsbuilder.blocks.typography.h3="H3"
grapesjsbuilder.blocks.typography.h4="H4"
grapesjsbuilder.blocks.typography.subtitle="字幕"
grapesjsbuilder.builder.warning.code_mode="通过打开生成器，您将离开代码模式。生成器可能会更改您的HTML 代码。只有在您知道自己在做什么的情况下才能继续。"
grapesjsbuilder.buttonBlockLabel="按钮"
grapesjsbuilder.buttons.buttonPreview.title="预览"
grapesjsbuilder.buttons.buttonPreview.titleDisabled="将更改应用于预览"
grapesjsbuilder.categoryBlockLabel="块"
grapesjsbuilder.categorySectionLabel="布局区块"
grapesjsbuilder.categoryTypographyLabel="排版"
grapesjsbuilder.components.names.gridItemsBlkLabel="网格项"
grapesjsbuilder.components.names.listItemsBlkLabel="列表项"
grapesjsbuilder.components.names.oneColumn="1列"
grapesjsbuilder.components.names.textSectionBlkLabel="文本部分"
grapesjsbuilder.components.names.threeColumn="3列"
grapesjsbuilder.components.names.twoColumn="2列"
grapesjsbuilder.components.names.twoColumnThirdSevens="2列3/7"
grapesjsbuilder.deleteAssetConfirmText="您确定要删除此档案吗？"
grapesjsbuilder.dynamicContentBlockLabel="动态内容"
grapesjsbuilder.dynamicContentBtnLabel="保存"
grapesjsbuilder.dynamicContentModalTitle="编辑动态内容"
grapesjsbuilder.panelsViewsButtonsApplyTitle="应用更改"
grapesjsbuilder.panelsViewsCommandModalTitleError="无法请求您的操作"
grapesjsbuilder.secondaryButtonBlockLabel="辅助按钮"
grapesjsbuilder.sourceCancelBtnLabel="取消"
grapesjsbuilder.sourceEditBtnLabel="保存"
grapesjsbuilder.sourceEditModalTitle="编辑代码"
grapesjsbuilder.sourceSyntaxError="请修复以下错误："
