; YXHK versioned Simplified Chinese translations.
mautic.category.contentblock.copy="类别作为高级标签，帮助您识别相关项目，使其更易于区分和报告。联系人还可以在首选项中心按类别选择他们的兴趣。"
mautic.category.contentblock.heading="为您的资源带来秩序"
mautic.category.contentblock.subheading="为您的广告系列、电子邮件、资产和其他元素添加清晰度和分类。"
mautic.category.createnew="创建新类别 ..."
mautic.category.form.alias.help="字母和数字（允许连字符）用于URL 此类别的生成。如果留空，将自动生成基于标题的唯一别名。"
mautic.category.form.confirmbatchdelete="删除所选的类别？相关的项目不会被删除，但将被设置为未分类。"
mautic.category.form.confirmdelete="删除类别，%name%？关联项目不会被删除;它们将被指定为未分类。"
mautic.category.global="全局"
mautic.category.header.edit="编辑 %type% 分类 - %name%"
mautic.category.header.index="类别"
mautic.category.header.new="新类别"
mautic.category.menu.index="类别"
mautic.category.noresults.tip="类别有助于不同项目的归类和组织。在很多过滤器中，可以输入类别：{alias} (replace {alias} with the real deal) 来显示特定类别中的项目。"
mautic.category.permissions.categories="类别 - 用户可访问"
mautic.category.permissions.header="分类权限"
mautic.form.field.asset.use_category="使用类别中的最后一个资产<strong>%category_name%</strong>"
mautic.global.global="全局"
