; YXHK versioned Simplified Chinese translations.
mautic.company.batch_companies_affected="{0} 0 公司受影响|{1} 1 公司受影响|]1,Inf[ %count% 公司受影响"
mautic.company.error.notfound="未找到公司。"
mautic.company.notice.batch_deleted="{0} 0 个公司被删除|{1} 1 个公司被删除|]1,Inf[ %count% 个公司被删除"
mautic.company.notice.merged="%secondary% 合并为%primary%"
mautic.email.batch_emails_affected="{0} 0封电子邮件受影响|{1} 1封电子邮件受影响|]1，Inf[%count% 受影响的电子邮件"
mautic.import.file.missing="文件系统中找不到文件 '%file%'。请重试。"
mautic.lead.batch.import.created="导入进程成功创建。操作完成后您将收到相应的通知。"
mautic.lead.batch.import.created.unpublished="已成功创建导入进程。但由于您没有发布权限，因此不会处理该进程。"
mautic.lead.batch_leads_affected="{0} 0 联络人受影响。|{1} 1 联络人受影响|]1,Inf[ %count% 联络人受影响 "
mautic.lead.email.error.failed="未能成功发送到 %email%: %error%"
mautic.lead.email.notice.sent="&quot;%subject%&quot; 已发送到 %email%"
mautic.lead.event.donotcontact_channel_contactable="联系人现在可以在%channel% 频道"
mautic.lead.export.being.prepared="文件已排队等待处理。文件将发送到您的电子邮件地址'%user_email%'。您可以从电子邮件中提供的链接下载该文件。"
mautic.lead.export.limit.exceeded="超出导出限制。您正在尝试导出%total% 联系人，但限制设置为%limit% 联系人。请细化筛选条件以减少联系人的数量。"
mautic.lead.field.error.notfound="未找到序号为 %id% 的字段！"
mautic.lead.field.notice.batch_deleted="%count% 字段已经被删除！"
mautic.lead.lead.error.notfound="未找到 id 号为 %id% 的联络人！"
mautic.lead.lead.notice.addedtolists="<a href='%url%' data-toggle='ajax' data-menu-link='mautic_contact_index'><strong>%name% (%id%)</strong></a> 被添加到 %list%."
mautic.lead.lead.notice.batch_deleted="%count% 个联络人被删除！"
mautic.lead.lead.notice.merged="联系人已合并！"
mautic.lead.lead.notice.removedfromlists="<a href='%url%' data-toggle='ajax' data-menu-link='mautic_contact_index'><strong>%name% (%id%)</strong></a> 被从 %list% 中删除。"
mautic.lead.list.error.cannot.delete.batch="段““%segments%无法删除“”，因为它们正被其他实体使用。有关详细信息，请尝试单独删除每个段。"
mautic.lead.list.error.notfound="没有ID为%id% 已找到！"
mautic.lead.list.frequency.rules.msg="否"
mautic.lead.list.notice.batch_deleted="%count% 段已被删除!"
mautic.lead.note.created="已成功创建注释"
