; YXHK versioned Simplified Chinese translations.
mautic.company.choosecompany.notblank="选择一家公司"
mautic.import.file.required="请选择一个CSV 要上传的文件"
mautic.import.missing.required.fields="'缺少某些必填字段。您必须将%fieldOrFields% \"%requiredFields%.\"'"
mautic.lead.api.tag.required="需要标记标签。"
mautic.lead.avatar.types_invalid="头像是无效图像。请上载gif、jpeg或png图像。"
mautic.lead.contact.field.not.found="'带别名的联系人字段“%alias%“没有找到”"
mautic.lead.contact.field.not.published="'带别名的联系人字段“%alias%“没有发表”"
mautic.lead.contact.wrong.field.type="“联系人字段“%alias%“是“的类型”%fieldType%“但必须是类型“%expectedType%\".'"
mautic.lead.customfield.notblank="此字段为必填字段。"
mautic.lead.dataProtocolMessage="URL 不允许使用“data：”协议。"
mautic.lead.date.invalid="日期无效。必须采用Y-m-d格式，例如1986-07-25。"
mautic.lead.datetime.invalid="日期时间格式无效。有效格式为Y-m-d H：i，例如1986-07-25 11：00。"
mautic.lead.defaultValue.invalid="默认值无效。"
mautic.lead.defaultValue.maxlengthexceeded="默认值不能超过%defaultValueLengthLimit% 个字符。当前长度为%currentLength% 字符."
mautic.lead.email.body.required="需要消息。"
mautic.lead.excluded_lists.conflicting="同一段不能同时排除和包括。"
mautic.lead.field.alias.unique="另一个域已在使用此别名。请选择另一个域或将其留空以自动生成别名。"
mautic.lead.field.boolean.nomissing="需要一个“负面”标签。"
mautic.lead.field.boolean.yesmissing="需要“正”标签。"
mautic.lead.field.char_length_limit.too_short="不能将此值设置为这么短，因为至少有一个现有记录%length% 个字符长。"
mautic.lead.field.column.already.exists="创建自定义字段时出错%field% 因为它已经存在。"
mautic.lead.field.failed="在联系人表中创建新列时出错：%error%."
mautic.lead.field.keyword.invalid="的'%keyword%'关键字是为段筛选器保留请选择其他别名"
mautic.lead.field.keyword.restricted="别名“%alias%'是受限制的字段。请选择其他字段。"
mautic.lead.field.label.maxlength="标签值不能长于{{ limit }}字符"
mautic.lead.field.label.notblank="需要标签。"
mautic.lead.field.select.listmissing="必须指定选择框的列表。用竖线分隔每个选项。即绿色|蓝色|红色"
mautic.lead.field.typenotrecognized="有一个字段类型无法识别。"
mautic.lead.field.unique.is_used="此字段必须是唯一的。"
mautic.lead.field.value.invalid="某些字段“值”无效。授权字符为a-z A-Z 0-9 - _"
mautic.lead.import.dir.notblank="需要导入目录。"
mautic.lead.import.file.notblank="需要导入文件。"
mautic.lead.import.filenotreadable="无法读取导入的csv文件。"
mautic.lead.import.filetoolarge="文件超过允许的最大上载大小%upload_max_filesize%."
mautic.lead.import.matchfields="您必须匹配至少一个字段。"
mautic.lead.list.alias.unique="已在使用中。请选择另一个或将其留空以自动生成。"
mautic.lead.lists.failed="未选择列表，或者您无权访问所选列表之一。"
mautic.lead.lists.required="至少需要一个联系人段。"
mautic.lead.lists.used_in_campaigns="{1}此段用于%campaignNames% 活动请在取消发布前进行检查|[2，Inf]此段用于以下活动：%campaignNames%，请检查后再取消发布。"
mautic.lead.lists.used_in_campaigns.delete="{1}分段%segmentNames% 用于%campaignNames% 活动请检查后再删除|[2，Inf]分段%segmentNames% 在以下活动中使用：%campaignNames%。请检查后再删除。"
mautic.lead.lists.used_in_campaigns.unpublish="{1}分段%segmentNames% 用于%campaignNames% 活动请在取消发布前进行检查|[2，Inf]分段%segmentNames% 在以下活动中使用：%campaignNames%，请检查后再取消发布。"
mautic.lead.note.text.notblank="备注文本不能为空"
mautic.lead.segment.date_invalid="日期字段筛选值“%value%“无效。它的格式必须为YYYY-MM-DD或使用验证中的关键字（您可以在文档中找到这些关键字）。请注意不要使用重复字符。"
mautic.lead.submitaction.formfield.notblank="选择一个表单域。"
mautic.lead.submitaction.leadfield.notblank="选择联系人字段。"
mautic.lead.time.invalid="时间无效。必须采用HH：ii格式，其中00 <= HH <= 23且00 <= ii <= 59，例如11：00。"
mautic.lead_list.is_in_use.delete="分段%segmentNames% 用于%segments%，请在删除之前返回并检查段"
mautic.lead_list.is_in_use.unpublish="分段%segmentNames% 用于%segments%，请在取消发布之前返回并检查段"
