; YXHK versioned Simplified Chinese translations.
mautic.install.database.driver.invalid="提供的数据库驱动程序无效。必须是以下驱动程序之一：%drivers%"
mautic.install.database.path.invalid="路径无效或不可写入"
mautic.install.database.path.warning="警告！！本路径位于公共可访问的 web 根目录下。不建议采用该设置，因为它可能引起安全风险。建议修改为 %root% 之外的路径。"
mautic.install.database.port.invalid="端口号应该为大于 0 的整数。"
mautic.install.password.minlength="密码最少为 6 个字符。"
